/**
 * SUBMODE 10: THE FINAL COLLAPSE — CANONICAL 93-STAGE PROGRESSION
 * 15:00 (900 seconds) Countdown to the Absolute Singularity
 *
 * Each stage features:
 * - Stage number (1 to 93)
 * - Canonical timestamp (15:00 down to 00:00)
 * - Specific Area / Sector Name
 * - Severity level (1 to 10)
 * - EXACT ONE-LINE description of the environmental change or gravitational hazard
 */

export interface Submode10StageDef {
  index: number;
  id: string;
  name: string;
  title: string;
  countdownTime: string;
  triggerTime: number; // in seconds from 00:00 start (0 to 1800 raw, mapped to 0 to 900)
  areaName: string;
  severity: number;
  /** EXACTLY ONE LINE describing the specific environmental change or gravitational hazard */
  hazardDescription: string;
  cause: string;
  physicalEffect: string;
}

export const SUBMODE_10_TOTAL_DURATION_SECONDS = 900; // 15 minutes

const RAW_SUBMODE_10_STAGES: readonly Submode10StageDef[] = [
  // =========================================================================
  // PHASE 1: SINGULARITY AWAKENING & METRIC PERTURBATIONS (Stages 1 – 15, 15:00 – 12:45)
  // =========================================================================
  {
    index: 1,
    id: 'stage_01_metric_awakening',
    name: 'QUANTUM METRIC AWAKENING',
    title: 'STAGE 01 — 15:00 QUANTUM METRIC AWAKENING',
    countdownTime: '15:00',
    triggerTime: 0,
    areaName: 'ORBITAL LAUNCH HIGHWAY',
    severity: 1.0,
    hazardDescription: 'The central singularity stirs, sending micro-gravitational tremors that ripple through the outer orbital highway tarmac.',
    cause: 'Initial black hole tidal gradient perturbation propagating into sector.',
    physicalEffect: 'Subtle lateral drift across track lane with light electromagnetic interference.',
  },
  {
    index: 2,
    id: 'stage_02_stellar_lensing_wake',
    name: 'STELLAR LENSING WAKE',
    title: 'STAGE 02 — 29:40 STELLAR LENSING WAKE',
    countdownTime: '29:40',
    triggerTime: 20,
    areaName: 'ORBITAL LAUNCH HIGHWAY',
    severity: 1.2,
    hazardDescription: 'Background star clusters warp into luminous curved caustics as gravitational lensing bends navigation vectors.',
    cause: 'Light deflection around expanding Schwarzschild curvature.',
    physicalEffect: 'Visual distortion of distant waypoints and optical steering aberration.',
  },
  {
    index: 3,
    id: 'stage_03_orbital_resonance_decay',
    name: 'ORBITAL RESONANCE DECAY',
    title: 'STAGE 03 — 29:20 ORBITAL RESONANCE DECAY',
    countdownTime: '29:20',
    triggerTime: 40,
    areaName: 'STATION DEPARTURE CORRIDOR',
    severity: 1.4,
    hazardDescription: 'Station-keeping thrusters fail across orbital towers, shedding loose solar panel arrays into high-speed flight paths.',
    cause: 'Tidal forces exceed artificial station-keeping gyros.',
    physicalEffect: 'High-velocity debris fragments bouncing off magnetic barriers.',
  },
  {
    index: 4,
    id: 'stage_04_accretion_disk_ignition',
    name: 'ACCRETION DISK IGNITION',
    title: 'STAGE 04 — 29:00 ACCRETION DISK IGNITION',
    countdownTime: '29:00',
    triggerTime: 60,
    areaName: 'ACCRETION PERIMETER ARCH',
    severity: 1.6,
    hazardDescription: 'The inner accretion disk ignites with ember-gold plasma streams, superheating nearby track guidance pylons.',
    cause: 'Infalling interstellar gas heats up through viscous frictional dissipation.',
    physicalEffect: 'Thermal hull radiation load increases and sensor arrays encounter static.',
  },
  {
    index: 5,
    id: 'stage_05_kerr_frame_dragging',
    name: 'KERR FRAME-DRAGGING SHEAR',
    title: 'STAGE 05 — 28:40 KERR FRAME-DRAGGING SHEAR',
    countdownTime: '28:40',
    triggerTime: 80,
    areaName: 'KERR SWIRL EXPANSION',
    severity: 1.8,
    hazardDescription: 'Spacetime itself twists in the direction of the black hole spin, dragging ship flight paths into clockwise yaw drift.',
    cause: 'Lense-Thirring precession dragging inertial reference frames.',
    physicalEffect: 'Continuous rotational torque pulling ships sideways toward the spin axis.',
  },
  {
    index: 6,
    id: 'stage_06_first_gravity_wave_pulse',
    name: 'FIRST GRAVITATIONAL WAVE PULSE',
    title: 'STAGE 06 — 28:20 FIRST GRAVITATIONAL WAVE PULSE',
    countdownTime: '28:20',
    triggerTime: 100,
    areaName: 'KERR SWIRL EXPANSION',
    severity: 2.0,
    hazardDescription: 'A concentric gravitational wave ripple bursts through space, violently shaking ship dampers and vibrating magnetic track rails.',
    cause: 'Asymmetric mass perturbation within the inner ISCO boundary.',
    physicalEffect: 'Periodic heave impulse lifting ships momentarily off suspension fields.',
  },
  {
    index: 7,
    id: 'stage_07_asteroid_belt_subduction',
    name: 'ASTEROID BELT SUBDUCTION',
    title: 'STAGE 07 — 28:00 ASTEROID BELT SUBDUCTION',
    countdownTime: '28:00',
    triggerTime: 120,
    areaName: 'OUTER ASTEROID REEF',
    severity: 2.2,
    hazardDescription: 'An outer asteroid cluster loses orbital equilibrium, raining incandescent metallic boulders diagonally through the racing lane.',
    cause: 'Gravitational capture pulls belt members inward.',
    physicalEffect: 'High-density kinetic hazards requiring rapid evasive maneuvering.',
  },
  {
    index: 8,
    id: 'stage_08_tidal_stretching_micro_debris',
    name: 'TIDAL STRETCHING OF MICRO-DEBRIS',
    title: 'STAGE 08 — 27:40 TIDAL STRETCHING OF MICRO-DEBRIS',
    countdownTime: '27:40',
    triggerTime: 140,
    areaName: 'OUTER ASTEROID REEF',
    severity: 2.4,
    hazardDescription: 'Smaller asteroid rocks stretch into teardrop-shaped molten filaments before shattering into razor-sharp particle curtains.',
    cause: 'Differential gravitational acceleration exceeding tensile rock cohesion.',
    physicalEffect: 'Curved particle slipstreams that erode ship energy shields upon contact.',
  },
  {
    index: 9,
    id: 'stage_09_radio_telemetry_blackout',
    name: 'RADIO TELEMETRY BLACKOUT',
    title: 'STAGE 09 — 27:20 RADIO TELEMETRY BLACKOUT',
    countdownTime: '27:20',
    triggerTime: 160,
    areaName: 'DEEP RELAY SECTOR',
    severity: 2.6,
    hazardDescription: 'Relativistic Doppler shift scatters tactical comms channels, causing HUD radar scans to flicker with phantom ghost echoes.',
    cause: 'High-velocity plasma shearing communication microwave frequencies.',
    physicalEffect: 'HUD radar display intermittently scrambles blips and distance readings.',
  },
  {
    index: 10,
    id: 'stage_10_magnetic_pylon_rupture',
    name: 'MAGNETIC PYLON RUPTURE',
    title: 'STAGE 10 — 27:00 MAGNETIC PYLON RUPTURE',
    countdownTime: '27:00',
    triggerTime: 180,
    areaName: 'DEEP RELAY SECTOR',
    severity: 2.8,
    hazardDescription: 'Guidance Pylon Echo-4 snaps under tidal strain, spewing high-voltage blue electrical arcs that arc between track guardrails.',
    cause: 'Structural resonance coupled with tidal shearing.',
    physicalEffect: 'Empirical lightning hazards draining ship boost tanks on impact.',
  },
  {
    index: 11,
    id: 'stage_11_chromatic_redshift_horizon',
    name: 'CHROMATIC REDSHIFT HORIZON',
    title: 'STAGE 11 — 26:40 CHROMATIC REDSHIFT HORIZON',
    countdownTime: '26:40',
    triggerTime: 200,
    areaName: 'INNER PHOTON APPROACH',
    severity: 3.0,
    hazardDescription: 'Distant celestial objects shift from bright amber to deep crimson, signaling intense gravitational time dilation ahead.',
    cause: 'Severe gravitational redshift near the expanding ergosphere perimeter.',
    physicalEffect: 'Cockpit visor optical filters engage, darkening external starfields.',
  },
  {
    index: 12,
    id: 'stage_12_debris_field_infall_spiral',
    name: 'DEBRIS FIELD INFALL SPIRAL',
    title: 'STAGE 12 — 26:20 DEBRIS FIELD INFALL SPIRAL',
    countdownTime: '26:20',
    triggerTime: 220,
    areaName: 'INNER PHOTON APPROACH',
    severity: 3.1,
    hazardDescription: 'A thousand fragments of a dismantled ore freighter spiral inward, forming a swirling funnel of razor debris.',
    cause: 'Decayed Keplerian orbits collapsing into logarithmic spiral trajectories.',
    physicalEffect: 'Vortical debris stream sweeping horizontally across the racing corridor.',
  },
  {
    index: 13,
    id: 'stage_13_first_rival_geometry_warp',
    name: 'FIRST RIVAL GEOMETRY WARP',
    title: 'STAGE 13 — 26:00 FIRST RIVAL GEOMETRY WARP',
    countdownTime: '26:00',
    triggerTime: 240,
    areaName: 'COMPETITOR GRID LINE',
    severity: 3.2,
    hazardDescription: 'Rival AI ships skimming the lower orbital lane visibly stretch along their hulls, their wingtips pulling toward the void.',
    cause: 'Tidal gradient differential spanning across multi-meter spaceship hulls.',
    physicalEffect: 'Rival ships swerve erratically as aerodynamic and inertial physics distort.',
  },
  {
    index: 14,
    id: 'stage_14_sub_photonic_plasma_arc',
    name: 'SUB-PHOTONIC PLASMA ARC',
    title: 'STAGE 14 — 25:40 SUB-PHOTONIC PLASMA ARC',
    countdownTime: '25:40',
    triggerTime: 260,
    areaName: 'PHOTON SHELL RIDGE',
    severity: 3.4,
    hazardDescription: 'A magnetic loop erupts from the inner accretion disk, whipping a 300-meter arc of superheated ionized gas across the track.',
    cause: 'Magnetic reconnection in the relativistic plasma disc.',
    physicalEffect: 'High-temperature thermal hazard causing rapid hull ablation and steering lock.',
  },
  {
    index: 15,
    id: 'stage_15_outer_station_truss_sever',
    name: 'OUTER STATION TRUSS SEVER',
    title: 'STAGE 15 — 25:20 OUTER STATION TRUSS SEVER',
    countdownTime: '25:20',
    triggerTime: 280,
    areaName: 'PHOTON SHELL RIDGE',
    severity: 3.5,
    hazardDescription: 'The outermost observation ring snaps at its docking joints, shedding rotating habitat modules into the vacuum.',
    cause: 'Tidal torque exceeding structural shear yield limits.',
    physicalEffect: 'Multi-ton rotating megastructures tumbling slowly across the flight corridor.',
  },

  // =========================================================================
  // PHASE 2: ORBITAL RESONANCE DECAY & CELESTIAL DEBRIS (Stages 16 – 30, 25:00 – 20:20)
  // =========================================================================
  {
    index: 16,
    id: 'stage_16_polar_jet_ignition',
    name: 'RELATIVISTIC POLAR JET IGNITION',
    title: 'STAGE 16 — 25:00 RELATIVISTIC POLAR JET IGNITION',
    countdownTime: '25:00',
    triggerTime: 300,
    areaName: 'POLAR VENT CORRIDOR',
    severity: 3.7,
    hazardDescription: 'Twin Blandford-Znajek relativistic jets ignite at the singularity poles, piercing space with blinding purple gamma-ray beams.',
    cause: 'Magnetic extraction of rotational black hole energy.',
    physicalEffect: 'Massive atmospheric luminescence surge and intense vertical electromagnetic buffeting.',
  },
  {
    index: 17,
    id: 'stage_17_satellite_constellation_cascade',
    name: 'SATELLITE CONSTELLATION CASCADE',
    title: 'STAGE 17 — 24:40 SATELLITE CONSTELLATION CASCADE',
    countdownTime: '24:40',
    triggerTime: 320,
    areaName: 'POLAR VENT CORRIDOR',
    severity: 3.8,
    hazardDescription: 'An entire GPS constellation collides in a Kessler cascade, sending hypersonic solar wings slicing across the course.',
    cause: 'Orbital intersection collapse caused by orbital plane compression.',
    physicalEffect: 'Fast-moving razor shard fields reflecting accretion disk glare.',
  },
  {
    index: 18,
    id: 'stage_18_roche_limit_breach',
    name: 'ROCHE LIMIT BREACH',
    title: 'STAGE 18 — 24:20 ROCHE LIMIT BREACH',
    countdownTime: '24:20',
    triggerTime: 340,
    areaName: 'ROCHE SHEAR CANYON',
    severity: 4.0,
    hazardDescription: 'A passing asteroid crosses the fluid Roche limit, crumbling into an elongated stream of crimson dust that blankets the track.',
    cause: 'Tidal forces overcoming internal gravitational self-attraction.',
    physicalEffect: 'Dense particulate fog obscuring turn apexes and reducing engine thruster intake.',
  },
  {
    index: 19,
    id: 'stage_19_track_expansion_joint_failure',
    name: 'TRACK EXPANSION JOINT FAILURE',
    title: 'STAGE 19 — 24:00 TRACK EXPANSION JOINT FAILURE',
    countdownTime: '24:00',
    triggerTime: 360,
    areaName: 'ROCHE SHEAR CANYON',
    severity: 4.1,
    hazardDescription: 'Thermal expansion and gravitational tension tear Segment 14 expansion seams open, creating sudden jagged road chasms.',
    cause: 'Differential tidal stress between track anchoring pylons.',
    physicalEffect: 'Abrupt vertical elevation steps that demand boost-assisted suspension jumps.',
  },
  {
    index: 20,
    id: 'stage_20_synchrotron_blue_shift_flash',
    name: 'SYNCHROTRON BLUE-SHIFT FLASH',
    title: 'STAGE 20 — 23:40 SYNCHROTRON BLUE-SHIFT FLASH',
    countdownTime: '23:40',
    triggerTime: 380,
    areaName: 'INNER HORIZON GORGE',
    severity: 4.3,
    hazardDescription: 'Electrons accelerated to relativistic velocities emit synchrotron radiation, flooding the cockpit with blinding cyan flashes.',
    cause: 'Relativistic beaming along the approaching side of the accretion disk.',
    physicalEffect: 'Momentary visor wash-out causing sensory disorientation on high-speed sweeps.',
  },
  {
    index: 21,
    id: 'stage_21_lunar_fragment_impact',
    name: 'LUNAR FRAGMENT IMPACT',
    title: 'STAGE 21 — 23:20 LUNAR FRAGMENT IMPACT',
    countdownTime: '23:20',
    triggerTime: 400,
    areaName: 'INNER HORIZON GORGE',
    severity: 4.4,
    hazardDescription: 'A cracked lunar core fragment strikes the lower support pylon, sending seismic shockwaves shivering up the track surface.',
    cause: 'Orbital decay of captured planetary moonlet.',
    physicalEffect: 'High-magnitude surface vibration causing vehicle bounce and traction loss.',
  },
  {
    index: 22,
    id: 'stage_22_rival_hull_spaghettification_onset',
    name: 'RIVAL HULL SPAGHETTIFICATION ONSET',
    title: 'STAGE 22 — 23:00 RIVAL HULL SPAGHETTIFICATION ONSET',
    countdownTime: '23:00',
    triggerTime: 420,
    areaName: 'COMPETITOR SECTOR ZERO',
    severity: 4.6,
    hazardDescription: 'Trailing AI rivals trailing in low orbits stretch into needle-thin carbon-fiber silhouettes as gravity draws their mass inward.',
    cause: 'Steepening gravitational gradient across competitor coordinates.',
    physicalEffect: 'Damaged rivals lose lateral control, spinning across the track while elongating.',
  },
  {
    index: 23,
    id: 'stage_23_gravity_gradient_inversion',
    name: 'GRAVITY GRADIENT INVERSION',
    title: 'STAGE 23 — 22:40 GRAVITY GRADIENT INVERSION',
    countdownTime: '22:40',
    triggerTime: 440,
    areaName: 'COMPETITOR SECTOR ZERO',
    severity: 4.7,
    hazardDescription: 'Local artificial gravity buffers fail, causing spaceships to alternate between crushing 8G compression and zero-G buoyancy.',
    cause: 'Interference between station dampening fields and black hole tidal surge.',
    physicalEffect: 'Severe vertical g-force fluctuations altering pitch responsiveness.',
  },
  {
    index: 24,
    id: 'stage_24_plasma_filament_webbing',
    name: 'PLASMA FILAMENT WEBBING',
    title: 'STAGE 24 — 22:20 PLASMA FILAMENT WEBBING',
    countdownTime: '22:20',
    triggerTime: 460,
    areaName: 'ACCRETION SHEAR AXIS',
    severity: 4.8,
    hazardDescription: 'High-energy magnetic plasma threads web between damaged track sections, forming luminous tripwires of burning ionization.',
    cause: 'Magnetic flux tubes bridging ionized debris streams.',
    physicalEffect: 'Shield-draining barrier wires that require precise ducking or speed boosts.',
  },
  {
    index: 25,
    id: 'stage_25_einstein_ring_multiplication',
    name: 'EINSTEIN RING MULTIPLICATION',
    title: 'STAGE 25 — 22:00 EINSTEIN RING MULTIPLICATION',
    countdownTime: '22:00',
    triggerTime: 480,
    areaName: 'ACCRETION SHEAR AXIS',
    severity: 5.0,
    hazardDescription: 'A secondary and tertiary ghost Einstein photon ring emerge, duplicating reflections of rival ships across the sky.',
    cause: 'Photons completing multiple full orbits around the photon sphere.',
    physicalEffect: 'Visual confusion as mirrored ship projections appear to dive from above.',
  },
  {
    index: 26,
    id: 'stage_26_cargo_dock_depressurization',
    name: 'CARGO DOCK DEPRESSURIZATION',
    title: 'STAGE 26 — 21:40 CARGO DOCK DEPRESSURIZATION',
    countdownTime: '21:40',
    triggerTime: 500,
    areaName: 'DEPOT DOCKING SECTOR',
    severity: 5.1,
    hazardDescription: 'Docking Hub Delta ruptures its atmospheric seal, blasting pressurized nitrogen gales and shipping containers across the route.',
    cause: 'Pressure hull failure induced by tidal hoop stress.',
    physicalEffect: 'Violent aerodynamic side-gusts blowing ships off magnetic centerlines.',
  },
  {
    index: 27,
    id: 'stage_27_matter_funnel_whirlwind',
    name: 'MATTER FUNNEL WHIRLWIND',
    title: 'STAGE 27 — 21:20 MATTER FUNNEL WHIRLWIND',
    countdownTime: '21:20',
    triggerTime: 520,
    areaName: 'DEPOT DOCKING SECTOR',
    severity: 5.2,
    hazardDescription: 'A twisting vortex of dust, fuel, and metal shavings forms an accretion maelstrom directly over the chicane complex.',
    cause: 'Vorticity generation in magnetized accretion disk boundary layers.',
    physicalEffect: 'Vortex turbulence dragging ship noses toward the inner guard rail.',
  },
  {
    index: 28,
    id: 'stage_28_coronal_loop_evaporation',
    name: 'CORONAL LOOP EVAPORATION',
    title: 'STAGE 28 — 21:00 CORONAL LOOP EVAPORATION',
    countdownTime: '21:00',
    triggerTime: 540,
    areaName: 'ISCO INNER BOUNDARY',
    severity: 5.3,
    hazardDescription: 'A massive plasma arch collapses inward into the ISCO, triggering a radial thermal flash that boils space dust to vapor.',
    cause: 'Catastrophic reconnection event exhausting magnetic field tension.',
    physicalEffect: 'High-intensity infrared flare overheating propulsion cooling loops.',
  },
  {
    index: 29,
    id: 'stage_29_super_heavy_debris_shearing',
    name: 'SUPER-HEAVY DEBRIS SHEARING',
    title: 'STAGE 29 — 20:40 SUPER-HEAVY DEBRIS SHEARING',
    countdownTime: '20:40',
    triggerTime: 560,
    areaName: 'ISCO INNER BOUNDARY',
    severity: 5.4,
    hazardDescription: 'A 2-kilometer derelict cruiser snaps into three jagged segments that roll horizontally through the primary flight corridor.',
    cause: 'Differential tidal torque across an extended megastructure.',
    physicalEffect: 'Massive physical roadblocks requiring precision split-second routing.',
  },
  {
    index: 30,
    id: 'stage_30_midpoint_gravitational_surge',
    name: 'MIDPOINT GRAVITATIONAL SURGE',
    title: 'STAGE 30 — 20:20 MIDPOINT GRAVITATIONAL SURGE',
    countdownTime: '20:20',
    triggerTime: 580,
    areaName: 'COLLAPSE CREST SECTOR',
    severity: 5.5,
    hazardDescription: 'The first major catastrophe shockwave bursts outward, cracking track segment foundations and sending camera screens rattling.',
    cause: 'Core contraction milestone as central gravitational parameter increases.',
    physicalEffect: 'Sustained lateral acceleration pulse throwing vehicles toward the outer abyss.',
  },

  // =========================================================================
  // PHASE 3: BINARY MERGERS, KILONOVA DETONATIONS & FRAME DRAGGING (Stages 31 – 45, 20:00 – 15:20)
  // =========================================================================
  {
    index: 31,
    id: 'stage_31_neutron_star_companion_approach',
    name: 'NEUTRON STAR COMPANION APPROACH',
    title: 'STAGE 31 — 20:00 NEUTRON STAR COMPANION APPROACH',
    countdownTime: '20:00',
    triggerTime: 600,
    areaName: 'BINARY INSTABILITY ZONE',
    severity: 5.7,
    hazardDescription: 'A runaway ultra-dense neutron star companion spirals into view, sweeping sweeping lighthouse pulsar beams across the track.',
    cause: 'Binary companion entering terminal inward inspiral.',
    physicalEffect: 'Periodic blinding strobes of intense ionizing radiation disrupting shields.',
  },
  {
    index: 32,
    id: 'stage_32_pulsar_beam_sweep',
    name: 'PULSAR BEAM SWEEP',
    title: 'STAGE 32 — 19:40 PULSAR BEAM SWEEP',
    countdownTime: '19:40',
    triggerTime: 620,
    areaName: 'BINARY INSTABILITY ZONE',
    severity: 5.8,
    hazardDescription: 'The neutron star pulsar beam intersects the track, vaporizing safety barriers and frying ship electronic HUD displays.',
    cause: 'Rapid 80Hz rotational sweeping of relativistic polar emission.',
    physicalEffect: 'HUD HUD telemetry glitches with static snow and momentary throttle lag.',
  },
  {
    index: 33,
    id: 'stage_33_gravitational_wave_chirp_burst',
    name: 'GRAVITATIONAL WAVE CHIRP BURST',
    title: 'STAGE 33 — 19:20 GRAVITATIONAL WAVE CHIRP BURST',
    countdownTime: '19:20',
    triggerTime: 640,
    areaName: 'BINARY INSTABILITY ZONE',
    severity: 6.0,
    hazardDescription: 'Spacetime hums at an audible frequency as a gravitational wave chirp contracts track distance and stretches ship hulls.',
    cause: 'Inspiral frequency acceleration prior to binary merger.',
    physicalEffect: 'Acoustic infrasound hum shaking the entire viewport with rhythmic camera compression.',
  },
  {
    index: 34,
    id: 'stage_34_kilonova_precursor_detonation',
    name: 'KILONOVA PRECURSOR DETONATION',
    title: 'STAGE 34 — 19:00 KILONOVA PRECURSOR DETONATION',
    countdownTime: '19:00',
    triggerTime: 660,
    areaName: 'KILONOVA DETONATION RIM',
    severity: 6.1,
    hazardDescription: 'Tidal disruption of the neutron star crust triggers a blinding flash of nuclear synthesis, igniting incandescent gold clouds.',
    cause: 'R-process nucleosynthesis decompressing neutron-rich matter.',
    physicalEffect: 'Radiative pressure wave pushing ships laterally with glowing gold plasma plumes.',
  },
  {
    index: 35,
    id: 'stage_35_hyper_velocity_shrapnel_burst',
    name: 'HYPER-VELOCITY SHRAPNEL BURST',
    title: 'STAGE 35 — 18:40 HYPER-VELOCITY SHRAPNEL BURST',
    countdownTime: '18:40',
    triggerTime: 680,
    areaName: 'KILONOVA DETONATION RIM',
    severity: 6.2,
    hazardDescription: 'Shards of exotic neutronium matter blast outward at 0.1c, punching glowing holes clean through overhead support structures.',
    cause: 'Explosive decompression of stripped degenerate matter.',
    physicalEffect: 'Micro-impact kinetic hazards leaving smoking scorch holes in track panels.',
  },
  {
    index: 36,
    id: 'stage_36_track_torsion_twisting',
    name: 'TRACK TORSION TWISTING',
    title: 'STAGE 36 — 18:20 TRACK TORSION TWISTING',
    countdownTime: '18:20',
    triggerTime: 700,
    areaName: 'KILONOVA DETONATION RIM',
    severity: 6.4,
    hazardDescription: 'A 500-meter straightaway undergoes extreme torsional twist, tilting 45 degrees sideways toward the black hole center.',
    cause: 'Asymmetric gravitational torque between inner and outer edge anchors.',
    physicalEffect: 'Severe camber shift requiring continuous counter-steering and wall-ride physics.',
  },
  {
    index: 37,
    id: 'stage_37_rival_spaghettification_filament_snap',
    name: 'RIVAL SPAGHETTIFICATION FILAMENT SNAP',
    title: 'STAGE 37 — 18:00 RIVAL SPAGHETTIFICATION FILAMENT SNAP',
    countdownTime: '18:00',
    triggerTime: 720,
    areaName: 'COMPETITOR ABYSS FLANK',
    severity: 6.5,
    hazardDescription: 'A rival AI ship caught in the lower vortex stretches 300 meters into glowing filaments before snapping like a cosmic elastic band.',
    cause: 'Complete structural yield of vehicle frame under extreme tidal tensile force.',
    physicalEffect: 'Snapping filaments whip across the track, releasing high-voltage plasma cascades.',
  },
  {
    index: 38,
    id: 'stage_38_quantum_vacuum_instability',
    name: 'QUANTUM VACUUM INSTABILITY',
    title: 'STAGE 38 — 17:40 QUANTUM VACUUM INSTABILITY',
    countdownTime: '17:40',
    triggerTime: 740,
    areaName: 'COMPETITOR ABYSS FLANK',
    severity: 6.6,
    hazardDescription: 'Virtual particle pairs manifest as glowing blue Hawking luminescence along track guardrails, distorting laser guidance lines.',
    cause: 'Curved spacetime background polarizing quantum vacuum fluctuations.',
    physicalEffect: 'Visual shimmer and flickering neon track boundaries that drift under observation.',
  },
  {
    index: 39,
    id: 'stage_39_station_solar_array_collapse',
    name: 'STATION SOLAR ARRAY COLLAPSE',
    title: 'STAGE 39 — 17:20 STATION SOLAR ARRAY COLLAPSE',
    countdownTime: '17:20',
    triggerTime: 760,
    areaName: 'SOLAR MAST PROMENADE',
    severity: 6.7,
    hazardDescription: 'A massive 4-kilometer photovoltaic mast collapses like a felling tree, its burning framework smashing into Sector 8.',
    cause: 'Structural failure of central tension cables under frame-dragging load.',
    physicalEffect: 'Colossal flaming lattice structure crushing half the track surface.',
  },
  {
    index: 40,
    id: 'stage_40_magnetic_monopole_discharge',
    name: 'MAGNETIC MONOPOLE DISCHARGE',
    title: 'STAGE 40 — 17:00 MAGNETIC MONOPOLE DISCHARGE',
    countdownTime: '17:00',
    triggerTime: 780,
    areaName: 'SOLAR MAST PROMENADE',
    severity: 6.8,
    hazardDescription: 'Trapped flux tubes collapse into a blinding spherical EMP sphere that temporarily disables boost conduits and engine afterburners.',
    cause: 'Magnetic reconnection in ultra-dense magnetosphere.',
    physicalEffect: 'Boost gauge drains to zero for 4 seconds; engine sound pitch dips.',
  },
  {
    index: 41,
    id: 'stage_41_matter_tail_spiral_wrap',
    name: 'MATTER TAIL SPIRAL WRAP',
    title: 'STAGE 41 — 16:40 MATTER TAIL SPIRAL WRAP',
    countdownTime: '16:40',
    triggerTime: 800,
    areaName: 'SPIRAL CHASM DESCENT',
    severity: 6.9,
    hazardDescription: 'Infalling debris spirals 360 degrees around the black hole horizon, creating an incandescent spiral ribbon encircling the race path.',
    cause: 'Relativistic geodesic motion wrapping matter streams.',
    physicalEffect: 'Continuous glowing ribbon encircling the sky, casting amber shadows.',
  },
  {
    index: 42,
    id: 'stage_42_second_gravitational_wave_harmonic',
    name: 'SECOND GRAVITATIONAL WAVE HARMONIC',
    title: 'STAGE 42 — 16:20 SECOND GRAVITATIONAL WAVE HARMONIC',
    countdownTime: '16:20',
    triggerTime: 820,
    areaName: 'SPIRAL CHASM DESCENT',
    severity: 7.0,
    hazardDescription: 'A double-frequency gravitational shockwave detonates, causing spacetime to warp in elliptical pulses that squeeze vehicle width.',
    cause: 'Non-linear gravitational self-interaction near event horizon.',
    physicalEffect: 'Ship model compresses horizontally while camera aspect ratio flexes rhythmically.',
  },
  {
    index: 43,
    id: 'stage_43_planetary_mantle_rupture',
    name: 'PLANETARY MANTLE RUPTURE',
    title: 'STAGE 43 — 16:00 PLANETARY MANTLE RUPTURE',
    countdownTime: '16:00',
    triggerTime: 840,
    areaName: 'PLANETARY COLLISION BASIN',
    severity: 7.1,
    hazardDescription: 'A doomed terrestrial planet cracks to its incandescent core, ejecting continents of molten magma into high orbital trajectories.',
    cause: 'Tidal heating melting core and mantle rocks.',
    physicalEffect: 'Giant glowing lava boulders raining down across the racing path.',
  },
  {
    index: 44,
    id: 'stage_44_iron_core_spaghettification',
    name: 'IRON CORE SPAGHETTIFICATION',
    title: 'STAGE 44 — 15:40 IRON CORE SPAGHETTIFICATION',
    countdownTime: '15:40',
    triggerTime: 860,
    areaName: 'PLANETARY COLLISION BASIN',
    severity: 7.2,
    hazardDescription: 'The planet iron core stretches into a thousand-meter metallic spindle, glowing white-hot as it falls toward the ergosphere.',
    cause: 'Differential tidal force overcoming iron metallic cohesion.',
    physicalEffect: 'Massive elongated molten spike plummeting through the flight path.',
  },
  {
    index: 45,
    id: 'stage_45_binary_kilonova_merger_climax',
    name: 'BINARY KILONOVA MERGER CLIMAX',
    title: 'STAGE 45 — 15:20 BINARY KILONOVA MERGER CLIMAX',
    countdownTime: '15:20',
    triggerTime: 880,
    areaName: 'PLANETARY COLLISION BASIN',
    severity: 7.3,
    hazardDescription: 'The neutron star plunges through the event horizon, triggering a super-radiant shockwave that pulverizes all outer sensor relays.',
    cause: 'Final coalescence and ringdown of the companion body into the singularity.',
    physicalEffect: 'Massive whiteout shockwave buffeting the craft and blasting away barrier walls.',
  },

  // =========================================================================
  // PHASE 4: ACCRETION SUPER-RADIANCE & STRUCTURAL RUPTURE (Stages 46 – 60, 15:00 – 10:20)
  // =========================================================================
  {
    index: 46,
    id: 'stage_46_accretion_disk_thermal_shift',
    name: 'ACCRETION DISK THERMAL SHIFT',
    title: 'STAGE 46 — 15:00 ACCRETION DISK THERMAL SHIFT',
    countdownTime: '15:00',
    triggerTime: 900,
    areaName: 'SYNCHROTRON FLUX CORRIDOR',
    severity: 7.4,
    hazardDescription: 'The accretion disk shifts from warm ember to electric cyan and violet, indicating synchrotron radiation reaching critical levels.',
    cause: 'Infall temperature climbing to tens of millions of Kelvin.',
    physicalEffect: 'Intense ultraviolet illumination casting sharp chromatic silhouettes.',
  },
  {
    index: 47,
    id: 'stage_47_track_segment_22_collapse',
    name: 'TRACK SEGMENT 22 COLLAPSE',
    title: 'STAGE 47 — 14:40 TRACK SEGMENT 22 COLLAPSE',
    countdownTime: '14:40',
    triggerTime: 920,
    areaName: 'SYNCHROTRON FLUX CORRIDOR',
    severity: 7.5,
    hazardDescription: 'Segment 22 foundation struts snap, dropping a 400-meter track section into the singularity like falling dominoes.',
    cause: 'Support pillar sheared by relativistic plasma drag.',
    physicalEffect: 'Total track absence requiring mandatory jump pad launch across the abyss.',
  },
  {
    index: 48,
    id: 'stage_48_multiple_rival_spaghettification',
    name: 'MULTIPLE RIVAL SPAGHETTIFICATION',
    title: 'STAGE 48 — 14:20 MULTIPLE RIVAL SPAGHETTIFICATION',
    countdownTime: '14:20',
    triggerTime: 940,
    areaName: 'RIVAL ATTRITION ZONE',
    severity: 7.6,
    hazardDescription: 'Three AI competitor crafts are simultaneously dragged down into the ISCO, stretching into razor-thin rainbow filaments of light.',
    cause: 'Runaway gravitational capture destabilizing lower-lane competitors.',
    physicalEffect: 'Competitor casualty icons light up on HUD as spaghettified trails fade into horizon.',
  },
  {
    index: 49,
    id: 'stage_49_ergosphere_entry_warning',
    name: 'ERGOSPHERE ENTRY WARNING',
    title: 'STAGE 49 — 14:00 ERGOSPHERE ENTRY WARNING',
    countdownTime: '14:00',
    triggerTime: 960,
    areaName: 'ERGOSPHERE BOUNDARY RIFT',
    severity: 7.7,
    hazardDescription: 'Klaxons shriek as the track dips within the static limit; stopping is now physically impossible in this rotating spacetime.',
    cause: 'Crossing the Penrose ergosphere boundary where static observers cannot exist.',
    physicalEffect: 'Forward vehicle inertia locked; reverse braking disabled by spacetime swirl.',
  },
  {
    index: 50,
    id: 'stage_50_penrose_energy_extraction_whirl',
    name: 'PENROSE ENERGY EXTRACTION WHIRL',
    title: 'STAGE 50 — 13:40 PENROSE ENERGY EXTRACTION WHIRL',
    countdownTime: '13:40',
    triggerTime: 980,
    areaName: 'ERGOSPHERE BOUNDARY RIFT',
    severity: 7.8,
    hazardDescription: 'High-energy matter splitting produces negative-energy streams, blasting escaping pilots with supercharged kinetic recoil.',
    cause: 'Penrose process converting rotational black hole energy into outward kinetic blasts.',
    physicalEffect: 'High-speed speedboost pads spawn alongside deadly turbulence pockets.',
  },
  {
    index: 51,
    id: 'stage_51_hab_ring_centrifugal_fracture',
    name: 'HAB-RING CENTRIFUGAL FRACTURE',
    title: 'STAGE 51 — 13:20 HAB-RING CENTRIFUGAL FRACTURE',
    countdownTime: '13:20',
    triggerTime: 1000,
    areaName: 'CENTRIFUGAL HABITAT ARCH',
    severity: 7.9,
    hazardDescription: 'The central spinning habitat ring fractures into four curved arcs that tumble inward like flying scythes.',
    cause: 'Centrifugal overspeed combined with external gravitational pull.',
    physicalEffect: 'Gigantic curved habitat segments sweeping overhead, crushing upper pylons.',
  },
  {
    index: 52,
    id: 'stage_52_atmospheric_containment_breach',
    name: 'ATMOSPHERIC CONTAINMENT BREACH',
    title: 'STAGE 52 — 13:00 ATMOSPHERIC CONTAINMENT BREACH',
    countdownTime: '13:00',
    triggerTime: 1020,
    areaName: 'CENTRIFUGAL HABITAT ARCH',
    severity: 8.0,
    hazardDescription: 'Hab-dome oxygen ignites into a 2-kilometer fireball that billows across the tunnel interior, scorching ship windshields.',
    cause: 'Rapid decompression meeting live electrical conduits.',
    physicalEffect: 'Blinding orange fireball filling the tunnel corridor, reducing visibility to zero.',
  },
  {
    index: 53,
    id: 'stage_53_gravitational_redshift_audio_decay',
    name: 'GRAVITATIONAL REDSHIFT AUDIO DECAY',
    title: 'STAGE 53 — 12:40 GRAVITATIONAL REDSHIFT AUDIO DECAY',
    countdownTime: '12:40',
    triggerTime: 1040,
    areaName: 'TIME DILATION GAP',
    severity: 8.1,
    hazardDescription: 'Engine audio pitches down by two octaves as severe gravitational time dilation stretches sound waves into infrasound groans.',
    cause: 'General relativistic frequency redshift affecting cockpit cabin acoustics.',
    physicalEffect: 'Engine hum pitch drops; countdown announcer voice slows and distorts.',
  },
  {
    index: 54,
    id: 'stage_54_light_cone_tipping_visual',
    name: 'LIGHT-CONE TIPPING VISUAL',
    title: 'STAGE 54 — 12:20 LIGHT-CONE TIPPING VISUAL',
    countdownTime: '12:20',
    triggerTime: 1060,
    areaName: 'TIME DILATION GAP',
    severity: 8.2,
    hazardDescription: 'Forward light cones visibly tip toward the singularity, making the black hole appear to wrap 180 degrees around the front windshield.',
    cause: 'Extreme photon trajectory bending as null geodesics tilt inward.',
    physicalEffect: 'Panoramic optical illusion making escape vectors look curved and impossible.',
  },
  {
    index: 55,
    id: 'stage_55_route_split_initialization',
    name: 'ROUTE SPLIT INITIALIZATION',
    title: 'STAGE 55 — 12:00 ROUTE SPLIT INITIALIZATION',
    countdownTime: '12:00',
    triggerTime: 1080,
    areaName: 'TRIFURCATION JUNCTION ZERO',
    severity: 8.3,
    hazardDescription: 'Emergency junction signals activate: three divergent escape corridors unlock ahead as main highway collapses behind.',
    cause: 'Automatic evacuation routing protocol triggered by catastrophic loss of orbit.',
    physicalEffect: 'HUD illuminates three route vectors: Route 01 Launcher, Route 02 Emergency, Route 03 Wormhole.',
  },
  {
    index: 56,
    id: 'stage_56_destruction_front_acceleration',
    name: 'DESTRUCTION FRONT ACCELERATION',
    title: 'STAGE 56 — 11:40 DESTRUCTION FRONT ACCELERATION',
    countdownTime: '11:40',
    triggerTime: 1100,
    areaName: 'TRIFURCATION JUNCTION ZERO',
    severity: 8.4,
    hazardDescription: 'The collapse wave accelerates to 180 km/h, consuming the track surface directly behind trailing racers in a spray of sparks.',
    cause: 'Inward runaway of the gravitational collapse horizon.',
    physicalEffect: 'Destruction distance meter drops on HUD; looking back reveals gaping void.',
  },
  {
    index: 57,
    id: 'stage_57_antimatter_fuel_tanker_explosion',
    name: 'ANTIMATTER FUEL TANKER EXPLOSION',
    title: 'STAGE 57 — 11:20 ANTIMATTER FUEL TANKER EXPLOSION',
    countdownTime: '11:20',
    triggerTime: 1120,
    areaName: 'FUEL MATRIX VAULT',
    severity: 8.5,
    hazardDescription: 'An abandoned antimatter transport barge detonates near Pylon 31, creating a pure magenta gamma-ray flash across the sector.',
    cause: 'Magnetic containment bottle collapse caused by tidal pinching.',
    physicalEffect: 'Shockwave violently jolts ship handling and flips hovering track debris.',
  },
  {
    index: 58,
    id: 'stage_58_spaghettified_plasma_rain',
    name: 'SPAGHETTIFIED PLASMA RAIN',
    title: 'STAGE 58 — 11:00 SPAGHETTIFIED PLASMA RAIN',
    countdownTime: '11:00',
    triggerTime: 1140,
    areaName: 'FUEL MATRIX VAULT',
    severity: 8.6,
    hazardDescription: 'Torn remnants of the fuel tanker rain downward as high-velocity spaghettified plasma noodles that burn on track contact.',
    cause: 'Relativistic acceleration of ionized containment fluid.',
    physicalEffect: 'Corrosive puddles forming on track that inflict continuous shield burn.',
  },
  {
    index: 59,
    id: 'stage_59_magnetic_rail_polarity_flip',
    name: 'MAGNETIC RAIL POLARITY FLIP',
    title: 'STAGE 59 — 10:40 MAGNETIC RAIL POLARITY FLIP',
    countdownTime: '10:40',
    triggerTime: 1160,
    areaName: 'MAGNETIC LEVITATION CHUTE',
    severity: 8.6,
    hazardDescription: 'Track levitation coils short-circuit, rapidly inverting polarity and slamming ships into the road before hurling them upward.',
    cause: 'Inductive surge induced by collapsing interstellar magnetic fields.',
    physicalEffect: 'Vehicle slams hard onto deck; suspension sparks fly before ship bounces high.',
  },
  {
    index: 60,
    id: 'stage_60_deep_infrasound_resonance',
    name: 'DEEP INFRASOUND RESONANCE',
    title: 'STAGE 60 — 10:20 DEEP INFRASOUND RESONANCE',
    countdownTime: '10:20',
    triggerTime: 1180,
    areaName: 'MAGNETIC LEVITATION CHUTE',
    severity: 8.7,
    hazardDescription: 'A 24 Hz infrasound frequency vibrates cockpit canopies to the threshold of shattering, vibrating user controls.',
    cause: 'Quasinormal mode ringdown of the perturbed Kerr metric.',
    physicalEffect: 'Continuous camera shake and blurred vision across dashboard dials.',
  },

  // =========================================================================
  // PHASE 5: ERGOSPHERE SHEAR & RIVAL SPAGHETTIFICATION CASCADES (Stages 61 – 75, 10:00 – 05:20)
  // =========================================================================
  {
    index: 61,
    id: 'stage_61_terminal_evacuation_alert',
    name: 'TERMINAL EVACUATION ALERT',
    title: 'STAGE 61 — 10:00 TERMINAL EVACUATION ALERT',
    countdownTime: '10:00',
    triggerTime: 1200,
    areaName: 'EVACUATION THRESHOLD',
    severity: 8.8,
    hazardDescription: 'All sector alarms blare in unison: ten minutes remaining until total singularity collapse; all non-escape tracks condemned.',
    cause: 'Command station automated countdown entering final critical phase.',
    physicalEffect: 'Pulsing crimson HUD emergency banners and repeating warning sirens.',
  },
  {
    index: 62,
    id: 'stage_62_photon_sphere_grazing',
    name: 'PHOTON SPHERE GRAZING',
    title: 'STAGE 62 — 09:40 PHOTON SPHERE GRAZING',
    countdownTime: '09:40',
    triggerTime: 1220,
    areaName: 'PHOTON ORBIT RIDGE',
    severity: 8.9,
    hazardDescription: 'The lower escape chicane skims the photon sphere at 1.5 Schwarzschild radii; light loops endlessly in glowing gold rings.',
    cause: 'Approaching the unstable circular photon orbit boundary.',
    physicalEffect: 'The player can see the back of their own ship projected directly ahead.',
  },
  {
    index: 63,
    id: 'stage_63_rival_leader_spaghettification',
    name: 'RIVAL LEADER SPAGHETTIFICATION',
    title: 'STAGE 63 — 09:20 RIVAL LEADER SPAGHETTIFICATION',
    countdownTime: '09:20',
    triggerTime: 1240,
    areaName: 'PHOTON ORBIT RIDGE',
    severity: 9.0,
    hazardDescription: 'The lead rival AI ship is pulled from the track by a gravitational vortex, stretching 800 meters into ribbons before dissolving.',
    cause: 'Unrecoverable loss of orbital speed dragging ship below ISCO radius.',
    physicalEffect: 'Dramatic cinematic dissolution of competitor; rank automatically promotes.',
  },
  {
    index: 64,
    id: 'stage_64_track_segment_35_buckling',
    name: 'TRACK SEGMENT 35 BUCKLING',
    title: 'STAGE 64 — 09:00 TRACK SEGMENT 35 BUCKLING',
    countdownTime: '09:00',
    triggerTime: 1260,
    areaName: 'STRUCTURAL FAULT 35',
    severity: 9.0,
    hazardDescription: 'Track Segment 35 buckles upward like an earthquake fault, forming a steep 30-meter ski jump over a sea of white-hot plasma.',
    cause: 'Compressive failure of longitudinal track dampers.',
    physicalEffect: 'Forced high-altitude launch; mid-air pitch leveling required for survival.',
  },
  {
    index: 65,
    id: 'stage_65_extreme_frame_dragging_swirl',
    name: 'EXTREME FRAME-DRAGGING SWIRL',
    title: 'STAGE 65 — 08:40 EXTREME FRAME-DRAGGING SWIRL',
    countdownTime: '08:40',
    triggerTime: 1280,
    areaName: 'STRUCTURAL FAULT 35',
    severity: 9.1,
    hazardDescription: 'Rotational space drag reaches 400 m/s, forcing all moving crafts into a mandatory clockwise orbit around the black hole maw.',
    cause: 'Kerr spin parameter approaching theoretical extremal limit (a = 0.998M).',
    physicalEffect: 'Extreme rightward lateral drift; steering must stay locked left to stay on track.',
  },
  {
    index: 66,
    id: 'stage_66_debris_ring_collision',
    name: 'DEBRIS RING COLLISION',
    title: 'STAGE 66 — 08:20 DEBRIS RING COLLISION',
    countdownTime: '08:20',
    triggerTime: 1300,
    areaName: 'ACCRETION SHOCK FRONTAL',
    severity: 9.1,
    hazardDescription: 'Two counter-rotating debris rings collide at 30 km/s, sending a blinding shockwave of incandescent shrapnel across the track.',
    cause: 'Intersection of retrograde and prograde accretion matter rings.',
    physicalEffect: 'Dense firewall of molten tungsten and silicon spanning the whole road.',
  },
  {
    index: 67,
    id: 'stage_67_player_hull_tidal_strain',
    name: 'PLAYER HULL TIDAL STRAIN',
    title: 'STAGE 67 — 08:00 PLAYER HULL TIDAL STRAIN',
    countdownTime: '08:00',
    triggerTime: 1320,
    areaName: 'ACCRETION SHOCK FRONTAL',
    severity: 9.2,
    hazardDescription: 'Structural integrity warnings scream as the player ship cockpit groans; rivets pop and canopy seams vent cooling frost.',
    cause: 'Tidal forces directly engaging player spaceship chassis.',
    physicalEffect: 'Hull integrity meter flickers; audio cues of metal groaning and creaking.',
  },
  {
    index: 68,
    id: 'stage_68_electromagnetic_null_field',
    name: 'ELECTROMAGNETIC NULL FIELD',
    title: 'STAGE 68 — 07:40 ELECTROMAGNETIC NULL FIELD',
    countdownTime: '07:40',
    triggerTime: 1340,
    areaName: 'NULL FIELD PASSAGE',
    severity: 9.2,
    hazardDescription: 'A pocket of magnetically neutralized vacuum cuts out shield regeneration completely, leaving bare titanium armor exposed.',
    cause: 'Zero-point magnetic boundary layer in the shear zone.',
    physicalEffect: 'Shields offline; all incoming projectile and thermal damage cuts straight to hull.',
  },
  {
    index: 69,
    id: 'stage_69_plasma_cyclone_touchdown',
    name: 'PLASMA CYCLONE TOUCHDOWN',
    title: 'STAGE 69 — 07:20 PLASMA CYCLONE TOUCHDOWN',
    countdownTime: '07:20',
    triggerTime: 1360,
    areaName: 'NULL FIELD PASSAGE',
    severity: 9.3,
    hazardDescription: 'A vertical funnel of violet plasma touches down on the banked turn, spinning at supersonic speed with flaming vortex tendrils.',
    cause: 'Relativistic Kelvin-Helmholtz instability in the accretion corona.',
    physicalEffect: 'Mobile atmospheric hazard wandering across lane paths.',
  },
  {
    index: 70,
    id: 'stage_70_route_01_orbital_launcher_reveal',
    name: 'ROUTE 01 ORBITAL LAUNCHER REVEAL',
    title: 'STAGE 70 — 07:00 ROUTE 01 ORBITAL LAUNCHER REVEAL',
    countdownTime: '07:00',
    triggerTime: 1380,
    areaName: 'TERMINAL ASCENT RAMP',
    severity: 9.3,
    hazardDescription: 'The massive physical Orbital Launcher emerges ahead, blazing green beacon arrays and spinning magnetic lock guide rings.',
    cause: 'Automated escape tower beacon activation.',
    physicalEffect: 'Route 01 gate lights ignite in sequence; navigation vector locks onto runway.',
  },
  {
    index: 71,
    id: 'stage_71_orbital_highway_super_tear',
    name: 'ORBITAL HIGHWAY SUPER-TEAR',
    title: 'STAGE 71 — 06:40 ORBITAL HIGHWAY SUPER-TEAR',
    countdownTime: '06:40',
    triggerTime: 1400,
    areaName: 'TERMINAL ASCENT RAMP',
    severity: 9.4,
    hazardDescription: 'The standard return circuit snaps cleanly in two behind the launch ramp, spiraling into the abyss like cut ribbons.',
    cause: 'Catastrophic failure of last remaining station anchor.',
    physicalEffect: 'Old track completely severed; turning back or missing the launcher is fatal.',
  },
  {
    index: 72,
    id: 'stage_72_third_gravitational_wave_deluge',
    name: 'THIRD GRAVITATIONAL WAVE DELUGE',
    title: 'STAGE 72 — 06:20 THIRD GRAVITATIONAL WAVE DELUGE',
    countdownTime: '06:20',
    triggerTime: 1420,
    areaName: 'TERMINAL ASCENT RAMP',
    severity: 9.4,
    hazardDescription: 'A series of rapid-fire gravitational shockwave pulses hit like ocean breakers, launching debris clouds vertically into space.',
    cause: 'Singularity settling into final non-axisymmetric core configuration.',
    physicalEffect: 'Continuous rhythm of heave punches shaking ship pitch and roll.',
  },
  {
    index: 73,
    id: 'stage_73_secondary_photon_ring_flare',
    name: 'SECONDARY PHOTON RING FLARE',
    title: 'STAGE 73 — 06:00 SECONDARY PHOTON RING FLARE',
    countdownTime: '06:00',
    triggerTime: 1440,
    areaName: 'PHOTON SHELL PERIMETER',
    severity: 9.5,
    hazardDescription: 'The secondary photon ring flares with diamond brilliance, casting stark geometric shadows of disintegrating stations.',
    cause: 'Caustic focusing of relativistic light rays.',
    physicalEffect: 'High-contrast lighting illuminating the final runway in ghostly monochrome.',
  },
  {
    index: 74,
    id: 'stage_74_route_02_emergency_chute_breach',
    name: 'ROUTE 02 EMERGENCY CHUTE BREACH',
    title: 'STAGE 74 — 05:40 ROUTE 02 EMERGENCY CHUTE BREACH',
    countdownTime: '05:40',
    triggerTime: 1460,
    areaName: 'PHOTON SHELL PERIMETER',
    severity: 9.5,
    hazardDescription: 'The outer conduit of Escape Route 02 buckles under tidal stress, venting supercooled liquid helium that freezes track panels.',
    cause: 'Cryogenic coolant line rupture under extreme g-load.',
    physicalEffect: 'Slick ice zones on Route 02 with zero frictional steering authority.',
  },
  {
    index: 75,
    id: 'stage_75_wormhole_mouth_gravitational_clash',
    name: 'WORMHOLE MOUTH GRAVITATIONAL CLASH',
    title: 'STAGE 75 — 05:20 WORMHOLE MOUTH GRAVITATIONAL CLASH',
    countdownTime: '05:20',
    triggerTime: 1480,
    areaName: 'WORMHOLE THROAT GATE',
    severity: 9.5,
    hazardDescription: 'The Route 03 Einstein-Rosen bridge throat clashes with the black hole gravity field, spitting spatial distortion ripples.',
    cause: 'Gravitational field superposition between exotic throat and Kerr metric.',
    physicalEffect: 'Spacetime mirrors bend visually, producing double-vision tunnel effects.',
  },

  // =========================================================================
  // PHASE 6: TERMINAL TIDAL DISRUPTION & ESCAPE ROUTE FRACTURE (Stages 76 – 88, 05:00 – 01:20)
  // =========================================================================
  {
    index: 76,
    id: 'stage_76_five_minute_extinction_mark',
    name: 'FIVE-MINUTE EXTINCTION MARK',
    title: 'STAGE 76 — 05:00 FIVE-MINUTE EXTINCTION MARK',
    countdownTime: '05:00',
    triggerTime: 1500,
    areaName: 'ORBITAL LAUNCHER CORRIDOR',
    severity: 9.6,
    hazardDescription: 'T-minus 05:00: The countdown clock flashes violet as the black hole diameter visibly expands, swallowing the horizon.',
    cause: 'Mass accretion spike expanding the apparent event horizon radius.',
    physicalEffect: 'Black hole disc looms massive in sky; dark shadow encroaches on track edges.',
  },
  {
    index: 77,
    id: 'stage_77_magnetic_lock_guidance_sweep',
    name: 'MAGNETIC LOCK GUIDANCE SWEEP',
    title: 'STAGE 77 — 04:40 MAGNETIC LOCK GUIDANCE SWEEP',
    countdownTime: '04:40',
    triggerTime: 1520,
    areaName: 'ORBITAL LAUNCHER CORRIDOR',
    severity: 9.6,
    hazardDescription: 'Launcher Magnetic Lock sensors engage, painting a narrow high-speed guidance corridor down the center of the runway.',
    cause: 'Target acquisition laser array locking ship transponder.',
    physicalEffect: 'Bright cyan lane guidelines illuminate; aligning within locks speed assist.',
  },
  {
    index: 78,
    id: 'stage_78_acceleration_ring_1_overcharge',
    name: 'ACCELERATION RING 1 OVERCHARGE',
    title: 'STAGE 78 — 04:20 ACCELERATION RING 1 OVERCHARGE',
    countdownTime: '04:20',
    triggerTime: 1540,
    areaName: 'ACCELERATION RING 1',
    severity: 9.7,
    hazardDescription: 'Ring 1 inductors overcharge with Cherenkov radiation, glowing blinding neon cyan as they prep a 300% velocity boost.',
    cause: 'High-voltage capacitors draining station emergency reactors.',
    physicalEffect: 'Immense forward acceleration thrust pressing the pilot back into seat.',
  },
  {
    index: 79,
    id: 'stage_79_station_spire_implosion',
    name: 'STATION SPIRE IMPLOSION',
    title: 'STAGE 79 — 04:00 STATION SPIRE IMPLOSION',
    countdownTime: '04:00',
    triggerTime: 1560,
    areaName: 'ACCELERATION RING 1',
    severity: 9.7,
    hazardDescription: 'The remaining central communications spire crumbles floor-by-floor, collapsing into a 100-meter needle of crushed alloy.',
    cause: 'Unbearable tidal compressive stress collapsing internal vacuum chambers.',
    physicalEffect: 'Debris cloud showers Ring 1 exterior; sparks cascade down the launch tunnel.',
  },
  {
    index: 80,
    id: 'stage_80_acceleration_ring_2_lock',
    name: 'ACCELERATION RING 2 LOCK',
    title: 'STAGE 80 — 03:40 ACCELERATION RING 2 LOCK',
    countdownTime: '03:40',
    triggerTime: 1580,
    areaName: 'ACCELERATION RING 2',
    severity: 9.7,
    hazardDescription: 'Ring 2 magnetic clamps activate, stabilizing ship trajectory against violent lateral 15G tidal turbulence.',
    cause: 'Second-stage linear induction coils engaging vehicle undercarriage.',
    physicalEffect: 'Velocity surpasses 800 km/h; external stars blur into continuous light-lines.',
  },
  {
    index: 81,
    id: 'stage_81_event_horizon_encroachment',
    name: 'EVENT HORIZON ENCROACHMENT',
    title: 'STAGE 81 — 03:20 EVENT HORIZON ENCROACHMENT',
    countdownTime: '03:20',
    triggerTime: 1600,
    areaName: 'ACCELERATION RING 2',
    severity: 9.8,
    hazardDescription: 'The event horizon boundary encroaches to within 200 meters of the launch rail; space behind is absolute pitch blackness.',
    cause: 'Schwarzschild radius expanding toward final mass saturation.',
    physicalEffect: 'All ambient light behind the vehicle vanishes; negative exposure effect.',
  },
  {
    index: 82,
    id: 'stage_82_acceleration_ring_3_hyperspeed',
    name: 'ACCELERATION RING 3 HYPERSPEED',
    title: 'STAGE 82 — 03:00 ACCELERATION RING 3 HYPERSPEED',
    countdownTime: '03:00',
    triggerTime: 1620,
    areaName: 'ACCELERATION RING 3',
    severity: 9.8,
    hazardDescription: 'Ring 3 detonates with plasma thrust, firing the spaceship into escape velocity along the calibrated orbital gate vector.',
    cause: 'Third-stage kinetic booster unleashing stored magnetic flux.',
    physicalEffect: 'Speedometer pins beyond 1,200 km/h; field-of-view stretches into tunnel vision.',
  },
  {
    index: 83,
    id: 'stage_83_orbital_gate_penetration',
    name: 'ORBITAL GATE PENETRATION',
    title: 'STAGE 83 — 02:40 ORBITAL GATE PENETRATION',
    countdownTime: '02:40',
    triggerTime: 1640,
    areaName: 'ORBITAL GATE THRESHOLD',
    severity: 9.8,
    hazardDescription: 'The ship pierces through the shimmering containment shield of the Orbital Gate, breaking free of the collapsing sector.',
    cause: 'Crossing the boundary layer into the reinforced orbital escape tube.',
    physicalEffect: 'Sonic boom shockwave repelling external black hole accretion particles.',
  },
  {
    index: 84,
    id: 'stage_84_collapse_wave_vaporizes_launch_runway',
    name: 'COLLAPSE WAVE VAPORIZES LAUNCH RUNWAY',
    title: 'STAGE 84 — 02:20 COLLAPSE WAVE VAPORIZES LAUNCH RUNWAY',
    countdownTime: '02:20',
    triggerTime: 1660,
    areaName: 'ORBITAL GATE THRESHOLD',
    severity: 9.9,
    hazardDescription: 'The launch runway and all three rings disintegrate into spaghettified particle filaments milliseconds behind the ship exhaust.',
    cause: 'Total consumption of launch structure by the advancing destruction front.',
    physicalEffect: 'Blinding Cherenkov flash in rear mirrors as the entire complex dissolves.',
  },
  {
    index: 85,
    id: 'stage_85_escape_vector_magnetic_tunnel',
    name: 'ESCAPE VECTOR MAGNETIC TUNNEL',
    title: 'STAGE 85 — 02:00 ESCAPE VECTOR MAGNETIC TUNNEL',
    countdownTime: '02:00',
    triggerTime: 1680,
    areaName: 'STATION APPROACH TUBE',
    severity: 9.9,
    hazardDescription: 'The reinforced pressurized approach tunnel buffers the ship, its armored blast shields sliding shut behind the vessel.',
    cause: 'Emergency station intake protocol sealing outer airlocks.',
    physicalEffect: 'External turbulence ceases; smooth decelerating magnetic drag engages.',
  },
  {
    index: 86,
    id: 'stage_86_station_outer_airlock_transition',
    name: 'STATION OUTER AIRLOCK TRANSITION',
    title: 'STAGE 86 — 01:40 STATION OUTER AIRLOCK TRANSITION',
    countdownTime: '01:40',
    triggerTime: 1700,
    areaName: 'STATION AIRLOCK VAULT',
    severity: 9.9,
    hazardDescription: 'Heavy blast doors seal with pneumatic thunder, locking the doomed universe outside behind meter-thick tungsten shielding.',
    cause: 'Sequential bulkheads sealing against external vacuum and radiation.',
    physicalEffect: 'Deep metallic clank audio cues; cabin atmosphere pressurizes to 1.0 bar.',
  },
  {
    index: 87,
    id: 'stage_87_hangar_bay_docking_alignment',
    name: 'HANGAR BAY DOCKING ALIGNMENT',
    title: 'STAGE 87 — 01:20 HANGAR BAY DOCKING ALIGNMENT',
    countdownTime: '01:20',
    triggerTime: 1720,
    areaName: 'SANCTUARY DOCKING BAY',
    severity: 9.9,
    hazardDescription: 'Hangar guide lasers illuminate the primary docking cradle; thrusters fire in micro-bursts to achieve docking alignment.',
    cause: 'Automated guidance beacon guiding ship into hydraulic arrestor cradle.',
    physicalEffect: 'Vehicle speed smoothly drops below 50 km/h into landing orientation.',
  },
  {
    index: 88,
    id: 'stage_88_magnetic_clamps_lock',
    name: 'MAGNETIC CLAMPS LOCK // SHIP SECURED',
    title: 'STAGE 88 — 01:00 MAGNETIC CLAMPS LOCK // SHIP SECURED',
    countdownTime: '01:00',
    triggerTime: 1740,
    areaName: 'SANCTUARY DOCKING BAY',
    severity: 9.9,
    hazardDescription: 'Four massive hydraulic magnetic clamps snap onto the ship landing pads; SHIP_SECURED status is authoritatively confirmed.',
    cause: 'Successful capture and hard-locking of spaceship landing gear.',
    physicalEffect: 'Clamps lock with green status lights; HUD displays SHIP SECURED.',
  },

  // =========================================================================
  // PHASE 7: SINGULARITY CONVERGENCE, 00:00 IMPLOSION & COSMIC TRANSMUTATION (Stages 89 – 93, 00:40 – 00:00)
  // =========================================================================
  {
    index: 89,
    id: 'stage_89_observation_deck_panorama_reveal',
    name: 'OBSERVATION DECK PANORAMA REVEAL',
    title: 'STAGE 89 — 00:40 OBSERVATION DECK PANORAMA REVEAL',
    countdownTime: '00:40',
    triggerTime: 1760,
    areaName: 'OBSERVATION PANORAMA DECK',
    severity: 10.0,
    hazardDescription: 'The safe station observation blast shutters retract, revealing an unobstructed panoramic view of the singularity at critical mass.',
    cause: 'Station shelter observation protocol revealing sector demise.',
    physicalEffect: 'Cinematic camera pans outward over the observation deck glass.',
  },
  {
    index: 90,
    id: 'stage_90_universal_matter_infall_funnel',
    name: 'UNIVERSAL MATTER INFALL FUNNEL',
    title: 'STAGE 90 — 00:30 UNIVERSAL MATTER INFALL FUNNEL',
    countdownTime: '00:30',
    triggerTime: 1770,
    areaName: 'OBSERVATION PANORAMA DECK',
    severity: 10.0,
    hazardDescription: 'All remaining matter of the cosmos—stars, track shards, and nebulae—stretches into glowing filaments funneled into the singularity core.',
    cause: 'Gravitational capture consuming all remnants within five astronomical units.',
    physicalEffect: 'Billions of spaghettified particle filaments plunging into the central abyss.',
  },
  {
    index: 91,
    id: 'stage_91_t_minus_ten_singularity_contraction',
    name: 'T-MINUS 00:10 SINGULARITY CONTRACTION',
    title: 'STAGE 91 — 00:10 T-MINUS 10 SINGULARITY CONTRACTION',
    countdownTime: '00:10',
    triggerTime: 1790,
    areaName: 'OBSERVATION PANORAMA DECK',
    severity: 10.0,
    hazardDescription: 'The entire accretion disk accelerates violently, contracting inward into an infinitesimal pinpoint of absolute blackness.',
    cause: 'Implosion of accretion disc into the central event horizon.',
    physicalEffect: 'All surrounding light is vacuumed inward; universe briefly darkens to total zero.',
  },
  {
    index: 92,
    id: 'stage_92_terminal_super_radiant_flash',
    name: 'TERMINAL SUPER-RADIANT HAWKING FLASH',
    title: 'STAGE 92 — 00:02 TERMINAL SUPER-RADIANT FLASH',
    countdownTime: '00:02',
    triggerTime: 1798,
    areaName: 'OBSERVATION PANORAMA DECK',
    severity: 10.0,
    hazardDescription: 'At T-minus 00:02, a flash of pure Hawking radiation and Cherenkov violet light bursts from the collapsed singularity throat.',
    cause: 'Quantum evaporation shockwave as horizon reaches maximum Planck temperature.',
    physicalEffect: 'Pure blinding violet-blue pulse washing across the cosmic observation window.',
  },
  {
    index: 93,
    id: 'stage_93_00_00_absolute_destruction_rebirth',
    name: '00:00 ABSOLUTE DESTRUCTION // COSMIC AFTERMATH',
    title: 'STAGE 93 — 00:00 ABSOLUTE DESTRUCTION // COSMIC AFTERMATH',
    countdownTime: '00:00',
    triggerTime: 1800,
    areaName: 'QUIESCENT SINGULARITY HORIZON',
    severity: 10.0,
    hazardDescription: 'The 15:00 clock strikes 00:00; absolute destruction ripples through remnants as the singularity stabilizes into an eternal Kerr remnant.',
    cause: 'Terminal gravitational collapse completion and ringdown into quiescent equilibrium.',
    physicalEffect: 'Spherical void shockwave expands into silent space; mission survival telemetry seals successfully.',
  },
];

/**
 * Formats a countdown value in seconds (e.g. 900 -> "15:00.00")
 */
export function formatSubmode10Countdown(remainingSeconds: number, withDecimals = false): string {
  const safe = Math.max(0, remainingSeconds);
  const minutes = Math.floor(safe / 60);
  const seconds = Math.floor(safe % 60);
  const mm = minutes.toString().padStart(2, '0');
  const ss = seconds.toString().padStart(2, '0');
  if (withDecimals) {
    const hundredths = Math.floor((safe % 1) * 100);
    return `${mm}:${ss}.${hundredths.toString().padStart(2, '0')}`;
  }
  return `${mm}:${ss}`;
}

export const SUBMODE_10_STAGES: readonly Submode10StageDef[] = RAW_SUBMODE_10_STAGES.map((stage) => {
  const scaledTrigger = Math.round((stage.triggerTime / 1800) * 900);
  const remaining = Math.max(0, 900 - scaledTrigger);
  const countdownTime = formatSubmode10Countdown(remaining);
  const title = stage.title.replace(/\d{2}:\d{2}/, countdownTime).replace(/30:00/g, '15:00');
  const hazardDescription = stage.hazardDescription.replace(/30:00/g, '15:00');
  return {
    ...stage,
    triggerTime: scaledTrigger,
    countdownTime,
    title,
    hazardDescription,
  };
});

/**
 * Returns the active Submode 10 stage based on elapsed time (0 to 900s).
 */
export function getActiveSubmode10Stage(elapsedSeconds: number): Submode10StageDef {
  const clamped = Math.max(0, Math.min(SUBMODE_10_TOTAL_DURATION_SECONDS, elapsedSeconds));
  // Binary search or linear search for exact bracket
  for (let i = SUBMODE_10_STAGES.length - 1; i >= 0; i--) {
    if (clamped >= SUBMODE_10_STAGES[i].triggerTime) {
      return SUBMODE_10_STAGES[i];
    }
  }
  return SUBMODE_10_STAGES[0];
}

/**
 * Returns the next upcoming Submode 10 stage, or null if on the final stage.
 */
export function getNextSubmode10Stage(elapsedSeconds: number): {
  stage: Submode10StageDef | null;
  secondsUntil: number;
} {
  const current = getActiveSubmode10Stage(elapsedSeconds);
  if (current.index >= SUBMODE_10_STAGES.length) {
    return { stage: null, secondsUntil: 0 };
  }
  const nextStage = SUBMODE_10_STAGES[current.index]; // 1-indexed so index is the next in 0-indexed array
  const clamped = Math.max(0, Math.min(SUBMODE_10_TOTAL_DURATION_SECONDS, elapsedSeconds));
  return {
    stage: nextStage,
    secondsUntil: Math.max(0, nextStage.triggerTime - clamped),
  };
}
