import { FactionInfo, StoryMission } from '../types';

export const COSMIC_FACTIONS: Record<string, FactionInfo> = {
  apex_syndicate: {
    id: 'apex_syndicate',
    name: 'Apex Syndicate',
    motto: 'Dominate the Grid, Crush the Void',
    lore: 'An industrial consortium of augmented cybernetic pilots commanding high-density titanium alloy crafts. They favor aggressive drafting, kinetic bumper impacts, and ruthless tactical blockades.',
    color: '#ff0055',
    icon: 'ShieldAlert',
    bonusText: '+15% Kinetic Collision Resistance & Draft Surge',
    championPilot: 'Commander Korr',
  },
  void_vanguard: {
    id: 'void_vanguard',
    name: 'Void Vanguard',
    motto: 'Where Coordinates End, We Reign',
    lore: 'Deep-space explorers and dimensional cartographers who chart the uncharted sectors. They ride hyper-agile interceptors designed to thread unstable wormhole gaps and razor-sharp turns.',
    color: '#00f0ff',
    icon: 'Compass',
    bonusText: '+20% Cornering Grip & Wormhole Slipstream Drift',
    championPilot: 'Ace Jax "Vector" Vance',
  },
  quantum_pulse: {
    id: 'quantum_pulse',
    name: 'Quantum Pulse',
    motto: 'Beyond the Sublight Limit',
    lore: 'Pioneering physicists and energy technologists who harness zero-point dark matter reactors. Their vessels accelerate with startling instantaneous torque and maintain sustained phase shielding.',
    color: '#d000ff',
    icon: 'Zap',
    bonusText: '+25% Nitro Acceleration & Overcharged Phase Shields',
    championPilot: 'Dr. Lyra Chronos',
  },
  solar_phalanx: {
    id: 'solar_phalanx',
    name: 'Solar Phalanx',
    motto: 'Forged in Pulsar Fire',
    lore: 'The elite galactic racing armada hailing from the inner solar megastructures. They field majestic golden cruisers engineered for maximum straight-line hyper-velocity and solar flare resilience.',
    color: '#ffaa00',
    icon: 'Sun',
    bonusText: '+30 km/h Peak Top Speed & Solar Boost Recharging',
    championPilot: 'Grand Marshall Vaelen',
  },
};

export const STORY_CAMPAIGN_MISSIONS: StoryMission[] = [
  {
    id: 'chapter_1_proving_grounds',
    chapter: 1,
    title: 'Orbital Proving Grounds',
    location: 'Neon Orbit — Sector 01',
    trackId: 'neon_orbit',
    mode: 'GRAND_PRIX',
    targetLaps: 2,
    rivalPilot: 'Ensign Drake (Apex Syndicate)',
    rivalFaction: 'apex_syndicate',
    briefing:
      'In the year 3099, the Void Core awakens. The qualifying gauntlet begins above the ringed gas giant of Neon Orbit. Outrace the aggressive Apex Syndicate scout craft and prove your flight credentials.',
    objective: 'Finish 1st or 2nd to earn your Subspace Racing License.',
    rewardCredits: 1200,
    rewardXP: 800,
    unlocked: true,
    completed: false,
  },
  {
    id: 'chapter_2_asteroid_ambush',
    chapter: 2,
    title: 'Asteroid Belt Gauntlet',
    location: 'Asteroid Run — Iron Mining Belt',
    trackId: 'asteroid_run',
    mode: 'SURVIVAL',
    targetLaps: 2,
    rivalPilot: 'Jax "Vector" Vance (Void Vanguard)',
    rivalFaction: 'void_vanguard',
    briefing:
      'The mining corridor is tearing apart from gravitational tidal forces. Dense asteroid swarms and electrified laser security pylons block your flight path. Dodge the hazards and outlast the Vanguard Ace.',
    objective: 'Survive the hazardous belt and cross the finish line with at least 35% hull integrity.',
    rewardCredits: 1800,
    rewardXP: 1200,
    unlocked: false,
    completed: false,
  },
  {
    id: 'chapter_3_rift_singularity',
    chapter: 3,
    title: 'Subspace Singularity Duel',
    location: 'Void Rift — Dimensional Horizon',
    trackId: 'void_rift',
    mode: 'DUEL',
    targetLaps: 3,
    rivalPilot: 'Dr. Lyra Chronos (Quantum Pulse)',
    rivalFaction: 'quantum_pulse',
    briefing:
      'Space-time fractures along the event horizon of the Void Rift. Dr. Lyra Chronos activates her temporal warp drive. Match her speed through the wormhole gateways in a high-stakes 1v1 duel.',
    objective: 'Defeat Dr. Lyra in head-to-head combat across the dimensional rift.',
    rewardCredits: 2500,
    rewardXP: 1800,
    unlocked: false,
    completed: false,
  },
  {
    id: 'chapter_4_void_core_ascendant',
    chapter: 4,
    title: 'The Void Core Horizon',
    location: 'Cosmic Ring — Pulsar Spire',
    trackId: 'cosmic_ring',
    mode: 'ELIMINATION',
    targetLaps: 3,
    rivalPilot: 'Grand Marshall Vaelen (Solar Phalanx)',
    rivalFaction: 'solar_phalanx',
    briefing:
      'The final convergence. At the center of the Pulsar Spire lies the ancient Void Core. Grand Marshall Vaelen and the galaxy’s ultimate champions assemble. Every 25 seconds, the lowest racer is vaporized by coronal discharge.',
    objective: 'Survive all elimination waves and claim the legendary Void Core Trophy.',
    rewardCredits: 5000,
    rewardXP: 3500,
    unlocked: false,
    completed: false,
  },
];
