import { ModeEventDefinition } from './ModeEventTypes';

export const MODE_EVENT_CATALOG: Record<string, ModeEventDefinition[]> = {
  // =========================================================================
  // MODE 02 — NEON CIRCUIT
  // =========================================================================
  NEON_CIRCUIT: [
    {
      id: 'm02_ev1_neon_gate',
      modeId: 'NEON_CIRCUIT',
      name: 'Sequential Neon Gate Activation',
      subtitle: 'CYBER ARCS ONLINE',
      description: 'Sequential neon accelerator arches charge up along Sector 1 straight.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.08, 0.22] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 45, // +45 km/h surge
      warningText: 'APPROACHING NEON ACCELERATOR GATES // ALIGN CENTER',
      activeText: 'NEON GATES ACTIVE // VELOCITY SURGE ENGAGED',
      consequenceText: 'SURGE CAPTURED (+45 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'BOOST',
      themeColor: '#00f0ff',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm02_ev2_lane_closure',
      modeId: 'NEON_CIRCUIT',
      name: 'Temporary Lane Closure',
      subtitle: 'TRAFFIC REDIRECT',
      description: 'Digital holographic pylons block the left lane due to maintenance.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.38, 0.52] },
      warningDurationSec: 2.5,
      activeDurationSec: 8.0,
      consequenceDurationSec: 2.0,
      consequenceType: 'LANE_CLOSURE',
      consequenceValue: 35, // impact slowdown
      warningText: 'MAINTENANCE HAZARD // LEFT LANE CLOSING // SHIFT RIGHT',
      activeText: 'LEFT LANE CLOSED // BARRIER FIELD ACTIVE',
      consequenceText: 'BARRIER CLIP DETECTED (-35 KM/H)',
      warningAudioKey: 'WARNING',
      activeAudioKey: 'IMPACT',
      themeColor: '#ff0055',
      safeLane: 'RIGHT',
      isRepeatable: true,
    },
    {
      id: 'm02_ev3_traffic_drone',
      modeId: 'NEON_CIRCUIT',
      name: 'Moving Traffic Drone Encounter',
      subtitle: 'CIVILIAN CONVOY',
      description: 'Automated municipal traffic drones cross high-speed expressway apex.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.58, 0.72] },
      warningDurationSec: 2.0,
      activeDurationSec: 7.0,
      consequenceDurationSec: 2.5,
      consequenceType: 'DRONE_INTERCEPT',
      consequenceValue: 25,
      warningText: 'AUTONOMOUS TRAFFIC DRONES ENTERING INTERSECTION',
      activeText: 'TRAFFIC DRONES IN SECTOR // THREAD THE GAP',
      consequenceText: 'DRONE TURBULENCE ENCOUNTERED',
      warningAudioKey: 'ALARM',
      activeAudioKey: 'IMPACT',
      themeColor: '#ffb703',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm02_ev4_timed_boost',
      modeId: 'NEON_CIRCUIT',
      name: 'Timed Boost-Gate Challenge',
      subtitle: 'SPEED TRAP CHALLENGE',
      description: 'High-speed speed trap gate evaluates entrance velocity.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.75, 0.88] },
      warningDurationSec: 2.0,
      activeDurationSec: 5.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 60,
      warningText: 'SPEED TRAP AHEAD // MAINTAIN >320 KM/H FOR NITRO REFILL',
      activeText: 'SPEED TRAP EVALUATION ACTIVE',
      consequenceText: 'THRESHOLD EXCEEDED! MAXIMUM NITRO RESTORED',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'SUCCESS',
      themeColor: '#10b981',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm02_ev5_final_lap',
      modeId: 'NEON_CIRCUIT',
      name: 'Final-Lap Lighting & Audio Escalation',
      subtitle: 'APEX SHOWDOWN',
      description: 'Final lap triggers full stadium searchlights, sirens, and maximum engine headroom.',
      trigger: { type: 'LAP_REACHED', lap: 2 },
      warningDurationSec: 1.5,
      activeDurationSec: 30.0,
      consequenceDurationSec: 15.0,
      consequenceType: 'LIGHTING_ESCALATION',
      consequenceValue: 20, // +20 km/h top speed boost
      warningText: 'FINAL LAP // CITY ESCALATION PROTOCOL ACTIVE',
      activeText: 'MAXIMUM ENGINE HEADROOM UNLOCKED // GO FOR PODIUM',
      consequenceText: 'OVERDRIVE ACTIVE',
      warningAudioKey: 'ALARM',
      activeAudioKey: 'BOOST',
      themeColor: '#a855f7',
      isRepeatable: false,
    },
  ],

  // =========================================================================
  // MODE 03 — ASTEROID RUN
  // =========================================================================
  ASTEROID_RUN: [
    {
      id: 'm03_ev1_cluster_approach',
      modeId: 'ASTEROID_RUN',
      name: 'Asteroid Cluster Approaches',
      subtitle: 'DENSE FIELD WARNING',
      description: 'Long-range radar detects incoming swarm of tumbling iron asteroids.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.12, 0.28] },
      warningDurationSec: 3.0,
      activeDurationSec: 8.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'DEBRIS_SWARM',
      consequenceValue: 30, // damage & slowdown
      warningText: 'LONG RANGE RADAR: HEAVY ASTEROID CLUSTER AHEAD',
      activeText: 'SWARM CONTACT // FIRE DESTRUCTION BEAM OR EVADE',
      consequenceText: 'ASTEROID IMPACT // INTEGRITY REDUCED',
      warningAudioKey: 'WARNING',
      activeAudioKey: 'IMPACT',
      themeColor: '#f97316',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm03_ev2_rotating_asteroid',
      modeId: 'ASTEROID_RUN',
      name: 'Large Asteroid Rotates into Route',
      subtitle: 'MEGALITH INTERCEPT',
      description: 'A 50-meter iron megalith rotates into the racing line.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.35, 0.50] },
      warningDurationSec: 2.8,
      activeDurationSec: 7.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_PENALTY',
      consequenceValue: 40,
      warningText: 'ROTATING MEGALITH BLOCKING FLIGHT LINE // DIVE LEFT',
      activeText: 'MEGALITH CLEARANCE CRITICAL // CLOSE FLY-BY',
      consequenceText: 'SURFACE GRAZE (-40 KM/H)',
      warningAudioKey: 'ALARM',
      activeAudioKey: 'IMPACT',
      themeColor: '#ef4444',
      safeLane: 'LEFT',
      isRepeatable: true,
    },
    {
      id: 'm03_ev3_collision_break',
      modeId: 'ASTEROID_RUN',
      name: 'Asteroid Fragmentation Event',
      subtitle: 'KINETIC SHATTER',
      description: 'Mining explosives detonate a boulder into tumbling fragments.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.52, 0.68] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 2.5,
      consequenceType: 'DEBRIS_SWARM',
      consequenceValue: 20,
      warningText: 'MINING DETONATION DETECTED // FRAGMENTATION IMMINENT',
      activeText: 'BOULDER SHATTERED // NAVIGATE DEBRIS GAP',
      consequenceText: 'FRAGMENT HIT',
      warningAudioKey: 'EXPLOSION',
      activeAudioKey: 'IMPACT',
      themeColor: '#eab308',
      safeLane: 'RIGHT',
      isRepeatable: true,
    },
    {
      id: 'm03_ev4_debris_stream',
      modeId: 'ASTEROID_RUN',
      name: 'Debris Stream Crosses Corridor',
      subtitle: 'CROSS-STREAM CURRENT',
      description: 'High-velocity micrometeorite stream sweeps laterally across the trench.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.70, 0.84] },
      warningDurationSec: 2.5,
      activeDurationSec: 7.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_PENALTY',
      consequenceValue: 30,
      warningText: 'MICROMETEORITE SPRAY CROSSING CORRIDOR // SHIELD ARMED',
      activeText: 'SPRAY ACTIVE // DRIFT AGAINST VECTOR',
      consequenceText: 'KINETIC DRAG INCURRED',
      warningAudioKey: 'WARNING',
      activeAudioKey: 'IMPACT',
      themeColor: '#f59e0b',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm03_ev5_narrow_passage',
      modeId: 'ASTEROID_RUN',
      name: 'Mining Extraction Gate Blast',
      subtitle: 'HOLLOW CORE SHORTCUT',
      description: 'Mining refinery blast clears hollow cavern shortcut.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.86, 0.98] },
      warningDurationSec: 2.0,
      activeDurationSec: 8.0,
      consequenceDurationSec: 4.0,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 50,
      warningText: 'BLAST CLEARANCE CONFIRMED // EXTRACTION SHAFT OPEN',
      activeText: 'HOLLOW MINING TUNNEL OPEN // FULL ACCELERATION',
      consequenceText: 'SUPERSONIC CAVERN PASS (+50 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'SUCCESS',
      themeColor: '#10b981',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
  ],

  // =========================================================================
  // MODE 04 — WORMHOLE EXPRESS
  // =========================================================================
  WORMHOLE_EXPRESS: [
    {
      id: 'm04_ev1_entrance_activate',
      modeId: 'WORMHOLE_EXPRESS',
      name: 'Wormhole Entrance Activates',
      subtitle: 'EVENT HORIZON IGNITION',
      description: 'Primary Einstein-Rosen spatial aperture spins up to stable frequency.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.06, 0.20] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'PORTAL_TRANSITION',
      consequenceValue: 50,
      warningText: 'SUBSPACE APERTURE CHARGING // MAINTAIN VECTOR',
      activeText: 'WARP INVERSION ENGAGED // VELOCITY x1.4',
      consequenceText: 'WARP ENTRY SUCCESSFUL',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'PORTAL',
      themeColor: '#8b5cf6',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm04_ev2_portal_stabilize',
      modeId: 'WORMHOLE_EXPRESS',
      name: 'Portal Stabilization Begins',
      subtitle: 'TENSOR FIELD LOCK',
      description: 'Internal conduit stabilization rings align flight trajectory.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.25, 0.40] },
      warningDurationSec: 2.0,
      activeDurationSec: 7.0,
      consequenceDurationSec: 2.5,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 40,
      warningText: 'STABILIZATION RINGS SYNCHRONIZING // ALIGN CENTER',
      activeText: 'SUBSPACE COMPRESSION LOCKED // THRUST MULTIPLIED',
      consequenceText: 'SLIPSTREAM CAPTURED (+40 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'BOOST',
      themeColor: '#06b6d4',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm04_ev3_tunnel_flux',
      modeId: 'WORMHOLE_EXPRESS',
      name: 'Conduit Chromatic Flux',
      subtitle: 'RELATIVISTIC DILATION',
      description: 'Spatial shear shifts conduit lighting and geometry into chromatic spectrum.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.45, 0.60] },
      warningDurationSec: 2.5,
      activeDurationSec: 8.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'ZERO_G_FLUX',
      consequenceValue: 20,
      warningText: 'CHROMATIC FLUX DETECTED // STEERING DILATION ACTIVE',
      activeText: 'SPATIAL DISTORTION // COUNTER-STEER THROUGH EDDIES',
      consequenceText: 'STABILIZED THROUGH SHEAR',
      warningAudioKey: 'WARNING',
      activeAudioKey: 'PORTAL',
      themeColor: '#ec4899',
      isRepeatable: true,
    },
    {
      id: 'm04_ev4_alternate_portal',
      modeId: 'WORMHOLE_EXPRESS',
      name: 'Temporary Alternate Portal Opens',
      subtitle: 'SUBSPACE SPLIT',
      description: 'High-speed auxiliary bypass portal pulses into existence on the right.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.65, 0.80] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 4.0,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 70,
      warningText: 'AUXILIARY WARP APERTURE DETECTED // RIGHT VECTOR',
      activeText: 'BYPASS PORTAL OPEN // SUPERLUMINAL SHORTCUT ACTIVE',
      consequenceText: 'BYPASS TRAVERSED (+70 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'SUCCESS',
      themeColor: '#10b981',
      safeLane: 'RIGHT',
      isRepeatable: true,
    },
    {
      id: 'm04_ev5_unstable_passage',
      modeId: 'WORMHOLE_EXPRESS',
      name: 'Unstable Passage Closes',
      subtitle: 'APERTURE COLLAPSE',
      description: 'Subspace exit aperture begins countdown to collapse; pilots must accelerate.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.82, 0.98] },
      warningDurationSec: 3.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_PENALTY',
      consequenceValue: 45,
      warningText: 'CONDUIT COLLAPSE IMMINENT // MAXIMUM BURN TO EXIT',
      activeText: 'EXIT APERTURE DESTABILIZING // THRESHOLD CLOSING',
      consequenceText: 'SHOCKWAVE EXPULSION',
      warningAudioKey: 'ALARM',
      activeAudioKey: 'PORTAL',
      themeColor: '#f43f5e',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
  ],

  // =========================================================================
  // MODE 05 — SOLAR STORM
  // =========================================================================
  SOLAR_STORM: [
    {
      id: 'm05_ev1_flare_warning',
      modeId: 'SOLAR_STORM',
      name: 'Solar Flare Warning',
      subtitle: 'CLASS-X ERUPTION ALERT',
      description: 'Helios orbital observatory detects massive coronal magnetic twist.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.10, 0.25] },
      warningDurationSec: 3.5,
      activeDurationSec: 8.0,
      consequenceDurationSec: 4.0,
      consequenceType: 'HEAT_INCREASE',
      consequenceValue: 25, // +25% heat
      warningText: 'SOLAR OBSERVATORY: CLASS-X CORONAL FLARE FORMING',
      activeText: 'CORONAL MASS EJECTION IN PROGRESS // SEEK SHIELDING',
      consequenceText: 'THERMAL RADIATION RISING (+25% HEAT)',
      warningAudioKey: 'ALARM',
      activeAudioKey: 'IMPACT',
      themeColor: '#ff6b35',
      safeLane: 'SHELTER',
      isRepeatable: true,
    },
    {
      id: 'm05_ev2_flare_buildup',
      modeId: 'SOLAR_STORM',
      name: 'Flare Buildup and Eruption',
      subtitle: 'PLASMA PROMINENCE',
      description: 'Blazing arch of superheated plasma leaps across outer racing line.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.30, 0.48] },
      warningDurationSec: 3.0,
      activeDurationSec: 7.0,
      consequenceDurationSec: 3.5,
      consequenceType: 'HEAT_INCREASE',
      consequenceValue: 35,
      warningText: 'PLASMA PROMINENCE CROSSING EXPOSED SECTOR',
      activeText: 'PLASMA WAVE ACTIVE // MAXIMUM HULL RADIATION',
      consequenceText: 'CRITICAL CORE HEATING',
      warningAudioKey: 'WARNING',
      activeAudioKey: 'EXPLOSION',
      themeColor: '#ef4444',
      safeLane: 'RIGHT',
      isRepeatable: true,
    },
    {
      id: 'm05_ev3_heat_zone',
      modeId: 'SOLAR_STORM',
      name: 'Heat Zone Activation',
      subtitle: 'SUPERHEATED PLATES',
      description: 'Unshielded titanium track plates absorb radiation, draining engine efficiency.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.52, 0.68] },
      warningDurationSec: 2.5,
      activeDurationSec: 8.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_PENALTY',
      consequenceValue: 35,
      warningText: 'TRACK SURFACE OVERHEATING // ENGINE THROTTLE DAMPENED',
      activeText: 'SUPERHEATED ZONE // COOLING CONDUITS ENGAGED',
      consequenceText: 'THERMAL THROTTLE DAMPENING (-35 KM/H)',
      warningAudioKey: 'WARNING',
      activeAudioKey: 'IMPACT',
      themeColor: '#f97316',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm05_ev4_protective_structure',
      modeId: 'SOLAR_STORM',
      name: 'Protective Shield Arch Deployment',
      subtitle: 'MAGNETIC UMBRELLA',
      description: 'Station magnetic deflector arches deploy protective blue fields.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.70, 0.85] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 4.0,
      consequenceType: 'HEAT_DISSIPATE',
      consequenceValue: 50, // -50% heat
      warningText: 'DEFLECTOR ARCHES ONLINE AHEAD // SHIFT TO BLUE CORRIDOR',
      activeText: 'MAGNETIC SHIELD ACTIVE // RAPID THERMAL VENTING',
      consequenceText: 'SYSTEMS COOLED (-50% HEAT)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'SUCCESS',
      themeColor: '#38bdf8',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm05_ev5_safe_window',
      modeId: 'SOLAR_STORM',
      name: 'Safe-Window Opening and Closing',
      subtitle: 'SOLAR ECLIPSE SHADOW',
      description: 'Asteroid shadow creates temporary zero-exposure sprint straight.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.88, 0.98] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 40,
      warningText: 'THERMAL SHADOW WINDOW OPENING // FULL POWER BURST',
      activeText: 'SOLAR SHADOW CONDUIT // UNRESTRICTED BOOST',
      consequenceText: 'SAFE SPRINT COMPLETED (+40 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'BOOST',
      themeColor: '#10b981',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
  ],

  // =========================================================================
  // MODE 06 — GRAVITY FREE
  // =========================================================================
  GRAVITY_FREE: [
    {
      id: 'm06_ev1_zero_g_entry',
      modeId: 'GRAVITY_FREE',
      name: 'Entry into Zero-Gravity Zone',
      subtitle: 'TETHER DISENGAGED',
      description: 'Magnetic road clamps release; ship transitions into free-drift space flight.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.08, 0.22] },
      warningDurationSec: 2.0,
      activeDurationSec: 8.0,
      consequenceDurationSec: 4.0,
      consequenceType: 'ZERO_G_FLUX',
      consequenceValue: 30,
      warningText: 'CENTRIFUGE EXIT AHEAD // PREPARE FOR ZERO-G INERTIA',
      activeText: 'ZERO-GRAVITY ENGAGED // MOMENTUM VECTOR FLIGHT',
      consequenceText: 'FREE FLIGHT ACTIVE',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'PORTAL',
      themeColor: '#10b981',
      isRepeatable: true,
    },
    {
      id: 'm06_ev2_rotating_platform',
      modeId: 'GRAVITY_FREE',
      name: 'Rotating Platform Activation',
      subtitle: 'CENTRIFUGE STRUTS',
      description: 'Enormous orbital station spoke rotates through flight envelope.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.30, 0.46] },
      warningDurationSec: 2.5,
      activeDurationSec: 7.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_PENALTY',
      consequenceValue: 35,
      warningText: 'ROTATING STATION ARM CROSSING // TIME INVERSION ENTRY',
      activeText: 'STRUT ROTATION ACTIVE // THREAD DOCKING RING',
      consequenceText: 'STRUT TURBULENCE (-35 KM/H)',
      warningAudioKey: 'WARNING',
      activeAudioKey: 'IMPACT',
      themeColor: '#f59e0b',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm06_ev3_floating_debris',
      modeId: 'GRAVITY_FREE',
      name: 'Floating Debris Encounter',
      subtitle: 'CARGO DRIFT FIELD',
      description: 'Zero-G cargo modules float unmoored in docking bay void.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.52, 0.68] },
      warningDurationSec: 2.5,
      activeDurationSec: 7.5,
      consequenceDurationSec: 2.5,
      consequenceType: 'DRONE_INTERCEPT',
      consequenceValue: 25,
      warningText: 'UNANCHORED CARGO CONTAINERS DRIFTING IN SECTOR',
      activeText: 'CONTAINER SLALOM // 3D ORIENTATION REQUIRED',
      consequenceText: 'CONTAINER CLIP',
      warningAudioKey: 'ALARM',
      activeAudioKey: 'IMPACT',
      themeColor: '#eab308',
      safeLane: 'RIGHT',
      isRepeatable: true,
    },
    {
      id: 'm06_ev4_momentum_challenge',
      modeId: 'GRAVITY_FREE',
      name: 'Momentum Challenge Activation',
      subtitle: 'INERTIA VECTOR GATE',
      description: 'High-speed momentum gate tests ability to maintain velocity without braking.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.72, 0.86] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.5,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 55,
      warningText: 'MOMENTUM GATE AHEAD // DO NOT BRAKE // PRESERVE INERTIA',
      activeText: 'INERTIAL EVALUATION ACTIVE // HOLD APEX',
      consequenceText: 'PERFECT INERTIAL DIVE (+55 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'SUCCESS',
      themeColor: '#06b6d4',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm06_ev5_propulsion_challenge',
      modeId: 'GRAVITY_FREE',
      name: 'Station Reentry Docking Alignment',
      subtitle: 'CENTRIFUGE CAPTURE',
      description: 'Magnetic catchers align floating ship back to centrifuge racing deck.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.88, 0.98] },
      warningDurationSec: 1.8,
      activeDurationSec: 5.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 40,
      warningText: 'CENTRIFUGE DOCKING BEACON LOCKED // ALIGN FLIGHT ANGLE',
      activeText: 'MAGNETIC DECK CAPTURE SUCCESSFUL // FULL TRACTION',
      consequenceText: 'DECK TRACTION RESTORED (+40 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'BOOST',
      themeColor: '#10b981',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
  ],

  // =========================================================================
  // MODE 07 — PLASMA STORM
  // =========================================================================
  PLASMA_STORM: [
    {
      id: 'm07_ev1_energy_buildup',
      modeId: 'PLASMA_STORM',
      name: 'Ionic Charge Buildup',
      subtitle: 'STATIC DISCHARGE WARNING',
      description: 'Atmospheric capacitor coils hiss as electrical potential spikes.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.08, 0.24] },
      warningDurationSec: 3.0,
      activeDurationSec: 7.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'ELECTRICAL_DISCHARGE',
      consequenceValue: 30,
      warningText: 'IONIC STATIC SURGING // 3 SECONDS TO ARCOTRON DISCHARGE',
      activeText: 'LIGHTNING DISCHARGE ACROSS SECTOR // SHIFT TO SAFE LANE',
      consequenceText: 'IONIC HIT DETECTED (-30 KM/H)',
      warningAudioKey: 'ALARM',
      activeAudioKey: 'IMPACT',
      themeColor: '#00f0ff',
      safeLane: 'RIGHT',
      isRepeatable: true,
    },
    {
      id: 'm07_ev2_electrical_discharge',
      modeId: 'PLASMA_STORM',
      name: 'Electrical Lightning Strike',
      subtitle: 'HIGH-VOLTAGE BOLT',
      description: 'Multi-million volt plasma lightning bolt strikes conductive road.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.32, 0.48] },
      warningDurationSec: 2.5,
      activeDurationSec: 6.5,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_PENALTY',
      consequenceValue: 40,
      warningText: 'PRIMARY LIGHTNING CONDUIT FIRING // AVOID LEFT RAIL',
      activeText: 'HIGH-VOLTAGE ARC ACTIVE // ELECTRICAL INTERFERENCE',
      consequenceText: 'SYSTEM GLITCH (-40 KM/H)',
      warningAudioKey: 'WARNING',
      activeAudioKey: 'EXPLOSION',
      themeColor: '#38bdf8',
      safeLane: 'RIGHT',
      isRepeatable: true,
    },
    {
      id: 'm07_ev3_conductive_track',
      modeId: 'PLASMA_STORM',
      name: 'Conductive Grid Overload',
      subtitle: 'GROUND GRID SHORT',
      description: 'Conductive track plates ground millions of amperes of static.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.52, 0.68] },
      warningDurationSec: 2.5,
      activeDurationSec: 7.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_PENALTY',
      consequenceValue: 35,
      warningText: 'TRACK GRID OVERLOAD // GROUND SPARKS ACTIVE',
      activeText: 'SURFACE ELECTRIFIED // HOVER STABILITY TESTED',
      consequenceText: 'GROUND DRAG',
      warningAudioKey: 'WARNING',
      activeAudioKey: 'IMPACT',
      themeColor: '#818cf8',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm07_ev4_safe_lane',
      modeId: 'PLASMA_STORM',
      name: 'Insulated Safe-Lane Beacon',
      subtitle: 'GROUNDED CORRIDOR',
      description: 'Insulated ceramic beacons illuminate the safe navigation channel.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.72, 0.86] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.5,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 45,
      warningText: 'INSULATED BEACON ONLINE // RIDE CENTER CHANNEL',
      activeText: 'SAFE CHANNEL SECURED // ELECTROMAGNETIC TURBO SURGE',
      consequenceText: 'SURGE ENGAGED (+45 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'SUCCESS',
      themeColor: '#10b981',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm07_ev5_storm_intensity',
      modeId: 'PLASMA_STORM',
      name: 'Storm Intensity Escalation',
      subtitle: 'MAGNETAR PULSE',
      description: 'Advancing storm wall surges forward with heightened electromagnetic intensity.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.88, 0.98] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 50,
      warningText: 'MAGNETAR PULSE CLOSING // FULL EVASION BOOST',
      activeText: 'MAXIMUM SURGE DISCHARGE // OUTRUN THE FRONT',
      consequenceText: 'PULSE OUTRUN (+50 KM/H)',
      warningAudioKey: 'ALARM',
      activeAudioKey: 'BOOST',
      themeColor: '#c084fc',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
  ],

  // =========================================================================
  // MODE 08 — SKYLINE RUSH
  // =========================================================================
  SKYLINE_RUSH: [
    {
      id: 'm08_ev1_traffic_drone',
      modeId: 'SKYLINE_RUSH',
      name: 'Traffic Drone Enters Line',
      subtitle: 'METRO CONVOY DETOUR',
      description: 'Heavy municipal air haulers lumber into the elevated expressway route.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.10, 0.25] },
      warningDurationSec: 2.2,
      activeDurationSec: 7.0,
      consequenceDurationSec: 2.5,
      consequenceType: 'DRONE_INTERCEPT',
      consequenceValue: 30,
      warningText: 'CARGO HAULER ENTERING RACING LINE // OVERTAKE HIGH',
      activeText: 'CARGO HAULER IN SECTOR // THREAD THE ROOF GAP',
      consequenceText: 'HAULER SLIPSTREAM CLIP',
      warningAudioKey: 'ALARM',
      activeAudioKey: 'IMPACT',
      themeColor: '#f59e0b',
      safeLane: 'RIGHT',
      isRepeatable: true,
    },
    {
      id: 'm08_ev2_bridge_barrier',
      modeId: 'SKYLINE_RUSH',
      name: 'Bridge Barrier State Shift',
      subtitle: 'VARIABLE SKYWAY GATE',
      description: 'Holographic toll gates switch configuration, revealing speed corridor.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.30, 0.45] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 40,
      warningText: 'VARIABLE SKYWAY BARRIER SHIFTING // GREEN GATE OPEN',
      activeText: 'EXPRESS GATE CLEARED // FREEWAY SURGE',
      consequenceText: 'EXPRESS PASS (+40 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'SUCCESS',
      themeColor: '#10b981',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm08_ev3_rooftop_platform',
      modeId: 'SKYLINE_RUSH',
      name: 'Rooftop Platform Jump Sequence',
      subtitle: 'CHASM SKY-LEAP',
      description: 'High-speed launch ramp propels ship across 200m chasm between megatowers.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.50, 0.65] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.5,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 55,
      warningText: 'ROOFTOP CHASM JUMP AHEAD // MAINTAIN >300 KM/H',
      activeText: 'AIRBORNE CHASM FLIGHT // LOCK LANDING VECTOR',
      consequenceText: 'CLEAN CHASM LANDING (+55 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'BOOST',
      themeColor: '#ec4899',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm08_ev4_construction_block',
      modeId: 'SKYLINE_RUSH',
      name: 'Construction Crane Sweep',
      subtitle: 'CRANE OBSTACLE',
      description: 'Autonomous construction crane boom swings across upper roadway.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.68, 0.82] },
      warningDurationSec: 2.5,
      activeDurationSec: 7.0,
      consequenceDurationSec: 2.5,
      consequenceType: 'SPEED_PENALTY',
      consequenceValue: 35,
      warningText: 'CONSTRUCTION CRANE ACTIVE // CRANE ARM ON LEFT',
      activeText: 'CRANE SWING IN SECTOR // DIVE LOW RIGHT',
      consequenceText: 'OBSTACLE CONTACT (-35 KM/H)',
      warningAudioKey: 'WARNING',
      activeAudioKey: 'IMPACT',
      themeColor: '#ef4444',
      safeLane: 'RIGHT',
      isRepeatable: true,
    },
    {
      id: 'm08_ev5_elevated_shortcut',
      modeId: 'SKYLINE_RUSH',
      name: 'Temporary Elevated Bypass Opens',
      subtitle: 'EXPRESS FLYOVER',
      description: 'Hydraulic skyway platform aligns, opening narrow spire bypass.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.85, 0.98] },
      warningDurationSec: 1.8,
      activeDurationSec: 6.0,
      consequenceDurationSec: 4.0,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 60,
      warningText: 'SPIRE BYPASS DEPLOYED // LEFT RAMP ACCESS OPEN',
      activeText: 'SPIRE SHORTCUT TRAVERSED // SPRINT TO FINISH',
      consequenceText: 'PODIUM SPRINT (+60 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'SUCCESS',
      themeColor: '#00f0ff',
      safeLane: 'LEFT',
      isRepeatable: true,
    },
  ],

  // =========================================================================
  // MODE 09 — DEBRIS SURVIVAL
  // =========================================================================
  DEBRIS_SURVIVAL: [
    {
      id: 'm09_ev1_debris_wave',
      modeId: 'DEBRIS_SURVIVAL',
      name: 'Debris Wave Approaches',
      subtitle: 'DERELICT EXPULSION',
      description: 'Exploding carrier reactor ejects expanding debris ring across trajectory.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.10, 0.26] },
      warningDurationSec: 3.0,
      activeDurationSec: 8.0,
      consequenceDurationSec: 3.5,
      consequenceType: 'DEBRIS_SWARM',
      consequenceValue: 35,
      warningText: 'RADAR WARNING: MASSIVE DEBRIS WAVE APPROACHING',
      activeText: 'DEBRIS WAVE CONTACT // EVADE FLYING WRECKAGE',
      consequenceText: 'WRECKAGE IMPACT',
      warningAudioKey: 'ALARM',
      activeAudioKey: 'IMPACT',
      themeColor: '#f97316',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm09_ev2_structural_detach',
      modeId: 'DEBRIS_SURVIVAL',
      name: 'Structural Component Detaches',
      subtitle: 'STATION COLLAPSE',
      description: 'A 40-meter solar array truss snaps free from station superstructure.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.32, 0.48] },
      warningDurationSec: 2.5,
      activeDurationSec: 7.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'SPEED_PENALTY',
      consequenceValue: 40,
      warningText: 'SOLAR TRUSS SHEARING // TOPPING ACROSS FLIGHT LINE',
      activeText: 'FALLING TRUSS IN SECTOR // FLY UNDER BEAM',
      consequenceText: 'STRUCTURAL IMPACT (-40 KM/H)',
      warningAudioKey: 'EXPLOSION',
      activeAudioKey: 'IMPACT',
      themeColor: '#ef4444',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm09_ev3_wreckage_cross',
      modeId: 'DEBRIS_SURVIVAL',
      name: 'Wreckage Crosses Track',
      subtitle: 'TUMBLING HULL SECTOR',
      description: 'Tumbling hull section spins across track like a rotating shield.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.52, 0.68] },
      warningDurationSec: 2.5,
      activeDurationSec: 7.5,
      consequenceDurationSec: 3.0,
      consequenceType: 'DEBRIS_SWARM',
      consequenceValue: 30,
      warningText: 'TUMBLING HULL PLATE CROSSING TRACK // HOLD RIGHT',
      activeText: 'HULL ROTATING THROUGH APEX // TIMED PASS REQUIRED',
      consequenceText: 'HULL GRAZE',
      warningAudioKey: 'WARNING',
      activeAudioKey: 'IMPACT',
      themeColor: '#eab308',
      safeLane: 'RIGHT',
      isRepeatable: true,
    },
    {
      id: 'm09_ev4_safe_passage',
      modeId: 'DEBRIS_SURVIVAL',
      name: 'Safe Passage Opens',
      subtitle: 'CLEAR RECOVERY WINDOW',
      description: 'Debris field parts momentarily, opening high-speed salvage window.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.72, 0.86] },
      warningDurationSec: 2.0,
      activeDurationSec: 6.0,
      consequenceDurationSec: 4.0,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 50,
      warningText: 'CLEAR CORRIDOR LOCATED // ACCELERATE INTO GAP',
      activeText: 'WRECKAGE CLEARED // FULL THRUST RECOVERY',
      consequenceText: 'SAFE CORRIDOR CLEARED (+50 KM/H)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'SUCCESS',
      themeColor: '#10b981',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm09_ev5_damaged_corridor',
      modeId: 'DEBRIS_SURVIVAL',
      name: 'Damaged Corridor Impassable',
      subtitle: 'BLAST DOOR EMERGENCY',
      description: 'Decompression hazard triggers emergency blast door on main route.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.88, 0.98] },
      warningDurationSec: 2.5,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'LANE_CLOSURE',
      consequenceValue: 35,
      warningText: 'HANGAR BREACH // MAIN CORRIDOR CLOSING // TAKE BYPASS',
      activeText: 'BLAST DOOR SEALED // DETOUR COMPLETE',
      consequenceText: 'DETOUR CLEARED',
      warningAudioKey: 'ALARM',
      activeAudioKey: 'IMPACT',
      themeColor: '#f43f5e',
      safeLane: 'LEFT',
      isRepeatable: true,
    },
  ],

  // =========================================================================
  // MODE 10 — QUANTUM TIME TRIAL
  // =========================================================================
  QUANTUM_TIME_TRIAL: [
    {
      id: 'm10_ev1_trial_start',
      modeId: 'QUANTUM_TIME_TRIAL',
      name: 'Chrono Time-Trial Start',
      subtitle: 'TELEMETRY CLOCK ACTIVE',
      description: 'Chrono telemetry locks in, establishing gold (45s), silver (52s), and bronze (60s) targets.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.02, 0.15] },
      warningDurationSec: 1.5,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'TIME_SPLIT_EVALUATION',
      consequenceValue: 0,
      warningText: 'CHRONO RUN COMMENCED // TARGET: GOLD <45.000s',
      activeText: 'TIMING GATES ONLINE // PASS THROUGH EMERALD SENSORS',
      consequenceText: 'CHRONO CALIBRATED',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'SUCCESS',
      themeColor: '#00f0ff',
      safeLane: 'CENTER',
      isRepeatable: false,
    },
    {
      id: 'm10_ev2_split_eval_1',
      modeId: 'QUANTUM_TIME_TRIAL',
      name: 'Sector 1 Split-Time Evaluation',
      subtitle: 'SPLIT DELTA CHECK',
      description: 'First split evaluation comparing current pace against Gold pace.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.30, 0.42] },
      warningDurationSec: 2.0,
      activeDurationSec: 5.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'TIME_SPLIT_EVALUATION',
      consequenceValue: -500, // -0.5s bonus for clean split
      warningText: 'SECTOR 1 SPLIT BEACON AHEAD',
      activeText: 'SPLIT EVALUATION: PACE OPTIMAL (-0.482s)',
      consequenceText: 'SPLIT DELTA: GREEN',
      warningAudioKey: 'CHECKPOINT',
      activeAudioKey: 'SUCCESS',
      themeColor: '#10b981',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm10_ev3_precision_gate',
      modeId: 'QUANTUM_TIME_TRIAL',
      name: 'Precision Gate Activation',
      subtitle: 'TIME-BONUS CHRONO SLIT',
      description: 'Narrow holographic ring awards -1.0s time bonus on clean pass without wall clipping.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.50, 0.62] },
      warningDurationSec: 2.0,
      activeDurationSec: 5.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'TIME_BONUS',
      consequenceValue: -1000, // -1.0s bonus
      warningText: 'CHRONO BONUS SLIT AHEAD // CENTER THREAD AWARDS -1.0s',
      activeText: 'PRECISION SLIT ACTIVE // THREAD THE NEEDLE',
      consequenceText: 'BONUS CLAIMED! (-1.000s TIME DEDUCTION)',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'BOOST',
      themeColor: '#a855f7',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm10_ev4_split_eval_2',
      modeId: 'QUANTUM_TIME_TRIAL',
      name: 'Sector 2 Split-Time Evaluation',
      subtitle: 'CHRONO DELTA 2',
      description: 'Second split evaluation comparing sector 2 time with target.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.68, 0.80] },
      warningDurationSec: 2.0,
      activeDurationSec: 5.0,
      consequenceDurationSec: 3.0,
      consequenceType: 'TIME_SPLIT_EVALUATION',
      consequenceValue: -500,
      warningText: 'SECTOR 2 SPLIT BEACON AHEAD',
      activeText: 'SPLIT EVALUATION: ON TRACK FOR GOLD (-1.120s)',
      consequenceText: 'SPLIT DELTA: GREEN',
      warningAudioKey: 'CHECKPOINT',
      activeAudioKey: 'SUCCESS',
      themeColor: '#10b981',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
    {
      id: 'm10_ev5_bonus_route',
      modeId: 'QUANTUM_TIME_TRIAL',
      name: 'Final Sector Climax Challenge',
      subtitle: 'SPRINT TO FINISH',
      description: 'Final sector sprint with high-difficulty apex line awarding final time reduction.',
      trigger: { type: 'SPLINE_PROGRESS', splineWindow: [0.85, 0.98] },
      warningDurationSec: 1.8,
      activeDurationSec: 6.0,
      consequenceDurationSec: 3.5,
      consequenceType: 'SPEED_BOOST',
      consequenceValue: 50,
      warningText: 'FINAL CHRONO SPRINT // OVERDRIVE BOOST ENGAGED',
      activeText: 'FINISH BEACON IN SIGHT // STAMP THE RECORD',
      consequenceText: 'VALID ATTEMPT RECORDED',
      warningAudioKey: 'ENERGY_CHARGE',
      activeAudioKey: 'SUCCESS',
      themeColor: '#00f0ff',
      safeLane: 'CENTER',
      isRepeatable: true,
    },
  ],
};
