const fs = require('fs');
const path = require('path');

const RAW_EVENTS_DATA = [
  // Part 1 — Awakening & Initial Collapse (1–33)
  { index: 1, time: "30:00", name: "Singularity Activation", id: "singularity_activation",
    subtitle: "The central dark singularity awakens; initial tidal metric perturbations propagate through space.",
    cause: "Initial black hole event horizon stabilization and core gravitational emergence.",
    physicalEffect: "Orbital vectors curve gently toward the singularity; asteroid trajectories bend.",
    env: "Accretion photon ring flickers into existence; space starts subtly curving around the black hole.",
    player: "Mild helm drift; subtle lateral gravitational pull toward the core." },

  { index: 2, time: "29:42", name: "Starlight Bending", id: "starlight_bending",
    subtitle: "Distant stellar rays warp into curved arcs as gravitational lensing takes hold.",
    cause: "Relativistic light deflection across the expanding Schwarzschild radius.",
    physicalEffect: "Optical caustics bend background celestial constellations around the core.",
    env: "Distant stars stretch into glowing blue-shifted arcs and Einstein rings.",
    player: "Navigation waypoints visibly shift as spacetime geometry distorts visual alignment." },

  { index: 3, time: "29:24", name: "Orbital Drift", id: "orbital_drift",
    subtitle: "Orbital objects lose station-keeping equilibrium and begin decaying inward.",
    cause: "Tidal forces overcome orbital attitude thrusters across the sector.",
    physicalEffect: "Unanchored satellites and small debris shift from stable Keplerian orbits.",
    env: "Outer dust lanes begin spiraling inward toward the accretion boundary.",
    player: "Periodic crosswinds of micro-gravity nudge the ship laterally." },

  { index: 4, time: "29:06", name: "Photon Ring Ignition", id: "photon_ring_ignition",
    subtitle: "A white-hot, razor-sharp photon ring ignites around the dark event horizon.",
    cause: "Photons orbiting at the photon sphere threshold build up extreme radiant energy density.",
    physicalEffect: "Blinding optical boundary flares around the central void singularity.",
    env: "Intense high-energy white-cyan ring illuminates surrounding dust clouds.",
    player: "Forward visor dynamic polarization activates to filter intense photon glare." },

  { index: 5, time: "28:48", name: "Gravity Pulse", id: "gravity_pulse",
    subtitle: "First rhythmic gravitational pulse ripples through surrounding space.",
    cause: "Mass influx fluctuation across the inner accretion boundary.",
    physicalEffect: "Longitudinal gravitational waves transmit physical compression waves through space.",
    env: "Space ripples with translucent wave fronts; particles shudder in synchronized cadence.",
    player: "Vibration felt through ship chassis; momentary drop in steering responsiveness." },

  { index: 6, time: "28:30", name: "Skybridge Distortion", id: "skybridge_distortion",
    subtitle: "Distant orbital transit skybridges visibly bow under differential tidal stress.",
    cause: "Differential gravitational acceleration across extended megastructure spans.",
    physicalEffect: "Support trusses on outer skybridge corridors bend toward the gravity well.",
    env: "Luminous neon rails on distant bridges warp into serpentine s-curves.",
    player: "Visual landmarks begin showing physical misalignment." },

  { index: 7, time: "28:12", name: "Moon Orbit Shift", id: "moon_orbit_shift",
    subtitle: "The sector's companion moon is pulled from its ancient elliptical trajectory.",
    cause: "Growing gravitational sphere of influence encompasses the lunar body.",
    physicalEffect: "Moon's orbital velocity increases; periapsis drops toward the singularity.",
    env: "The distant moon tilts noticeably; loose surface regolith lifts into orbit.",
    player: "Noticeable gravitational tide pulling toward the left horizon." },

  { index: 8, time: "27:54", name: "Asteroid Capture", id: "asteroid_capture",
    subtitle: "Dozens of high-density asteroids are captured into accelerating inward spirals.",
    cause: "Three-body gravitational capture by the singularity and companion bodies.",
    physicalEffect: "Asteroids plunge into elliptical spiral tracks across the racing arena.",
    env: "Glowing molten veins crack open on tumbling asteroids from tidal heating.",
    player: "Near-field hazard: tumbling asteroids cross upper airspace." },

  { index: 9, time: "27:36", name: "Space Elevator Sway", id: "space_elevator_sway",
    subtitle: "Colossal tethered orbital elevators oscillate with harmonic tidal resonance.",
    cause: "Gravitational harmonic excitation along carbon-nanotube elevator tethers.",
    physicalEffect: "Thousands of kilometers of elevator cable undulate with massive standing waves.",
    env: "Warning beacons flash along the swaying elevator tower spine.",
    player: "Sensors pick up intense structural tension harmonics in the upper atmosphere." },

  { index: 10, time: "27:18", name: "Nebula Lensing", id: "nebula_lensing",
    subtitle: "Vast purple and indigo cosmic nebula clouds are magnified and warped into rings.",
    cause: "Gravitational microlensing of distant cosmic emission clouds.",
    physicalEffect: "Nebula gas envelopes stretch into dramatic swirling arcs around the void.",
    env: "Sky transitions into a dramatic dual-palette cosmic storm of indigo and amber.",
    player: "Dramatic atmospheric color shift in ambient cockpit lighting." },

  { index: 11, time: "27:00", name: "Orbital Ring Vibration", id: "orbital_ring_vibration",
    subtitle: "The planetary megastructure orbital ring begins to hum with structural vibration.",
    cause: "Tidal forces induce mechanical resonance through the ring's magnetic joints.",
    physicalEffect: "Superconducting magnetic levitation tracks buckle with high-frequency tremors.",
    env: "Electric arcs crackle across the ring's illuminated maintenance towers.",
    player: "Low-frequency rumble vibrates through the racing highway surface." },

  { index: 12, time: "26:42", name: "City Power Surge", id: "city_power_surge",
    subtitle: "Orbital city platforms experience massive electromagnetic induction power surges.",
    cause: "Rapidly shifting magnetic field lines cut through city power transmission grids.",
    physicalEffect: "High-voltage grids overload; luminous grid arrays flicker and pulse violently.",
    env: "City skyline blinks through chaotic cascading power flickers and blue transformer flashes.",
    player: "Electromagnetic interference momentarily glitches ship digital HUD readouts." },

  { index: 13, time: "26:24", name: "Plasma Current Reversal", id: "plasma_current_reversal",
    subtitle: "Accretion plasma streams reverse direction as magnetohydrodynamic forces flip.",
    cause: "Severe twisting of magnetic flux tubes anchored to the spinning ergosphere.",
    physicalEffect: "Relativistic plasma reverses trajectory, colliding with outward gas flows.",
    env: "Explosive magenta and orange plasma shockwaves erupt in the middle accretion disk.",
    player: "Cockpit radiation warning chimes; thermal shield load spikes." },

  { index: 14, time: "26:06", name: "Station Orbit Failure", id: "station_orbit_failure",
    subtitle: "Orbital station thrusters exhaust fuel; station begins uncontrolled orbital decay.",
    cause: "Exhaustion of station-keeping propellant against relentless gravitational drag.",
    physicalEffect: "The colossal orbital station loses circularity and dips toward the accretion plane.",
    env: "Station rotating habitat section wobbles out of its gyroscopic balance plane.",
    player: "Station silhouette descends lower on the horizon, glowing with friction." },

  { index: 15, time: "25:48", name: "Gravity Shadow", id: "gravity_shadow",
    subtitle: "Spacetime curvature creates acute gravitational blind spots and shear zones.",
    cause: "Frame-dragging creates localized zones of extreme gravitational deflection.",
    physicalEffect: "Abrupt boundary between low-gravity pockets and crushing gravitational wells.",
    env: "Space appears visually sheared along sharp refraction boundaries.",
    player: "Sudden acceleration and deceleration jolts as ship crosses shear boundaries." },

  { index: 16, time: "25:30", name: "First Structural Fracture", id: "first_structural_fracture",
    subtitle: "Distant orbital highway bridge snaps with a catastrophic release of mechanical tension.",
    cause: "Tensile stress exceeds carbon-composite yield strength by over 140%.",
    physicalEffect: "A major 800-meter bridge span splits in two, flinging structural girders into space.",
    env: "Explosion of glowing debris and severed superconductor cables glowing orange.",
    player: "Audible cosmic thunder crack reverberates through surrounding medium." },

  { index: 17, time: "25:12", name: "Tower Lean", id: "tower_lean",
    subtitle: "The primary communications and energy transmission tower bends perceptibly toward the void.",
    cause: "Unbalanced tidal gradient pulling the tower's upper spire faster than its base.",
    physicalEffect: "The 2-kilometer tower develops an alarming 18-degree permanent lean.",
    env: "Tower exterior illumination panels pop sequentially as structural seams warp.",
    player: "Visual landmark tilt provides undeniable evidence of gravitational escalation." },

  { index: 18, time: "24:54", name: "Debris Stream Formation", id: "debris_stream_formation",
    subtitle: "Pulverized asteroids and structural fragments coalesce into dense spiraling debris ribbons.",
    cause: "Gravitational focusing funnels scattered matter into coherent orbital streams.",
    physicalEffect: "Millions of fragments organize into high-velocity spiraling tracer filaments.",
    env: "Luminous glowing ribbons spiral around the black hole like incandescent highways.",
    player: "Particle streams lash across windshield; shield energy drains upon contact." },

  { index: 19, time: "24:36", name: "Orbital Traffic Chaos", id: "orbital_traffic_chaos",
    subtitle: "Automated cargo freighters and drones lose navigational lock, scrambling routes.",
    cause: "Navigation beacons desynchronize due to gravitational time dilation shifts.",
    physicalEffect: "Hundreds of autonomous cargo vessels disperse into erratic evasive maneuvers.",
    env: "Streaks of emergency engine burns crisscross the upper skybox.",
    player: "Distress beacons flood communication channels." },

  { index: 20, time: "24:18", name: "Gravity Wave Front", id: "gravity_wave_front",
    subtitle: "A visible gravitational shockwave expands outward from the ergosphere boundary.",
    cause: "Coalescence of high-density core matter within the event horizon.",
    physicalEffect: "Spacetime compression wave propagates at lightspeed, distorting space metrics.",
    env: "Circular shockwave disc ripples outward, distorting stars and clouds in its wake.",
    player: "Major ship tremor; controls stiffen as gravitational wave sweeps across hull." },

  { index: 21, time: "24:00", name: "Planetary Lensing", id: "planetary_lensing",
    subtitle: "The sapphire terrestrial planet passes behind the lensing zone and is visually duplicated.",
    cause: "Extreme gravitational light deflection creates secondary Einstein images.",
    physicalEffect: "Twin curved mirages of the planet appear on opposite sides of the singularity.",
    env: "Massive blue planet appears to wrap around the central black hole in glowing crescent arcs.",
    player: "Stunning, surreal visual spectacle across the entire forward field of view." },

  { index: 22, time: "23:42", name: "Space Dock Failure", id: "space_dock_failure",
    subtitle: "Primary orbital drydock mooring clamps shear off; massive docking bays drift loose.",
    cause: "Tidal forces overcome hydraulic magnetic docking locks.",
    physicalEffect: "Gigantic multi-kilometer docking cradles detach and begin tumbling.",
    env: "Emergency decompression vents spew white vapor plumes into the black void.",
    player: "Huge floating superstructure silhouettes drift across distant flight corridors." },

  { index: 23, time: "23:24", name: "Energy Tower Collapse", id: "energy_tower_collapse",
    subtitle: "The leaning energy tower buckles at mid-span and collapses into the debris field.",
    cause: "Complete failure of the lower compressive support pillars under tidal torque.",
    physicalEffect: "Tower snaps into multiple twisting sections, discharging millions of gigajoules.",
    env: "Colossal electric lightning burst discharges through nearby space clouds.",
    player: "Intense flash illuminates track; magnetic shockwave buffets racer." },

  { index: 24, time: "23:06", name: "Asteroid Tidal Stretch", id: "asteroid_tidal_stretch",
    subtitle: "Captured asteroids are pulled into elongated, teardrop-shaped molten filaments.",
    cause: "Differential gravitational acceleration exceeds the asteroid's internal cohesive strength.",
    physicalEffect: "Solid rock bodies stretch into 3-kilometer incandescent molten needles.",
    env: "Asteroids glow brilliant cherry-red with glowing magma cracks before splitting.",
    player: "Stretched glowing filaments streak past the track at hypersonic velocities." },

  { index: 25, time: "22:48", name: "Orbital Ring Break", id: "orbital_ring_break",
    subtitle: "The massive orbital megaring suffers a catastrophic fracture at Sector 4.",
    cause: "Hoop stress in the ring exceeds material limits as the planetary radius shifts.",
    physicalEffect: "The continuous megaring snaps open, its ends whipping outward with kinetic fury.",
    env: "A 100-kilometer arc of the ring recoils into space with flashing severed circuits.",
    player: "Deep resonant bass reverberates through track roadbed." },

  { index: 26, time: "22:30", name: "City Distortion", id: "city_distortion",
    subtitle: "Distant orbital metropolis platforms bend into surreal curved hyperbolic planes.",
    cause: "Gravitational lensing combined with physical structural sag toward the horizon.",
    physicalEffect: "Skyscrapers and city grids curve upward like an inverted bowl.",
    env: "City lights form a glowing amphitheater curved around the black hole.",
    player: "Disorienting visual parallax challenges depth perception on turns." },

  { index: 27, time: "22:12", name: "Space Tower Duplication", id: "space_tower_duplication",
    subtitle: "Gravitational lensing creates twin holographic ghost images of surviving space towers.",
    cause: "Light passing above and below the photon sphere creates dual optical paths.",
    physicalEffect: "Surviving towers appear in duplicate above and below the accretion plane.",
    env: "Mirrored glowing architecture flanks the black hole rim.",
    player: "Optical illusion requires trust in digital instruments over raw vision." },

  { index: 28, time: "21:54", name: "Station Spaghettification", id: "station_spaghettification",
    subtitle: "The outer ring of the primary space station begins severe tidal elongation.",
    cause: "Near-side of station accelerated thousands of m/s² faster than far-side.",
    physicalEffect: "Circular habitat ring stretches into an elongated elliptical oval.",
    env: "Station modules deform into glowing noodles of metal and burning atmosphere.",
    player: "Spaghettification visuals intensify; horizon warning alarms sound." },

  { index: 29, time: "21:36", name: "Plasma Storm", id: "plasma_storm",
    subtitle: "Violent solar-flare-scale plasma storms erupt from the inner accretion disk.",
    cause: "Magnetic reconnection in relativistic gas orbiting at 60% the speed of light.",
    physicalEffect: "High-density plasma arcs leap hundreds of kilometers above the disk plane.",
    env: "Blinding orange and cyan plasma curtains sweep across the sector.",
    player: "Thermal warning: core temperature rises rapidly; boost cooling advised." },

  { index: 30, time: "21:18", name: "Gravity Corridor", id: "gravity_corridor",
    subtitle: "A focused gravitational acceleration corridor opens along the main transit spine.",
    cause: "Constructive interference of framedragging vortexes.",
    physicalEffect: "Extreme longitudinal gravitational boost lane with fierce shear margins.",
    env: "Space looks blue-shifted and compressed along the corridor axis.",
    player: "Ship experiences extreme forward acceleration with reduced steering authority." },

  { index: 31, time: "21:00", name: "Megastructure Rotation", id: "megastructure_rotation",
    subtitle: "The colossal orbital arch megastructure begins a slow, uncontrolled axial roll.",
    cause: "Lense-Thirring precession induces relentless torque on the massive arch.",
    physicalEffect: "The 1000-meter-wide arch tilts 45 degrees, blocking upper starfields.",
    env: "Enormous shadows sweep across the racing arena as the arch rotates.",
    player: "Shadow transitions rapidly alternate between blinding glare and deep space darkness." },

  { index: 32, time: "20:42", name: "City Platform Separation", id: "city_platform_separation",
    subtitle: "Upper residential platforms detach from the city core and begin independent inward spirals.",
    cause: "Emergency explosive decoupling of doomed city sectors to relieve strain.",
    physicalEffect: "Multi-kilometer floating city discs drift into the lower orbital abyss.",
    env: "City discs glow like floating lanterns drifting toward the black hole mouth.",
    player: "Surreal emotional spectacle as human civilization fragments below." },

  { index: 33, time: "20:24", name: "Tower Foundation Tear", id: "tower_foundation_tear",
    subtitle: "The massive subterranean anchors of the space elevator tear free from bedrock.",
    cause: "Planetary crustal uplift driven by tidal gravitational deformation.",
    physicalEffect: "Foundational mountain-sized anchors rip out of the planetary surface.",
    env: "Vast plumes of shattered rock and dust erupt from the planetary horizon.",
    player: "Heavy gravitational wave shockwave rocks the racer." },

  // Part 2 — Civilization Breakdown (34–66)
  { index: 34, time: "20:06", name: "Communication Array Failure", id: "communication_array_failure",
    subtitle: "The global interstellar relay array disintegrates; sector-wide communications fail.",
    cause: "Thermal overload and tidal snapping of microwave emitter dishes.",
    physicalEffect: "Interstellar transceivers fail; static overrides all communication frequencies.",
    env: "Relay dishes tumble into space, flashing silent emergency beacon codes.",
    player: "Radio turns to eerie cosmic static; automated automated warning tickers take over." },

  { index: 35, time: "19:48", name: "Orbital Highway Fracture", id: "orbital_highway_fracture",
    subtitle: "Major parallel transit highways suffer structural rupture, leaving disconnected ramps.",
    cause: "Dynamic resonance from collapsing neighboring orbital platforms.",
    physicalEffect: "Highway surface cracks apart into floating segments; magnetic rails snap.",
    env: "Sections of glowing track tumble like falling dominoes through space.",
    player: "Navigation warning: parallel alternative routes are severed; stay on primary spine." },

  { index: 36, time: "19:30", name: "Rotating Habitat Desynchronization", id: "rotating_habitat_desync",
    subtitle: "Centrifugal artificial gravity habitats lose gyroscopic sync and begin tumbling violently.",
    cause: "Differential tidal precession torques the spin axes of opposing centrifuge rings.",
    physicalEffect: "Habitats tear along their central hubs, scattering residential pods.",
    env: "Glowing debris clouds of glass, steel, and atmosphere shimmer in vacuum.",
    player: "Debris spray crosses the racing corridor; shield deflectors engaged." },

  { index: 37, time: "19:12", name: "Magnetic Rail Discharge", id: "magnetic_rail_discharge",
    subtitle: "Superconducting magnetic highway rails discharge gigavolt arcs across the void.",
    cause: "Loss of cryogenic coolant leads to explosive quench in superconductor loops.",
    physicalEffect: "Violent blue-white electrical arcs leap across hundred-meter gaps in space.",
    env: "Lightning storm in zero gravity; glowing electromagnetic webs illuminate the track.",
    player: "Electromagnetic pulses drain boost capacitors if hit by arc discharge." },

  { index: 38, time: "18:54", name: "Docking Sphere Decompression", id: "docking_sphere_decompression",
    subtitle: "Orbital sphere terminals rupture, venting millions of liters of volatile propellant.",
    cause: "Structural puncture by tidal debris followed by catastrophic tank overpressure.",
    physicalEffect: "Vast spherical fuel clouds expand and instantly crystallize in deep vacuum.",
    env: "Iridescent crystalline vapor clouds shimmer with cyan and violet reflections.",
    player: "Cockpit visual obfuscation; micro-crystal impacts patter against the canopy." },

  { index: 39, time: "18:36", name: "Solar Collector Misalignment", id: "solar_collector_misalignment",
    subtitle: "Megascale orbital solar mirror arrays tilt into chaotic angles, focusing stray beam rays.",
    cause: "Attitude thruster depletion and gravitational gradient torque.",
    physicalEffect: "Square-kilometer mirrors spin out of control, sweeping solar beams across space.",
    env: "Blinding concentrated solar beams lance through dark space clouds.",
    player: "Stray thermal beam warning; quick steering required to avoid focused beam corridors." },

  { index: 40, time: "18:18", name: "Gravity Stabilizer Failure", id: "gravity_stabilizer_failure",
    subtitle: "The sector's primary quantum gravity dampening station suffers catastrophic burnout.",
    cause: "Thermal collapse of tachyon containment rings under relentless singular load.",
    physicalEffect: "Local gravity dampening drops to zero; raw gravitational gradient unleashed.",
    env: "The universe appears to bend twice as steeply; space warps violently around racer.",
    player: "Significant handling shift: craft feels 40% heavier and responds with fierce inertia." },

  { index: 41, time: "18:00", name: "Orbital Residential District Shift", id: "residential_district_shift",
    subtitle: "Suspended habitat domes slide along their mooring tracks, breaking umbilical links.",
    cause: "Tidal shear forces exceed safety clamp shear pins.",
    physicalEffect: "Cluster of 12 geodesic habitat domes drifts freely into the accretion zone.",
    env: "Golden-lit domes drift across the purple abyss like drowning fireflies.",
    player: "High-contrast visual landmarks illuminate the darkening void." },

  { index: 42, time: "17:42", name: "Research Station Tidal Split", id: "research_station_split",
    subtitle: "The deep-void astrophysics research station cleaves cleanly in two down its spine.",
    cause: "Tidal tension overcomes structural bulkheads along the station center of mass.",
    physicalEffect: "Two halves of station diverge on accelerating inward trajectories.",
    env: "Atmospheric decompression creates glowing aurora plumes between the separating halves.",
    player: "Dual radar targets split and accelerate into the black hole horizon." },

  { index: 43, time: "17:24", name: "Cargo Field Escape", id: "cargo_field_escape",
    subtitle: "Automated magnetic container yards break apart, launching thousands of cargo pods.",
    cause: "Loss of central containment grid power.",
    physicalEffect: "Thousands of standardized shipping containers scatter like shrapnel across space.",
    env: "Dense minefield of tumbling geometric containers glinting in starlight.",
    player: "Precision steering required to navigate dense container swarm." },

  { index: 44, time: "17:06", name: "Orbital Refinery Bend", id: "orbital_refinery_bend",
    subtitle: "Heavy mineral processing refinery complex bends into an elongated u-shape.",
    cause: "Extreme mass density of molten metal stores attracts differential gravitational pull.",
    physicalEffect: "Superheavy refinery hull deforms plastically without immediate fracture.",
    env: "Molten slag vents from ruptured storage tanks, creating fiery orange tracer streams.",
    player: "Thermal radiation alert; heat shimmer distorts view ahead." },

  { index: 45, time: "16:48", name: "Defense Platform Disarmament", id: "defense_platform_disarm",
    subtitle: "Automated defense platforms suffer magazine detonations as shells are crushed.",
    cause: "Tidal compression detonates sensitive kinetic munitions in orbital silos.",
    physicalEffect: "Sequential secondary explosions ripple along defense platform perimeter.",
    env: "Brilliant orange fireballs expand and dissipate instantly in vacuum.",
    player: "Kinetic shockwaves rattle ship chassis; evasive trajectory engaged." },

  { index: 46, time: "16:30", name: "Orbital Ring Tidal Tear", id: "orbital_ring_tidal_tear",
    subtitle: "Secondary tear opens in the fractured orbital ring, shedding massive gantry spans.",
    cause: "Dynamic whipping motion of the severed ring sections induces secondary shears.",
    physicalEffect: "A 50-kilometer section of the ring detaches and curls inward toward the disk.",
    env: "Massive metal ribbon glowing red at its edges twists gracefully into the void.",
    player: "Scale of destruction overwhelms forward horizon; world feels miniature beside it." },

  { index: 47, time: "16:12", name: "Holographic City Failure", id: "holographic_city_failure",
    subtitle: "Megacity holographic advertising arrays and sky-projections glitch and collapse.",
    cause: "Loss of synchronized ground-station laser projectors.",
    physicalEffect: "Gigantic kilometer-tall digital avatars and corporate logos tear and dissolve into static.",
    env: "Electric cyan and magenta digital noise artifacts flicker across the space vacuum.",
    player: "Futuristic visual aesthetic strips away, revealing the raw, bare structural bones." },

  { index: 48, time: "15:54", name: "Spaceport Orbital Drift", id: "spaceport_orbital_drift",
    subtitle: "The central interstellar spaceport begins an irreversible terminal descent.",
    cause: "Orbital decay reaches critical cascade point as atmospheric drag rises.",
    physicalEffect: "Massive hub station drops 500 kilometers in altitude, glowing incandescent.",
    env: "Spaceport hull glows cherry-red with atmospheric and plasma friction.",
    player: "Spaceport descends into the fiery accretion disk background." },

  { index: 49, time: "15:36", name: "Traffic Lane Collapse", id: "traffic_lane_collapse",
    subtitle: "Automated neon route markers along civilian transit lanes deactivate permanently.",
    cause: "Grid power completely fails across outer transit corridors.",
    physicalEffect: "Illuminated waypoints go dark; only racing track boundaries remain powered.",
    env: "Surrounding space grows significantly darker; only the black hole and track glow.",
    player: "Visual clarity improves as civilian background clutter disappears." },

  { index: 50, time: "15:18", name: "Megastructure Joint Failure", id: "megastructure_joint_failure",
    subtitle: "The primary expansion joint of the orbital arch shears off with explosive energy.",
    cause: "Unrelenting tidal torque exceeds multi-meter steel pin tolerances.",
    physicalEffect: "The arch's right support column snaps, leaving the arch cantilevered into space.",
    env: "Explosion of sparks and structural fragments flies thousands of meters outward.",
    player: "Colossal mechanical snap produces high-energy gravitational transducer signal." },

  { index: 51, time: "15:00", name: "Gravity Well Deepening", id: "gravity_well_deepening",
    subtitle: "The singularity's effective mass increases as captured megastructures fall inward.",
    cause: "Accretion of hundreds of billions of tons of orbital debris into the event horizon.",
    physicalEffect: "Event horizon radius visibly expands; photon sphere radius grows proportionally.",
    env: "Central dark black disc visibly expands on the screen; white ring thickens.",
    player: "Gravitational pull increases across entire track spline." },

  { index: 52, time: "14:42", name: "Observation Array Collapse", id: "observation_array_collapse",
    subtitle: "Deep-space radio telescope arrays fold inward like crushed umbrellas.",
    cause: "Centripetal acceleration combines with tidal gradient compression.",
    physicalEffect: "Massive parabolic sensor meshes buckle and fold into compact debris masses.",
    env: "Silvery metallic reflections warp and crumple into tangled balls of scrap.",
    player: "Cockpit radar resolution shifts from long-range to immediate tactical." },

  { index: 53, time: "14:24", name: "Wormhole Infrastructure Destabilization", id: "wormhole_infra_destabilization",
    subtitle: "The Route 03 Wormhole Escape gate apparatus experiences harmonic field oscillation.",
    cause: "External black hole gravitational tides interact with wormhole exotic matter coils.",
    physicalEffect: "Wormhole containment rings spin erratically, shedding electric turquoise corona discharges.",
    env: "Spacetime around the wormhole exit shimmers with psychedelic chromatic aberration.",
    player: "Route 03 landmark visible in distance; gateway stability countdown begins." },

  { index: 54, time: "14:06", name: "Planetary Observation Failure", id: "planetary_observation_failure",
    subtitle: "Distant science satellites studying the terrestrial planet lose telemetry.",
    cause: "Intense relativistic plasma clouds blot out communication line of sight.",
    physicalEffect: "Sensor feeds terminate with abrupt flatlines.",
    env: "Thick clouds of ionised plasma mask the distant planet's southern hemisphere.",
    player: "HUD status ticker updates: 'PLANETARY SENSORS OFFLINE // VISUAL RECON ONLY'." },

  { index: 55, time: "13:48", name: "Industrial Platform Breakaway", id: "industrial_platform_breakaway",
    subtitle: "Automated heavy mining platforms break from mooring pylons, careening inward.",
    cause: "Centrifugal breakaway as orbital velocity fails to balance tidal pull.",
    physicalEffect: "Hexagonal industrial complexes tumble across the track's lower airspace.",
    env: "Smokestacks and smelter flames extinguish in vacuum as platforms break apart.",
    player: "Massive floating platform passes beneath the race track." },

  { index: 56, time: "13:30", name: "Energy Bridge Network Failure", id: "energy_bridge_failure",
    subtitle: "Luminous energy transmission bridges linking orbital cities collapse into sparks.",
    cause: "Phase-locking failure between emitter and collector towers.",
    physicalEffect: "Kilometer-long solid-light bridges flicker and dissolve into harmless photon mist.",
    env: "Bright cyan light beams vanish, plunging city sectors into pitch blackness.",
    player: "Visual track path stands out with stark, high-contrast neon clarity." },

  { index: 57, time: "13:12", name: "City Power Grid Islanding", id: "city_grid_islanding",
    subtitle: "Surviving orbital city pockets isolate power grids, glowing like isolated islands.",
    cause: "Automated emergency isolation breakers sever compromised sector lines.",
    physicalEffect: "Remaining city sectors maintain faint amber emergency illumination.",
    env: "Sparse islands of amber light speckle the sprawling dark orbital wreckage.",
    player: "Haunting reminder of civilization fighting for survival in the background." },

  { index: 58, time: "12:54", name: "Gravity Shear", id: "gravity_shear",
    subtitle: "A sharp horizontal gravity shear plane forms across the middle race sector.",
    cause: "Differential frame dragging between inner and outer ergosphere boundaries.",
    physicalEffect: "Upper and lower sections of objects are pulled in opposite orbital directions.",
    env: "Debris streams appear sheared off along a razor-sharp horizontal plane.",
    player: "Severe turbulence when crossing sector boundary; counter-steering required." },

  { index: 59, time: "12:36", name: "Rotating Habitat Structural Failure", id: "rotating_habitat_failure",
    subtitle: "The final large spinning habitat ring suffers catastrophic hub detachment.",
    cause: "Spoke tension exceeds tensile limits under simultaneous centrifugal and tidal load.",
    physicalEffect: "Centrifuge spokes tear away from hub; outer rim uncurls into an open whip.",
    env: "Spectacular kinetic unraveling of a 4-kilometer habitat structure.",
    player: "Debris field expands rapidly across lower orbital plane." },

  { index: 60, time: "12:18", name: "Orbital Debris Cascade", id: "debris_cascade",
    subtitle: "Kessler syndrome reaches runaway threshold across the entire orbital sphere.",
    cause: "Exponential collision rate between thousands of drifting structure fragments.",
    physicalEffect: "Space fills with millions of high-velocity hypervelocity fragments.",
    env: "Continuous micro-flashes illuminate the background as fragments collide at 20 km/s.",
    player: "Shield integrity telemetry hums under constant micro-impact bombardment." },

  { index: 61, time: "12:00", name: "Half-Collapse Threshold", id: "half_collapse_threshold",
    subtitle: "The twelve-minute midpoint is crossed: half of all orbital civilization structures are destroyed.",
    cause: "Calculated catastrophic cascade milestone across orbital infrastructure.",
    physicalEffect: "Major transition in environmental dynamics: background shifts from architecture to raw astrophysical destruction.",
    env: "The accretion disk now dominates 60% of the visual field; deep red and orange glow.",
    player: "Tactical HUD announces: 'HALF-COLLAPSE REACHED // GRAV ESCALATION TIER 2'." },

  { index: 62, time: "11:42", name: "Orbital Rail Separation", id: "orbital_rail_separation",
    subtitle: "Surviving magnetic rail transit corridors separate into free-floating ribbons.",
    cause: "Thermal expansion and tidal stretching sever expansion couplings.",
    physicalEffect: "Long flexible neon-lit rail tracks undulate like luminous ribbons in space.",
    env: "Glowing cyan and violet ribbons drift languidly toward the event horizon.",
    player: "Stunning visual backdrop provides intense feeling of speed and scale." },

  { index: 63, time: "11:24", name: "Research Platform Breakaway", id: "research_platform_breakaway",
    subtitle: "Primary quantum observation laboratory module falls out of high orbit.",
    cause: "Reaction control thruster burnouts.",
    physicalEffect: "Compact research module plunges directly into the accretion disc shockwave.",
    env: "Module vaporizes with brilliant green and gold spectroscopic flash.",
    player: "Spectroscopic flash illuminates cockpit interior with vivid colors." },

  { index: 64, time: "11:06", name: "Civilization Light Cascade", id: "civilization_light_cascade",
    subtitle: "Cascading blackout sweeps across the entire remaining planetary megacity network.",
    cause: "Primary geothermal and nuclear core taps on the planet surface are overwhelmed.",
    physicalEffect: "Billions of city lights extinguish sequentially in massive dark waves.",
    env: "The planet below turns from a dazzling web of golden light into a dark, shadowy sphere.",
    player: "Visual mood turns profoundly somber and cinematic; race against doom intensifies." },

  { index: 65, time: "10:48", name: "Major Orbital Structure Fracture", id: "major_orbital_structure_fracture",
    subtitle: "The largest suspended orbital drydock facility cleaves in two.",
    cause: "Combined gravitational torque and kinetic impacts from debris cascade.",
    physicalEffect: "A structure larger than Manhattan Island splits down its longitudinal axis.",
    env: "Massive decompression jets and structural lightning illuminate the colossal split.",
    player: "Sensors register seismic-class gravitational impulse." },

  { index: 66, time: "10:30", name: "Civilization Fragmentation", id: "civilization_fragmentation",
    subtitle: "Final centralized orbital network cohesion is lost; all sectors now drift independently.",
    cause: "Complete breakdown of automated orbital coordination network.",
    physicalEffect: "End of Part 2. The artificial world has dissolved into chaotic wreckage.",
    env: "Sky is dominated by floating megastructure wreckage and blazing accretion fire.",
    player: "HUD announces transition into Part 3: FINAL COLLAPSE." },

  // Part 3 — Final Collapse (67–100)
  { index: 67, time: "10:12", name: "Surviving District Separation", id: "surviving_district_separation",
    subtitle: "Last surviving city districts break apart, scattering isolated survival domes.",
    cause: "Tidal forces overcome remaining inter-district mechanical trusses.",
    physicalEffect: "Individual survival pods drift into divergent, doomed orbital vectors.",
    env: "Dim emergency beacons drift like glowing embers into the central vortex.",
    player: "Track boundaries flex slightly under rising gravitational gradient." },

  { index: 68, time: "09:54", name: "Orbital Ring Secondary Fracture", id: "orbital_ring_secondary_fracture",
    subtitle: "The shattered megaring snaps into dozens of smaller curling arc segments.",
    cause: "Secondary harmonic vibrations shatter brittle superconducting segments.",
    physicalEffect: "The ring dissolves from two large halves into twenty curling arcs.",
    env: "Ring segments curl like burning paper edges, glowing incandescent orange.",
    player: "Background architecture transforms into chaotic cosmic debris." },

  { index: 69, time: "09:36", name: "Space Elevator Cable Failure", id: "space_elevator_cable_failure",
    subtitle: "The primary space elevator tether snaps at altitude 8,000 kilometers.",
    cause: "Tensile stress exceeds theoretical limits of carbon nanotube lattice.",
    physicalEffect: "Upper cable whips outward toward escape velocity; lower cable coils down to planet.",
    env: "Tens of thousands of kilometers of glowing cable wrap around the planetary sphere.",
    player: "Dramatic hyper-velocity line of light slashes across the skybox." },

  { index: 70, time: "09:18", name: "Orbital Highway Breakaway", id: "orbital_highway_breakaway",
    subtitle: "Upper bypass highways break from pylons and begin spiraling into the accretion stream.",
    cause: "Pylon foundation failure under extreme horizontal tidal acceleration.",
    physicalEffect: "Hundreds of kilometers of highway roadbed plunge into the fiery accretion disk.",
    env: "Highway surface dissolves into glowing lava-like filaments as it approaches horizon.",
    player: "Player's active track boundary rails hum with emergency stabilization fields." },

  { index: 71, time: "09:00", name: "City Core Power Failure", id: "city_core_power_failure",
    subtitle: "The central quantum singularity power tap inside the city hub goes supercritical.",
    cause: "Feedback loop from the external black hole destabilizes internal containment.",
    physicalEffect: "City core undergoes internal implosion, collapsing in on itself without external blast.",
    env: "Silent, eerie implosion sucks the center of the floating city into a compact point.",
    player: "High-intensity gravitational dip pulls hard on racer's chassis." },

  { index: 72, time: "08:42", name: "Planetary Orbital Distortion", id: "planetary_orbital_distortion",
    subtitle: "The distant sapphire planet is pulled into a visibly eccentric, decaying trajectory.",
    cause: "Planetary mass is insufficient to maintain orbit against the supermassive core.",
    physicalEffect: "Planet drops lower in the skybox, its sphere elongating slightly into an egg shape.",
    env: "Atmospheric oceans on the planet show massive tidal bulges visible from space.",
    player: "Planet now looms twice as large, its oceans glowing under accretion light." },

  { index: 73, time: "08:24", name: "Megastructure Tidal Twist", id: "megastructure_tidal_twist",
    subtitle: "The colossal orbital arch twists 90 degrees, corkscrewing under frame-dragging torque.",
    cause: "Kerr metric frame dragging exerts differential spin on opposing arch ends.",
    physicalEffect: "Massive megastructure deforms into a spiraling helix of twisted metal.",
    env: "Arch's blue illumination strips turn amber under extreme internal plastic stress.",
    player: "Dizzying visual perspective as giant corkscrew structure fills the zenith." },

  { index: 74, time: "08:06", name: "Habitat Cluster Separation", id: "habitat_cluster_separation",
    subtitle: "Last orbital survival cluster disperses; escape pods launch into escape trajectories.",
    cause: "Final emergency evacuation order issued by surviving orbital authorities.",
    physicalEffect: "Thousands of tiny escape pod thrusters ignite simultaneously.",
    env: "Sky filled with thousands of tiny white engine pinpricks scattering outward.",
    player: "Escape routes Route 01 (Launcher), Route 02 (Emergency), Route 03 (Wormhole) highlighted on HUD." },

  { index: 75, time: "07:48", name: "Gravity Lensing Surge", id: "gravity_lensing_surge",
    subtitle: "Gravitational lensing triples in strength; multiple Einstein rings encircle the void.",
    cause: "Inner disk compression doubles light deflection angles around photon sphere.",
    physicalEffect: "Surrounding starfields and wreckage warp into three nested concentric halos.",
    env: "Space looks wildly distorted; geometric shapes warp into fluid, flowing curves.",
    player: "Track boundaries appear curved even along straightaways; trust steering instruments." },

  { index: 76, time: "07:30", name: "Orbital Docking Collapse", id: "orbital_docking_collapse",
    subtitle: "Terminal failure of remaining orbital docking hubs; structures pancake inward.",
    cause: "Tidal compression along transverse axes crushes hollow docking bays.",
    physicalEffect: "Spherical and cylindrical docking modules crumple like paper cups.",
    env: "Metallic hulls flatten and shred, scattering interior equipment into the void.",
    player: "Acoustic rumble transmitted through ship landing skids and magnetic guide rails." },

  { index: 77, time: "07:12", name: "Industrial District Breakup", id: "industrial_district_breakup",
    subtitle: "Heavy foundry platforms fragment into glowing chunks of white-hot slag.",
    cause: "Superheated industrial furnaces rupture under tidal pressure.",
    physicalEffect: "Rivers of molten metal escape into vacuum, freezing into metallic hail.",
    env: "Glowing red and orange meteoric hail showers through surrounding airspace.",
    player: "Shield deflectors flash continuously against micro-slag bombardment." },

  { index: 78, time: "06:54", name: "Gravity Wave Interference", id: "gravity_wave_interference",
    subtitle: "Overlapping gravitational waves create chaotic interference patterns in spacetime.",
    cause: "Multiple collapsing megastructure bodies generate asynchronous wave trains.",
    physicalEffect: "Spacetime expands and contracts unpredictably beneath the race track.",
    env: "Visual rippling of space like heat waves across a desert highway.",
    player: "Ship oscillates between feeling weightless and feeling crushing 8G gravity spikes." },

  { index: 79, time: "06:36", name: "Surviving Traffic Evacuation", id: "surviving_traffic_evacuation",
    subtitle: "Last military and civilian evacuation convoys make desperate runs for escape routes.",
    cause: "Approaching six-minute critical point forces final evacuation attempts.",
    physicalEffect: "High-speed evacuation vessels streak along outer launch vector corridors.",
    env: "Blazing ion engine plumes illuminate the dark debris canyons around the route.",
    player: "Orbital Launcher (Route 01) and Emergency Tower (Route 02) approach on minimap." },

  { index: 80, time: "06:18", name: "Research Complex Tear", id: "research_complex_tear",
    subtitle: "The primary antimatter research complex tears open; magnetic containment fails.",
    cause: "Power grid failure collapses superconducting antimatter bottle traps.",
    physicalEffect: "Antimatter annihilates with surrounding structure in pure gamma-ray burst.",
    env: "Brilliant pure-violet detonation sphere expands and illuminates the entire sector.",
    player: "Visor auto-polarizes against gamma flash; EMP causes temporary HUD chromatic split." },

  { index: 81, time: "06:00", name: "Six-Minute Critical Threshold", id: "six_minute_critical_threshold",
    subtitle: "T-06:00. The collapse enters its final critical phase; outer escape vectors begin closing.",
    cause: "Event horizon accretion rate increases tenfold; ISCO radius moves outward.",
    physicalEffect: "Stable orbit radius expands beyond the primary racing corridor.",
    env: "Black hole accretion disk flares into blinding golden and crimson fire.",
    player: "HUD warning: 'T-06:00 CRITICAL THRESHOLD // ESCAPE WINDOWS CLOSING'." },

  { index: 82, time: "05:42", name: "Orbital Stabilizer Chain Failure", id: "stabilizer_chain_failure",
    subtitle: "Cascading failure of all gyroscopic stabilization stations along the sector rim.",
    cause: "Bearing seizure under unrelenting tidal torque.",
    physicalEffect: "Remaining stable platforms begin rapid, violent tumbling.",
    env: "Giant gyroscope wheels hundreds of meters across tear loose and roll through space.",
    player: "Visual reference axes spin; artificial horizon instrument becomes essential." },

  { index: 83, time: "05:24", name: "Energy Network Collapse", id: "energy_network_collapse",
    subtitle: "The planetary orbital energy grid suffers absolute, irreversible blackout.",
    cause: "Destruction of final solar collector arrays and core transformer stations.",
    physicalEffect: "All non-essential illumination across the entire star system goes dark.",
    env: "Stark contrast: pitch black space contrasted with the roaring, blazing accretion disk.",
    player: "Track neon boundaries glow with brilliant emerald and cyan contrast." },

  { index: 84, time: "05:06", name: "Orbital Observation Array Disintegration", id: "observation_array_disintegration",
    subtitle: "Final telescope towers and deep radar stations disintegrate into powder.",
    cause: "Tidal friction pulverizes composite truss structures into fine carbon dust.",
    physicalEffect: "Structures dissolve into dense black carbon dust clouds.",
    env: "Dark clouds of pulverized carbon drift across the glowing accretion background.",
    player: "Visor wipers engage as carbon soot particles coat cockpit canopy." },

  { index: 85, time: "04:48", name: "City Platform Tidal Stretch", id: "city_platform_stretch",
    subtitle: "The last intact floating city platform stretches into an elongated arc of light.",
    cause: "Differential gravitational acceleration pulls the platform into spaghettification.",
    physicalEffect: "Circular city disc stretches to five times its original length.",
    env: "City lights form a long luminous filament descending toward the singularity mouth.",
    player: "Witnessing direct spaghettification of massive human-built architecture." },

  { index: 46, time: "04:30", name: "Megastructure Section Loss", id: "megastructure_section_loss",
    subtitle: "The central keystone section of the orbital arch separates and plunges into the void.",
    cause: "Complete shearing of internal reinforcement cables.",
    physicalEffect: "A 500-meter block of megastructure architecture falls toward the event horizon.",
    env: "Giant rectangular landmark tumbles downward, silhouette outlined against photon ring.",
    player: "Scale landmark lost; horizon feels vast and terrifyingly empty." },

  { index: 87, time: "04:12", name: "Debris Orbital Cascade", id: "debris_cascade_final",
    subtitle: "Debris ribbons compress into an ultra-dense, razor-thin equatorial disc.",
    cause: "Gravitational relaxation forces all matter into the black hole's equatorial plane.",
    physicalEffect: "All scattered fragments align into a razor-sharp glowing plane of matter.",
    env: "A thin, blindingly bright blade of glowing dust cuts horizontally across the view.",
    player: "Track passes directly through the equatorial disc; brilliant particle shower." },

  { index: 88, time: "03:54", name: "Planetary Lensing Break", id: "planetary_lensing_break",
    subtitle: "The distorted image of the planet breaks into disconnected sparkling optical arcs.",
    cause: "Atmospheric stripping of the planet disrupts smooth optical refraction.",
    physicalEffect: "The planetary mirage shatters into a glittering necklace of Einstein images.",
    env: "Luminous blue and white arcs sparkle around the black hole perimeter.",
    player: "Breathtaking cosmic visual phenomenon fills upper canopy." },

  { index: 89, time: "03:36", name: "Surviving Spaceport Failure", id: "spaceport_failure_final",
    subtitle: "The terminal spaceport structure strikes the upper accretion disc and vaporizes.",
    cause: "Perigee drops below accretion disc surface threshold.",
    physicalEffect: "Instant thermal and kinetic vaporization of a ten-million-ton facility.",
    env: "Explosive shockwave ripples across the surface of the plasma accretion disc.",
    player: "Shockwave causes significant ship turbulence and compass deflection." },

  { index: 90, time: "03:18", name: "Orbital Civilization Tilt", id: "civilization_tilt",
    subtitle: "All surviving debris planes tilt 30 degrees, aligning with the spinning Kerr metric.",
    cause: "Bardeen-Petterson effect aligns orbiting viscous matter with the black hole's spin axis.",
    physicalEffect: "Entire surrounding universe tilts into alignment with the black hole's equator.",
    env: "Disorienting cosmic roll as all dust lanes and wreckage planes tilt together.",
    player: "Horizon tilts dramatically; ship gyroscopes fight to maintain reference plane." },

  { index: 91, time: "03:00", name: "Three-Minute Critical State", id: "three_minute_critical_state",
    subtitle: "T-03:00. Escape vectors reach maximum instability; three minutes until total collapse.",
    cause: "Spacetime curvature gradient exceeds safe containment parameters.",
    physicalEffect: "Gravitational acceleration increases exponentially toward zero hour.",
    env: "Photon ring pulses with urgent, rapid flashes of high-energy violet radiation.",
    player: "Emergency audio sirens sound; HUD displays critical countdown timer." },

  { index: 92, time: "02:42", name: "Final Communication Loss", id: "final_communication_loss",
    subtitle: "All emergency broadcasts, distress beacons, and automated transponders go silent.",
    cause: "Severe gravitational redshift shifts all radio transmissions into undetectable low frequencies.",
    physicalEffect: "Complete electromagnetic silence across all frequencies.",
    env: "Eerie cosmic silence; only the low resonant hum of the black hole remains.",
    player: "Radio silence. You are the last surviving ship operating in this sector." },

  { index: 93, time: "02:24", name: "Final Orbital Ring Movement", id: "final_orbital_ring_movement",
    subtitle: "The last remaining arc of the megaring slides into the outer accretion boundary.",
    cause: "Drag against relativistic plasma disc decelerates final ring segment.",
    physicalEffect: "The enormous steel arc vanishes into the incandescent plasma sea.",
    env: "Blazing white wake behind the disappearing structure before complete assimilation.",
    player: "Visual horizon now completely stripped of all ancient civilization landmarks." },

  { index: 94, time: "02:06", name: "Final Power District Failure", id: "final_power_district_failure",
    subtitle: "The last emergency power bunker exhausts its fusion cores; final lights extinguish.",
    cause: "Depletion of localized fuel reserves under crushing gravitational pressure.",
    physicalEffect: "Final scattered golden pinpricks of light wink out.",
    env: "The sector is now illuminated exclusively by the black hole's accretion fury.",
    player: "Cockpit instrument HUD glows with stark, solitary neon intensity." },

  { index: 95, time: "01:48", name: "Major Structural Separation", id: "major_structural_separation_final",
    subtitle: "The race track's own foundational anchoring pylons begin severing under tidal strain.",
    cause: "Differential tidal pull reaches the track's own structural threshold.",
    physicalEffect: "Track roadbed begins flexing and rippling like a wave on water.",
    env: "Track neon guide rails warp and bend into rolling sinuous waves.",
    player: "Highway surface undulates under the racer; steering requires intense rhythm and anticipation." },

  { index: 96, time: "01:30", name: "Gravitational Dominance", id: "gravitational_dominance",
    subtitle: "Gravitational forces completely overwhelm all other physical forces in the sector.",
    cause: "Proximity to the event horizon produces gravitational accelerations exceeding 10,000G.",
    physicalEffect: "Matter ceases to behave as solid objects, flowing like fluid along geodesic curves.",
    env: "All surrounding objects stretch into long, luminous streaks pointing directly at the core.",
    player: "Ship thrusters operate at 100% capacity just to maintain forward velocity." },

  { index: 97, time: "01:12", name: "Civilization Breakup", id: "civilization_breakup_final",
    subtitle: "Every trace of human civilization across the star system has been pulverized into dust.",
    cause: "Complete tidal disintegration of all artificial structures.",
    physicalEffect: "Only raw atoms, plasma, and relativistic particles remain.",
    env: "Pure astrophysical environment: Singularity, Accretion Disk, Photon Ring, and Racer.",
    player: "HUD displays: 'CIVILIZATION TERMINATED // REACH SURVIVAL CORRIDOR NOW'." },

  { index: 98, time: "00:54", name: "Final Orbital Fall", id: "final_orbital_fall",
    subtitle: "The companion moon crosses the Roche limit and shatters into billions of fragments.",
    cause: "Tidal forces exceed lunar gravitational self-attraction.",
    physicalEffect: "The moon shatters into a colossal expanding cloud of luminous lunar dust.",
    env: "A magnificent pearlescent ring forms instantly from the shattered moon's remains.",
    player: "Breathtaking celestial catastrophe frames the final approach to the escape routes." },

  { index: 99, time: "00:36", name: "Last Surviving Structures", id: "last_surviving_structures",
    subtitle: "T-00:36. Only the three escape routes and the racer remain intact; final sprint.",
    cause: "Final 36-second survival corridor before the absolute collapse threshold.",
    physicalEffect: "Route 01 (Orbital Launcher), Route 02 (Emergency Corridor), Route 03 (Wormhole) emit maximum beacon pulses.",
    env: "The three escape routes glow with blinding cyan, amber, and turquoise energy fields.",
    player: "Maximum boost recommended! Commit to an escape corridor or face event horizon infall!" },

  { index: 100, time: "00:00", name: "Final Collapse State", id: "final_collapse_state",
    subtitle: "T-00:00. The clock reaches zero. Complete gravitational implosion of the star system.",
    cause: "The event horizon reaches maximum instability; singularity consumes all remaining sector matter.",
    physicalEffect: "Sequential cosmic climax: motion slows -> near silence -> dark gravitational pulse -> cosmic boom -> aftermath -> rebuild.",
    env: "NO WHITE FLASH. Pure dark gravitational implosion, sudden silence, followed by the Ultimate Combined Ending sequence.",
    player: "The universe collapses inward. Safe-zone shelter or escape trajectory determines ultimate survival outcome." }
];

console.log(`Loaded ${RAW_EVENTS_DATA.length} events.`);

// Verification: exactly 100 events
if (RAW_EVENTS_DATA.length !== 100) {
  throw new Error(`Expected exactly 100 events, got ${RAW_EVENTS_DATA.length}`);
}

const lines = [];
lines.push(`import type { CosmicEventDefinition } from "./cosmicSystems";`);
lines.push(``);
lines.push(`export const RAW_COSMIC_100_EVENTS: Omit<CosmicEventDefinition, "element1" | "element2" | "eventOccurrenceNarrative" | "completionStrategy" | "cinematicBeats">[] = [`);

RAW_EVENTS_DATA.forEach((e, idx) => {
  const i = e.index;
  const triggerTime = i === 100 ? 1800 : (i - 1) * 18;
  const severity = Number((1.0 + (i - 1) * (9.0 / 99)).toFixed(2));
  const progressRatio = (i - 1) / 99;

  const padIdx = String(i).padStart(2, '0');
  const title = `EVENT ${padIdx} — ${e.time} ${e.name.toUpperCase()}`;

  const gravityParams = {
    gravityInfluenceRadius: Number((0.15 + progressRatio * 0.85).toFixed(3)),
    gravityAsymmetry: Number((0.05 + progressRatio * 0.95).toFixed(3)),
    lensingStrength: Number((0.1 + progressRatio * 0.9).toFixed(3)),
    tidalStrength: Number((0.12 + progressRatio * 0.88).toFixed(3)),
    infallRate: Number((0.1 + progressRatio * 0.9).toFixed(3)),
    accretionActivity: Number((0.15 + progressRatio * 0.85).toFixed(3)),
    matterStreamIntensity: Number((0.1 + progressRatio * 0.9).toFixed(3)),
    gravitationalWaveStrength: Number((0.05 + progressRatio * 0.95).toFixed(3)),
    spacetimeDistortion: Number((0.08 + progressRatio * 0.92).toFixed(3)),
    environmentCompression: Number((0.05 + progressRatio * 0.95).toFixed(3)),
    asymmetricExpansion: Number((0.05 + progressRatio * 0.95).toFixed(3)),
    collapseIntensity: Number((0.05 + progressRatio * 0.95).toFixed(3)),
  };

  const entry = {
    index: i,
    id: e.id,
    name: e.name.toUpperCase(),
    title: title,
    countdownTime: e.time,
    subtitle: e.subtitle,
    cause: e.cause,
    physicalEffect: e.physicalEffect,
    environmentalResponse: e.env,
    playerResponse: e.player,
    triggerTime: triggerTime,
    severity: severity,
    gravityParams: gravityParams,
  };

  const isLast = idx === RAW_EVENTS_DATA.length - 1;
  lines.push(`  ${JSON.stringify(entry, null, 2).replace(/\n/g, '\n  ')}${isLast ? '' : ','}`);
});

lines.push(`];`);
lines.push(``);
lines.push(`export const RAW_COSMIC_40_EVENTS = RAW_COSMIC_100_EVENTS;`);
lines.push(``);

const targetPath = path.join(__dirname, '../src/game/catastrophe/cosmic100EventsCatalog.ts');
fs.writeFileSync(targetPath, lines.join('\n'), 'utf8');
console.log(`Successfully generated ${RAW_EVENTS_DATA.length} events into ${targetPath}`);
