/**
 * SUBMODE 10: THE FINAL COLLAPSE — 100-EVENT MASTER TIMELINE
 *
 * Exact authoritative schedule for the 15:00 -> 00:00 circular countdown clock.
 * Every event contains:
 * - eventNumber (1 to 100)
 * - exactTriggerSeconds (0 to 900)
 * - displayTime (canonical MM:SS)
 * - eventName (canonical gameplay event name)
 * - alertTitle (concise headline)
 * - alertMessage (authoritative warning text for the single Event Alert Bar)
 * - severity ('NOTICE' | 'WARNING' | 'DANGER' | 'CRITICAL' | 'EMERGENCY' | 'FINAL_WARNING' | 'SINGULARITY_CRITICAL')
 * - severityLevel (1.0 to 10.0)
 * - audioCue
 * - environmentReaction
 * - cameraShake
 * - blackHoleInstability
 */

export type AlertSeverityType =
  | 'NOTICE'
  | 'WARNING'
  | 'DANGER'
  | 'CRITICAL'
  | 'EMERGENCY'
  | 'FINAL_WARNING'
  | 'SINGULARITY_CRITICAL';

export interface FinalCollapseMasterEvent {
  eventNumber: number;
  exactTriggerSeconds: number;
  displayTime: string;
  eventName: string;
  alertTitle: string;
  alertMessage: string;
  severity: AlertSeverityType;
  severityLevel: number;
  audioCue: 'advisory' | 'warning' | 'danger' | 'critical' | 'emergency' | 'final_warning' | 'collapse';
  environmentReaction: string;
  cameraShake: number;
  blackHoleInstability: number;
  affectedObject: string;
}

export const FINAL_COLLAPSE_MASTER_100_TIMELINE: readonly FinalCollapseMasterEvent[] = [
  // =========================================================================
  // EVENTS 01–20: NOTICE / WARNING (15:00 → 12:07)
  // =========================================================================
  {
    eventNumber: 1,
    exactTriggerSeconds: 0,
    displayTime: '15:00',
    eventName: 'GRAVITATIONAL ANOMALY DETECTED',
    alertTitle: 'GRAVITATIONAL ANOMALY',
    alertMessage: 'GRAVITATIONAL ANOMALY DETECTED // 15:00 COUNTDOWN INITIATED',
    severity: 'NOTICE',
    severityLevel: 1.0,
    audioCue: 'advisory',
    environmentReaction: 'Central singularity awakens with low-frequency metric pulse; photon ring ignites.',
    cameraShake: 0.15,
    blackHoleInstability: 0.10,
    affectedObject: 'Singularity Event Horizon',
  },
  {
    eventNumber: 2,
    exactTriggerSeconds: 9,
    displayTime: '14:51',
    eventName: 'ORBITAL INSTABILITY',
    alertTitle: 'ORBITAL INSTABILITY',
    alertMessage: 'ORBITAL INSTABILITY DETECTED // ROUTE STRUCTURES SHIFTING',
    severity: 'NOTICE',
    severityLevel: 1.2,
    audioCue: 'advisory',
    environmentReaction: 'Outer relativistic highway registers micro-torsion; starlight bends along Einstein arcs.',
    cameraShake: 0.20,
    blackHoleInstability: 0.12,
    affectedObject: 'Orbital Highway Tarmac',
  },
  {
    eventNumber: 3,
    exactTriggerSeconds: 18,
    displayTime: '14:42',
    eventName: 'GRAVITY FIELD FLUCTUATION',
    alertTitle: 'FIELD FLUCTUATION',
    alertMessage: 'GRAVITY FIELD FLUCTUATING // LATERAL DRIFT DETECTED',
    severity: 'NOTICE',
    severityLevel: 1.4,
    audioCue: 'advisory',
    environmentReaction: 'Ergosphere radius expands subtly; track lane magnetic guides pulse with cyan caustics.',
    cameraShake: 0.25,
    blackHoleInstability: 0.14,
    affectedObject: 'Magnetic Track Guides',
  },
  {
    eventNumber: 4,
    exactTriggerSeconds: 27,
    displayTime: '14:33',
    eventName: 'DISTANT DEBRIS COLLISION',
    alertTitle: 'DEBRIS COLLISION',
    alertMessage: 'DISTANT DEBRIS COLLISION // FRAGMENTS ENTERING ORBIT',
    severity: 'NOTICE',
    severityLevel: 1.6,
    audioCue: 'advisory',
    environmentReaction: 'Outer satellite impact debris illuminates sector horizon with ionized particle showers.',
    cameraShake: 0.30,
    blackHoleInstability: 0.16,
    affectedObject: 'Outer Satellite Ring',
  },
  {
    eventNumber: 5,
    exactTriggerSeconds: 36,
    displayTime: '14:24',
    eventName: 'PLANETARY ORBIT SHIFT',
    alertTitle: 'ORBITAL SHIFT',
    alertMessage: 'PLANETARY ORBIT SHIFT // SAPPHIRE GAS GIANT INCLINATION ALTERED',
    severity: 'NOTICE',
    severityLevel: 1.8,
    audioCue: 'advisory',
    environmentReaction: 'Sapphire giant planet tilts 3 degrees toward core; gravitational tidal tug registers on ship compass.',
    cameraShake: 0.35,
    blackHoleInstability: 0.18,
    affectedObject: 'Sapphire Gas Giant',
  },
  {
    eventNumber: 6,
    exactTriggerSeconds: 45,
    displayTime: '14:15',
    eventName: 'GRAVITY WAVE DETECTED',
    alertTitle: 'GRAVITY WAVE',
    alertMessage: 'GRAVITY WAVE DETECTED // RELATIVISTIC SPATIAL RIPPLE',
    severity: 'NOTICE',
    severityLevel: 2.0,
    audioCue: 'advisory',
    environmentReaction: 'Coherent metric wave ripples radially outward from horizon, vibrating ship chassis.',
    cameraShake: 0.40,
    blackHoleInstability: 0.20,
    affectedObject: 'Relativistic Metric Field',
  },
  {
    eventNumber: 7,
    exactTriggerSeconds: 55,
    displayTime: '14:05',
    eventName: 'ASTEROID BELT DISTURBANCE',
    alertTitle: 'ASTEROID BELT',
    alertMessage: 'ASTEROID BELT DISTURBANCE // PERTURBED ORBITS CROSSING TRANSIT LANE',
    severity: 'WARNING',
    severityLevel: 2.2,
    audioCue: 'warning',
    environmentReaction: 'Dense asteroid swarm disperses inward; micrometeorites graze ship energy shield.',
    cameraShake: 0.45,
    blackHoleInstability: 0.22,
    affectedObject: 'Perimeter Asteroid Belt',
  },
  {
    eventNumber: 8,
    exactTriggerSeconds: 64,
    displayTime: '13:56',
    eventName: 'ORBITAL PLATFORM INSTABILITY',
    alertTitle: 'PLATFORM INSTABILITY',
    alertMessage: 'ORBITAL PLATFORM INSTABILITY // STATION THRUSTERS AT MAXIMUM',
    severity: 'WARNING',
    severityLevel: 2.4,
    audioCue: 'warning',
    environmentReaction: 'Orbital observation platforms fire emergency chemical thrusters to resist horizon pull.',
    cameraShake: 0.48,
    blackHoleInstability: 0.24,
    affectedObject: 'Observation Platforms',
  },
  {
    eventNumber: 9,
    exactTriggerSeconds: 73,
    displayTime: '13:47',
    eventName: 'ROUTE STRUCTURE VIBRATION',
    alertTitle: 'ROUTE VIBRATION',
    alertMessage: 'ROUTE STRUCTURE VIBRATION // RESONANT FREQUENCY REACHED',
    severity: 'WARNING',
    severityLevel: 2.6,
    audioCue: 'warning',
    environmentReaction: 'Highway suspension struts resonate at 34 Hz; yellow warning lights flash along pylons.',
    cameraShake: 0.50,
    blackHoleInstability: 0.26,
    affectedObject: 'Highway Suspension Struts',
  },
  {
    eventNumber: 10,
    exactTriggerSeconds: 82,
    displayTime: '13:38',
    eventName: 'BLACK HOLE PULL INTENSIFIES',
    alertTitle: 'BLACK HOLE PULL',
    alertMessage: 'BLACK HOLE PULL INTENSIFIES // ACCRETION VELOCITY ESCALATING',
    severity: 'WARNING',
    severityLevel: 2.8,
    audioCue: 'warning',
    environmentReaction: 'Inner disk plasma acceleration produces intense doppler brightening on approaching limb.',
    cameraShake: 0.55,
    blackHoleInstability: 0.28,
    affectedObject: 'Accretion Disk Inner Edge',
  },
  {
    eventNumber: 11,
    exactTriggerSeconds: 91,
    displayTime: '13:29',
    eventName: 'SATELLITE ORBIT FAILURE',
    alertTitle: 'SATELLITE FAILURE',
    alertMessage: 'SATELLITE ORBIT FAILURE // COMMUNICATIONS RELAYS DECAYING',
    severity: 'WARNING',
    severityLevel: 3.0,
    audioCue: 'warning',
    environmentReaction: 'Relay satellites plunge across lower atmosphere; telemetry signal flickers momentarily.',
    cameraShake: 0.58,
    blackHoleInstability: 0.30,
    affectedObject: 'Relay Satellite Grid',
  },
  {
    eventNumber: 12,
    exactTriggerSeconds: 100,
    displayTime: '13:20',
    eventName: 'SPACE DEBRIS INGRESS',
    alertTitle: 'DEBRIS INGRESS',
    alertMessage: 'SPACE DEBRIS INGRESS // METEORIC SHOWER CROSSING FLIGHT PATH',
    severity: 'WARNING',
    severityLevel: 3.2,
    audioCue: 'warning',
    environmentReaction: 'Superheated silicate debris streaks across canopy with glowing amber plasma trails.',
    cameraShake: 0.60,
    blackHoleInstability: 0.32,
    affectedObject: 'Upper Flight Corridor',
  },
  {
    eventNumber: 13,
    exactTriggerSeconds: 109,
    displayTime: '13:11',
    eventName: 'PLANETARY TIDAL STRESS',
    alertTitle: 'TIDAL STRESS',
    alertMessage: 'PLANETARY TIDAL STRESS // EMERALD ICE PLANET CRACKING',
    severity: 'WARNING',
    severityLevel: 3.4,
    audioCue: 'warning',
    environmentReaction: 'Emerald ice world shows visible glacial fissures; reflective ice plumes erupt into orbit.',
    cameraShake: 0.62,
    blackHoleInstability: 0.34,
    affectedObject: 'Emerald Ice Planet',
  },
  {
    eventNumber: 14,
    exactTriggerSeconds: 118,
    displayTime: '13:02',
    eventName: 'GRAVITATIONAL CURRENT FORMS',
    alertTitle: 'GRAVITATIONAL CURRENT',
    alertMessage: 'GRAVITATIONAL CURRENT FORMS // DRIFT TENDENCY TO SECTOR CORE',
    severity: 'WARNING',
    severityLevel: 3.6,
    audioCue: 'warning',
    environmentReaction: 'Helical gravitational stream channels track particles inward toward black hole equator.',
    cameraShake: 0.65,
    blackHoleInstability: 0.36,
    affectedObject: 'Gravitational Stream Alpha',
  },
  {
    eventNumber: 15,
    exactTriggerSeconds: 127,
    displayTime: '12:53',
    eventName: 'ORBITAL HIGHWAY DISTORTION',
    alertTitle: 'HIGHWAY DISTORTION',
    alertMessage: 'ORBITAL HIGHWAY DISTORTION // TRACK SEGMENT BENDING',
    severity: 'WARNING',
    severityLevel: 3.8,
    audioCue: 'warning',
    environmentReaction: 'Primary highway deck curves with visible warp; magnetic suspension flexes under stress.',
    cameraShake: 0.68,
    blackHoleInstability: 0.38,
    affectedObject: 'Highway Deck Section 04',
  },
  {
    eventNumber: 16,
    exactTriggerSeconds: 136,
    displayTime: '12:44',
    eventName: 'ENERGY GRID INSTABILITY',
    alertTitle: 'ENERGY GRID',
    alertMessage: 'ENERGY GRID INSTABILITY // POWER SURGES ALONG ROUTE PYLONS',
    severity: 'WARNING',
    severityLevel: 4.0,
    audioCue: 'warning',
    environmentReaction: 'Substation arcing leaps between city spires; track illumination strobes irregularly.',
    cameraShake: 0.70,
    blackHoleInstability: 0.40,
    affectedObject: 'Orbital Power Grid',
  },
  {
    eventNumber: 17,
    exactTriggerSeconds: 145,
    displayTime: '12:35',
    eventName: 'FLOATING PLATFORM FAILURE',
    alertTitle: 'PLATFORM FAILURE',
    alertMessage: 'FLOATING PLATFORM FAILURE // CARGO STATION TUMBLING',
    severity: 'WARNING',
    severityLevel: 4.2,
    audioCue: 'warning',
    environmentReaction: 'Cargo staging terminal loses attitude control, rotating slowly against the starry abyss.',
    cameraShake: 0.72,
    blackHoleInstability: 0.42,
    affectedObject: 'Cargo Staging Hub',
  },
  {
    eventNumber: 18,
    exactTriggerSeconds: 155,
    displayTime: '12:25',
    eventName: 'ASTEROID TRAJECTORY SHIFT',
    alertTitle: 'ASTEROID SHIFT',
    alertMessage: 'ASTEROID TRAJECTORY SHIFT // HIGH-VELOCITY IMPACTORS INCOMING',
    severity: 'WARNING',
    severityLevel: 4.4,
    audioCue: 'warning',
    environmentReaction: 'Iron asteroids slingshot through track void space at 8 km/s; proximity warnings chime.',
    cameraShake: 0.75,
    blackHoleInstability: 0.44,
    affectedObject: 'Iron Asteroid Stream',
  },
  {
    eventNumber: 19,
    exactTriggerSeconds: 164,
    displayTime: '12:16',
    eventName: 'STRUCTURAL GRAVITY STRESS',
    alertTitle: 'GRAVITY STRESS',
    alertMessage: 'STRUCTURAL GRAVITY STRESS // HIGH TENSION ON CITY SPAN',
    severity: 'WARNING',
    severityLevel: 4.6,
    audioCue: 'warning',
    environmentReaction: 'Metropolitan suspension cables hum with mechanical tension; micro-fractures propagate.',
    cameraShake: 0.78,
    blackHoleInstability: 0.46,
    affectedObject: 'Metropolitan Suspension Cables',
  },
  {
    eventNumber: 20,
    exactTriggerSeconds: 173,
    displayTime: '12:07',
    eventName: 'FIRST COLLAPSE WAVE',
    alertTitle: 'FIRST COLLAPSE WAVE',
    alertMessage: 'FIRST COLLAPSE WAVE // OUTER SECTOR SEPARATION INITIATED',
    severity: 'WARNING',
    severityLevel: 4.8,
    audioCue: 'warning',
    environmentReaction: 'Deep sub-bass shockwave travels across skybox; outer docking arm tears away in fire.',
    cameraShake: 0.82,
    blackHoleInstability: 0.48,
    affectedObject: 'Outer Docking Facility',
  },

  // =========================================================================
  // EVENTS 21–40: WARNING / EXPANDING COLLAPSE (11:58 → 09:05)
  // =========================================================================
  {
    eventNumber: 21,
    exactTriggerSeconds: 182,
    displayTime: '11:58',
    eventName: 'ORBITAL CITY INSTABILITY',
    alertTitle: 'CITY INSTABILITY',
    alertMessage: 'ORBITAL CITY INSTABILITY // SECTOR FOUNDATIONS SHIFTING',
    severity: 'WARNING',
    severityLevel: 5.0,
    audioCue: 'warning',
    environmentReaction: 'Skyscraper cluster tilts visibly; emergency sirens echo through electromagnetic channels.',
    cameraShake: 0.85,
    blackHoleInstability: 0.50,
    affectedObject: 'Neo-Genesis Spires',
  },
  {
    eventNumber: 22,
    exactTriggerSeconds: 191,
    displayTime: '11:49',
    eventName: 'TOWER NETWORK FAILURE',
    alertTitle: 'TOWER FAILURE',
    alertMessage: 'TOWER NETWORK FAILURE // COMMUNICATIONS SPIRES COLLAPSING',
    severity: 'WARNING',
    severityLevel: 5.2,
    audioCue: 'warning',
    environmentReaction: 'Communication towers buckle; cascading power discharges light up surrounding space clouds.',
    cameraShake: 0.88,
    blackHoleInstability: 0.52,
    affectedObject: 'Communications Spires',
  },
  {
    eventNumber: 23,
    exactTriggerSeconds: 200,
    displayTime: '11:40',
    eventName: 'SPACE ELEVATOR DISTORTION',
    alertTitle: 'SPACE ELEVATOR',
    alertMessage: 'SPACE ELEVATOR DISTORTION // TETHER BENDING PAST SAFETY LIMIT',
    severity: 'WARNING',
    severityLevel: 5.4,
    audioCue: 'warning',
    environmentReaction: 'Carbon nanotube tether bows into a vast arc under tidal shear; climber pods lock clamps.',
    cameraShake: 0.90,
    blackHoleInstability: 0.54,
    affectedObject: 'Space Elevator Tether',
  },
  {
    eventNumber: 24,
    exactTriggerSeconds: 209,
    displayTime: '11:31',
    eventName: 'METROPOLITAN PLATFORM SHIFT',
    alertTitle: 'PLATFORM SHIFT',
    alertMessage: 'METROPOLITAN PLATFORM SHIFT // HABITAT RING DISPLACED',
    severity: 'WARNING',
    severityLevel: 5.5,
    audioCue: 'warning',
    environmentReaction: 'Habitat ring platform shifts 400 meters; transit tubes snap with bright blue plasma bursts.',
    cameraShake: 0.92,
    blackHoleInstability: 0.55,
    affectedObject: 'Habitat Ring Sector',
  },
  {
    eventNumber: 25,
    exactTriggerSeconds: 218,
    displayTime: '11:22',
    eventName: 'MAGNETIC STORM SURGE',
    alertTitle: 'MAGNETIC STORM',
    alertMessage: 'MAGNETIC STORM SURGE // INSTRUMENT POLARIZATION OVERLOAD',
    severity: 'WARNING',
    severityLevel: 5.6,
    audioCue: 'warning',
    environmentReaction: 'Violet synchrotron radiation sweeps across ship windshield; guidance HUD recalibrates.',
    cameraShake: 0.95,
    blackHoleInstability: 0.56,
    affectedObject: 'Accretion Corona Field',
  },
  {
    eventNumber: 26,
    exactTriggerSeconds: 227,
    displayTime: '11:13',
    eventName: 'PLANETARY DEBRIS RELEASE',
    alertTitle: 'DEBRIS RELEASE',
    alertMessage: 'PLANETARY DEBRIS RELEASE // MANTLE FRAGMENTS ENTERING HIGHWAY',
    severity: 'WARNING',
    severityLevel: 5.7,
    audioCue: 'warning',
    environmentReaction: 'Volcanic moon sheds molten basalt chunks that tumble across racing track boundaries.',
    cameraShake: 0.98,
    blackHoleInstability: 0.57,
    affectedObject: 'Volcanic Moon Mantle',
  },
  {
    eventNumber: 27,
    exactTriggerSeconds: 236,
    displayTime: '11:04',
    eventName: 'ROUTE SPLIT DESTABILIZATION',
    alertTitle: 'ROUTE SPLIT',
    alertMessage: 'ROUTE SPLIT DESTABILIZATION // JUNCTION PYLONS VIBRATING',
    severity: 'WARNING',
    severityLevel: 5.8,
    audioCue: 'warning',
    environmentReaction: 'Junction switchpoints warp under asymmetric gravitational pull; track split indicators blink red.',
    cameraShake: 1.00,
    blackHoleInstability: 0.58,
    affectedObject: 'Junction Split Gateways',
  },
  {
    eventNumber: 28,
    exactTriggerSeconds: 245,
    displayTime: '10:55',
    eventName: 'COLLAPSING BRIDGE SECTOR',
    alertTitle: 'BRIDGE SECTOR',
    alertMessage: 'COLLAPSING BRIDGE SECTOR // EXPANSION JOINTS TEARING',
    severity: 'WARNING',
    severityLevel: 5.9,
    audioCue: 'warning',
    environmentReaction: 'Suspension bridge section snaps at joint 07; roadway panels tilt precariously into the void.',
    cameraShake: 1.02,
    blackHoleInstability: 0.59,
    affectedObject: 'Void Bridge Structure',
  },
  {
    eventNumber: 29,
    exactTriggerSeconds: 255,
    displayTime: '10:45',
    eventName: 'ORBITAL RING FRACTURE',
    alertTitle: 'RING FRACTURE',
    alertMessage: 'ORBITAL RING FRACTURE // CIRCUMFERENCE STRUCTURAL TEAR',
    severity: 'WARNING',
    severityLevel: 6.0,
    audioCue: 'warning',
    environmentReaction: 'Giant mega-engineering ring fractures into three segments; decompression clouds expand.',
    cameraShake: 1.05,
    blackHoleInstability: 0.60,
    affectedObject: 'Primary Megastructure Ring',
  },
  {
    eventNumber: 30,
    exactTriggerSeconds: 264,
    displayTime: '10:36',
    eventName: 'GRAVITY TUNNEL COLLAPSE',
    alertTitle: 'TUNNEL COLLAPSE',
    alertMessage: 'GRAVITY TUNNEL COLLAPSE // ACCELERATION FIELD SHUTDOWN',
    severity: 'WARNING',
    severityLevel: 6.1,
    audioCue: 'warning',
    environmentReaction: 'Magnetic conduit tunnel implodes; ship forced into open relativistic space corridor.',
    cameraShake: 1.08,
    blackHoleInstability: 0.61,
    affectedObject: 'Magnetic Transit Tube',
  },
  {
    eventNumber: 31,
    exactTriggerSeconds: 273,
    displayTime: '10:27',
    eventName: 'NEUTRON STAR DISTURBANCE',
    alertTitle: 'NEUTRON STAR',
    alertMessage: 'NEUTRON STAR DISTURBANCE // RELATIVISTIC JET PULSES DETECTED',
    severity: 'WARNING',
    severityLevel: 6.2,
    audioCue: 'warning',
    environmentReaction: 'Binary neutron star accelerates orbit; high-energy gamma pulses light backdrop nebulae.',
    cameraShake: 1.10,
    blackHoleInstability: 0.62,
    affectedObject: 'Binary Neutron Star',
  },
  {
    eventNumber: 32,
    exactTriggerSeconds: 282,
    displayTime: '10:18',
    eventName: 'TIDAL FORCE SURGE',
    alertTitle: 'TIDAL SURGE',
    alertMessage: 'TIDAL FORCE SURGE // SPATIAL DIFFERENTIAL SPIKING',
    severity: 'WARNING',
    severityLevel: 6.3,
    audioCue: 'warning',
    environmentReaction: 'Gravitational gradient between ship nose and tail creates strong stabilizing helm resistance.',
    cameraShake: 1.12,
    blackHoleInstability: 0.63,
    affectedObject: 'Localized Gravitational Gradient',
  },
  {
    eventNumber: 33,
    exactTriggerSeconds: 291,
    displayTime: '10:09',
    eventName: 'SPACE STATION DEORBIT',
    alertTitle: 'STATION DEORBIT',
    alertMessage: 'SPACE STATION DEORBIT // SECTOR ORBIT UNSTABLE',
    severity: 'WARNING',
    severityLevel: 6.4,
    audioCue: 'warning',
    environmentReaction: 'Orbital station spirals inward toward the ergosphere; hull panels glow white-hot from compression.',
    cameraShake: 1.15,
    blackHoleInstability: 0.64,
    affectedObject: 'Orbital Transit Station',
  },
  {
    eventNumber: 34,
    exactTriggerSeconds: 300,
    displayTime: '10:00',
    eventName: 'MAJOR ORBITAL COLLAPSE',
    alertTitle: 'MAJOR COLLAPSE',
    alertMessage: 'MAJOR ORBITAL COLLAPSE // 10:00 THRESHOLD REACHED',
    severity: 'WARNING',
    severityLevel: 6.5,
    audioCue: 'warning',
    environmentReaction: 'Entire outer orbital tier gives way; thousands of structural girders rain down toward horizon.',
    cameraShake: 1.18,
    blackHoleInstability: 0.65,
    affectedObject: 'Outer Orbital Tier',
  },
  {
    eventNumber: 35,
    exactTriggerSeconds: 309,
    displayTime: '09:51',
    eventName: 'PLANETARY RIFT FORMATION',
    alertTitle: 'PLANETARY RIFT',
    alertMessage: 'PLANETARY RIFT FORMATION // LAVA SEAS EXPOSED TO VACUUM',
    severity: 'WARNING',
    severityLevel: 6.6,
    audioCue: 'warning',
    environmentReaction: 'Tectonic canyon on volcanic world splits open; glowing magma fountains shoot into orbit.',
    cameraShake: 1.20,
    blackHoleInstability: 0.66,
    affectedObject: 'Volcanic World Crust',
  },
  {
    eventNumber: 36,
    exactTriggerSeconds: 318,
    displayTime: '09:42',
    eventName: 'CITY SECTOR EVACUATION',
    alertTitle: 'CITY EVACUATION',
    alertMessage: 'CITY SECTOR EVACUATION // CIVILIAN ESCAPE TRANSPORTS FLEEING',
    severity: 'WARNING',
    severityLevel: 6.7,
    audioCue: 'warning',
    environmentReaction: 'Evacuation ships launch from underground hangars; engine plumes create chaotic turbulent wakes.',
    cameraShake: 1.22,
    blackHoleInstability: 0.67,
    affectedObject: 'Metropolitan Hangars',
  },
  {
    eventNumber: 37,
    exactTriggerSeconds: 327,
    displayTime: '09:33',
    eventName: 'EMERGENCY ROUTE ACTIVATION',
    alertTitle: 'EMERGENCY ROUTE',
    alertMessage: 'EMERGENCY ROUTE ACTIVATED // BYPASS CORRIDORS POWERED ON',
    severity: 'WARNING',
    severityLevel: 6.8,
    audioCue: 'warning',
    environmentReaction: 'Emergency bypass ramps ignite with high-intensity amber beacons; shortcut path clears.',
    cameraShake: 1.25,
    blackHoleInstability: 0.68,
    affectedObject: 'Emergency Bypass Ramps',
  },
  {
    eventNumber: 38,
    exactTriggerSeconds: 336,
    displayTime: '09:24',
    eventName: 'ORBITAL RAMP FAILURE',
    alertTitle: 'RAMP FAILURE',
    alertMessage: 'ORBITAL RAMP FAILURE // ELEVATED LAUNCH TRESTLE DETACHING',
    severity: 'WARNING',
    severityLevel: 6.9,
    audioCue: 'warning',
    environmentReaction: 'Elevated launch trestle separates from support tower, floating free into track airspace.',
    cameraShake: 1.28,
    blackHoleInstability: 0.69,
    affectedObject: 'Elevated Launch Trestle',
  },
  {
    eventNumber: 39,
    exactTriggerSeconds: 345,
    displayTime: '09:15',
    eventName: 'DEBRIS STORM',
    alertTitle: 'DEBRIS STORM',
    alertMessage: 'DEBRIS STORM // DENSE IMPACT FIELD INTERSECTING FLIGHT PATH',
    severity: 'WARNING',
    severityLevel: 7.0,
    audioCue: 'warning',
    environmentReaction: 'Hypervelocity cloud of shredded plating sweeps across the route; hull impacts register.',
    cameraShake: 1.30,
    blackHoleInstability: 0.70,
    affectedObject: 'Hypervelocity Debris Cloud',
  },
  {
    eventNumber: 40,
    exactTriggerSeconds: 355,
    displayTime: '09:05',
    eventName: 'SECOND COLLAPSE WAVE',
    alertTitle: 'SECOND COLLAPSE WAVE',
    alertMessage: 'SECOND COLLAPSE WAVE // CORE HIGHWAY SECTORS FRACTURING',
    severity: 'WARNING',
    severityLevel: 7.0,
    audioCue: 'warning',
    environmentReaction: 'Massive gravitational shockwave cascades through structures; skybox lighting shifts to blood red.',
    cameraShake: 1.35,
    blackHoleInstability: 0.71,
    affectedObject: 'Core Highway Network',
  },

  // =========================================================================
  // EVENTS 41–60: DANGER / CRITICAL ACCELERATION (08:56 → 06:04)
  // =========================================================================
  {
    eventNumber: 41,
    exactTriggerSeconds: 364,
    displayTime: '08:56',
    eventName: 'GRAVITY WELL EXPANSION',
    alertTitle: 'GRAVITY WELL',
    alertMessage: 'GRAVITY WELL EXPANDING // SCHWARZSCHILD RADIUS SWELLING',
    severity: 'DANGER',
    severityLevel: 7.2,
    audioCue: 'danger',
    environmentReaction: 'Black hole event horizon visibly swells in size; backdrop constellations compress tightly.',
    cameraShake: 1.38,
    blackHoleInstability: 0.72,
    affectedObject: 'Schwarzschild Boundary',
  },
  {
    eventNumber: 42,
    exactTriggerSeconds: 373,
    displayTime: '08:47',
    eventName: 'ORBITAL HIGHWAY FRACTURE',
    alertTitle: 'HIGHWAY FRACTURE',
    alertMessage: 'ORBITAL HIGHWAY FRACTURE // MAIN ROADWAY SPLITTING OPEN',
    severity: 'DANGER',
    severityLevel: 7.3,
    audioCue: 'danger',
    environmentReaction: 'Roadway tarmac splits with 50-meter gap; magnetic containment arcs violently bridge the chasm.',
    cameraShake: 1.40,
    blackHoleInstability: 0.73,
    affectedObject: 'Highway Sector 09',
  },
  {
    eventNumber: 43,
    exactTriggerSeconds: 382,
    displayTime: '08:38',
    eventName: 'FUTURE CITY SECTOR COLLAPSE',
    alertTitle: 'CITY SECTOR COLLAPSE',
    alertMessage: 'FUTURE CITY SECTOR COLLAPSE // MEGAPOLIS TOWERS TOPPLING',
    severity: 'DANGER',
    severityLevel: 7.4,
    audioCue: 'danger',
    environmentReaction: 'Cluster of crystalline spires collapses into itself; debris cloud glows with electrical fire.',
    cameraShake: 1.42,
    blackHoleInstability: 0.74,
    affectedObject: 'Metropolis Tower Complex',
  },
  {
    eventNumber: 44,
    exactTriggerSeconds: 391,
    displayTime: '08:29',
    eventName: 'PLANETARY RING DISTORTION',
    alertTitle: 'RING DISTORTION',
    alertMessage: 'PLANETARY RING DISTORTION // ICE PARTICLES FUNNELING TO SINGULARITY',
    severity: 'DANGER',
    severityLevel: 7.5,
    audioCue: 'danger',
    environmentReaction: 'Gas giant planetary rings distort into spiral vortex drawn directly toward black hole pole.',
    cameraShake: 1.45,
    blackHoleInstability: 0.75,
    affectedObject: 'Gas Giant Planetary Rings',
  },
  {
    eventNumber: 45,
    exactTriggerSeconds: 400,
    displayTime: '08:20',
    eventName: 'MASSIVE ASTEROID BREAKUP',
    alertTitle: 'ASTEROID BREAKUP',
    alertMessage: 'MASSIVE ASTEROID BREAKUP // KILOMETER-SIZED ROCK SHATTERING',
    severity: 'DANGER',
    severityLevel: 7.6,
    audioCue: 'danger',
    environmentReaction: 'Gigantic central asteroid shatters into thousands of glowing fragments under tidal shear.',
    cameraShake: 1.48,
    blackHoleInstability: 0.76,
    affectedObject: 'Ceres-Class Asteroid Core',
  },
  {
    eventNumber: 46,
    exactTriggerSeconds: 409,
    displayTime: '08:11',
    eventName: 'ESCAPE ROUTE DESTABILIZATION',
    alertTitle: 'ESCAPE ROUTE DESTABILIZED',
    alertMessage: 'ESCAPE ROUTE DESTABILIZATION // GUIDANCE BEACONS OFFLINE',
    severity: 'DANGER',
    severityLevel: 7.7,
    audioCue: 'danger',
    environmentReaction: 'Primary escape vector guidance lights flicker out; backup holographic markers illuminate.',
    cameraShake: 1.50,
    blackHoleInstability: 0.77,
    affectedObject: 'Escape Vector Guidance Beacons',
  },
  {
    eventNumber: 47,
    exactTriggerSeconds: 418,
    displayTime: '08:02',
    eventName: 'ORBITAL TOWER COLLAPSE',
    alertTitle: 'TOWER COLLAPSE',
    alertMessage: 'ORBITAL TOWER COLLAPSE // ENERGY PYLON 03 TEARING LOOSE',
    severity: 'DANGER',
    severityLevel: 7.8,
    audioCue: 'danger',
    environmentReaction: 'Massive energy distribution tower shears at foundation; giant structural beam crosses path.',
    cameraShake: 1.52,
    blackHoleInstability: 0.78,
    affectedObject: 'Energy Distribution Tower 03',
  },
  {
    eventNumber: 48,
    exactTriggerSeconds: 427,
    displayTime: '07:53',
    eventName: 'ENERGY CORE FAILURE',
    alertTitle: 'ENERGY CORE FAILURE',
    alertMessage: 'ENERGY CORE FAILURE // REACTOR BREACH PROPAGATING',
    severity: 'DANGER',
    severityLevel: 7.9,
    audioCue: 'danger',
    environmentReaction: 'City sub-surface fusion reactor detonates with silent cyan fireball expanding into space.',
    cameraShake: 1.55,
    blackHoleInstability: 0.79,
    affectedObject: 'Orbital Fusion Core',
  },
  {
    eventNumber: 49,
    exactTriggerSeconds: 436,
    displayTime: '07:44',
    eventName: 'GRAVITY SLINGSHOT DISTORTION',
    alertTitle: 'SLINGSHOT DISTORTION',
    alertMessage: 'GRAVITY SLINGSHOT DISTORTION // TRAJECTORY OVERSTEER ACTIVE',
    severity: 'DANGER',
    severityLevel: 8.0,
    audioCue: 'danger',
    environmentReaction: 'Intense gravitational slingshot force pulls ship sideways toward inner event horizon.',
    cameraShake: 1.58,
    blackHoleInstability: 0.80,
    affectedObject: 'Ergosphere Slingshot Vector',
  },
  {
    eventNumber: 50,
    exactTriggerSeconds: 445,
    displayTime: '07:35',
    eventName: 'MIDPOINT COLLAPSE',
    alertTitle: 'MIDPOINT COLLAPSE',
    alertMessage: 'MIDPOINT COLLAPSE // 50% TIMELINE CATASTROPHE MILESTONE',
    severity: 'DANGER',
    severityLevel: 8.0,
    audioCue: 'danger',
    environmentReaction: 'Half of civilization infrastructure is now compromised; massive cosmic light flash illuminates sky.',
    cameraShake: 1.60,
    blackHoleInstability: 0.81,
    affectedObject: 'Central Infrastructure Backbone',
  },
  {
    eventNumber: 51,
    exactTriggerSeconds: 455,
    displayTime: '07:25',
    eventName: 'PLANETARY TIDAL BREAK',
    alertTitle: 'PLANETARY BREAK',
    alertMessage: 'PLANETARY TIDAL BREAK // EMERALD ICE PLANET DISINTEGRATING',
    severity: 'DANGER',
    severityLevel: 8.1,
    audioCue: 'danger',
    environmentReaction: 'Ice planet breaks into three giant tectonic plates with crystalline debris filling sector.',
    cameraShake: 1.62,
    blackHoleInstability: 0.82,
    affectedObject: 'Emerald Ice Planet Core',
  },
  {
    eventNumber: 52,
    exactTriggerSeconds: 464,
    displayTime: '07:16',
    eventName: 'ORBITAL CITY FRACTURE',
    alertTitle: 'CITY FRACTURE',
    alertMessage: 'ORBITAL CITY FRACTURE // FLOATING FOUNDATION CRACKING IN HALF',
    severity: 'DANGER',
    severityLevel: 8.2,
    audioCue: 'danger',
    environmentReaction: 'Floating metropolis bedrock splits apart; skyscrapers topple horizontally across void.',
    cameraShake: 1.65,
    blackHoleInstability: 0.83,
    affectedObject: 'Floating Metropolis Bedrock',
  },
  {
    eventNumber: 53,
    exactTriggerSeconds: 473,
    displayTime: '07:07',
    eventName: 'ROUTE NETWORK FAILURE',
    alertTitle: 'NETWORK FAILURE',
    alertMessage: 'ROUTE NETWORK FAILURE // SECONDARY TRACK LOOPS DESTROYED',
    severity: 'DANGER',
    severityLevel: 8.3,
    audioCue: 'danger',
    environmentReaction: 'Secondary loop tracks plunge into the event horizon; player route narrowed to core lines.',
    cameraShake: 1.68,
    blackHoleInstability: 0.84,
    affectedObject: 'Secondary Track Loops',
  },
  {
    eventNumber: 54,
    exactTriggerSeconds: 482,
    displayTime: '06:58',
    eventName: 'SPACE BRIDGE COLLAPSE',
    alertTitle: 'SPACE BRIDGE',
    alertMessage: 'SPACE BRIDGE COLLAPSE // CENTRAL ARCHWAY DISINTEGRATING',
    severity: 'DANGER',
    severityLevel: 8.4,
    audioCue: 'danger',
    environmentReaction: 'Grand space bridge arch snaps into spinning girder fragments; jump booster activates.',
    cameraShake: 1.70,
    blackHoleInstability: 0.85,
    affectedObject: 'Grand Space Bridge Arch',
  },
  {
    eventNumber: 55,
    exactTriggerSeconds: 491,
    displayTime: '06:49',
    eventName: 'DEBRIS STREAM ACCELERATION',
    alertTitle: 'DEBRIS ACCELERATION',
    alertMessage: 'DEBRIS STREAM ACCELERATION // RELATIVISTIC SHRAPNEL AT 0.2C',
    severity: 'DANGER',
    severityLevel: 8.5,
    audioCue: 'danger',
    environmentReaction: 'Debris streams accelerated by relativistic frame dragging whip past cockpit at extreme speeds.',
    cameraShake: 1.72,
    blackHoleInstability: 0.86,
    affectedObject: 'Relativistic Shrapnel Stream',
  },
  {
    eventNumber: 56,
    exactTriggerSeconds: 500,
    displayTime: '06:40',
    eventName: 'NEUTRON STAR GRAVITY SURGE',
    alertTitle: 'NEUTRON SURGE',
    alertMessage: 'NEUTRON STAR GRAVITY SURGE // PULSAR SWEEP INTERSECTING FLIGHT VECTOR',
    severity: 'DANGER',
    severityLevel: 8.5,
    audioCue: 'danger',
    environmentReaction: 'Pulsar beam sweeps across sector; blinding ultraviolet strobe illuminates black hole silhouette.',
    cameraShake: 1.75,
    blackHoleInstability: 0.87,
    affectedObject: 'Neutron Star Pulsar Beam',
  },
  {
    eventNumber: 57,
    exactTriggerSeconds: 509,
    displayTime: '06:31',
    eventName: 'PLANETARY SPAGHETTIFICATION BEGINS',
    alertTitle: 'PLANETARY SPAGHETTIFICATION',
    alertMessage: 'PLANETARY SPAGHETTIFICATION DETECTED // TIDAL FORCES RISING',
    severity: 'DANGER',
    severityLevel: 8.6,
    audioCue: 'danger',
    environmentReaction: 'Distant sapphire planet visibly elongates into a crescent teardrop drawn toward singularity.',
    cameraShake: 1.78,
    blackHoleInstability: 0.88,
    affectedObject: 'Sapphire Planet Mantle',
  },
  {
    eventNumber: 58,
    exactTriggerSeconds: 518,
    displayTime: '06:22',
    eventName: 'ORBITAL STRUCTURES STRETCH',
    alertTitle: 'STRUCTURES STRETCHING',
    alertMessage: 'ORBITAL STRUCTURES STRETCHING // MAINTAIN COURSE',
    severity: 'DANGER',
    severityLevel: 8.7,
    audioCue: 'danger',
    environmentReaction: 'Towers and highway pylons stretch vertically along tidal lines like molten glass.',
    cameraShake: 1.80,
    blackHoleInstability: 0.89,
    affectedObject: 'Orbital Highway Pylons',
  },
  {
    eventNumber: 59,
    exactTriggerSeconds: 527,
    displayTime: '06:13',
    eventName: 'ESCAPE CORRIDOR COLLAPSE',
    alertTitle: 'CORRIDOR COLLAPSE',
    alertMessage: 'ESCAPE CORRIDOR COLLAPSE // INTERMEDIATE EVAC CORRIDOR CRUSHED',
    severity: 'DANGER',
    severityLevel: 8.8,
    audioCue: 'danger',
    environmentReaction: 'Evacuation transit tube 02 crushed by gravitational compression wave.',
    cameraShake: 1.82,
    blackHoleInstability: 0.90,
    affectedObject: 'Evac Corridor 02',
  },
  {
    eventNumber: 60,
    exactTriggerSeconds: 536,
    displayTime: '06:04',
    eventName: 'THIRD COLLAPSE WAVE',
    alertTitle: 'THIRD COLLAPSE WAVE',
    alertMessage: 'THIRD COLLAPSE WAVE // METROPOLIS ANCHORS SEVERED',
    severity: 'DANGER',
    severityLevel: 8.9,
    audioCue: 'danger',
    environmentReaction: 'Entire inner city anchor grid shears free; skyscrapers tumbling into black hole accretion disk.',
    cameraShake: 1.85,
    blackHoleInstability: 0.91,
    affectedObject: 'Inner City Anchor Grid',
  },

  // =========================================================================
  // EVENTS 61–75: CRITICAL / CRITICAL TIMELINE (05:55 → 03:47)
  // =========================================================================
  {
    eventNumber: 61,
    exactTriggerSeconds: 545,
    displayTime: '05:55',
    eventName: 'GRAVITY FIELD CRITICAL',
    alertTitle: 'FIELD CRITICAL',
    alertMessage: 'GRAVITY FIELD CRITICAL // HULL SHEAR STRESS AT 85%',
    severity: 'CRITICAL',
    severityLevel: 9.0,
    audioCue: 'critical',
    environmentReaction: 'Ship chassis groans under extreme gravitational compression; HUD displays red stress markers.',
    cameraShake: 1.88,
    blackHoleInstability: 0.92,
    affectedObject: 'Ship Structural Hull',
  },
  {
    eventNumber: 62,
    exactTriggerSeconds: 555,
    displayTime: '05:45',
    eventName: 'ORBITAL RING BREAKUP',
    alertTitle: 'RING BREAKUP',
    alertMessage: 'ORBITAL RING BREAKUP // FINAL MEGASTRUCTURE ARCHES COLLAPSING',
    severity: 'CRITICAL',
    severityLevel: 9.1,
    audioCue: 'critical',
    environmentReaction: 'Final arches of orbital ring disintegrate; colossal debris blocks rain through racing zone.',
    cameraShake: 1.90,
    blackHoleInstability: 0.93,
    affectedObject: 'Megastructure Arch Remnants',
  },
  {
    eventNumber: 63,
    exactTriggerSeconds: 564,
    displayTime: '05:36',
    eventName: 'PLANETARY COLLISION WARNING',
    alertTitle: 'COLLISION WARNING',
    alertMessage: 'PLANETARY COLLISION WARNING // TWO WORLDS ON INTERSECTING VECTORS',
    severity: 'CRITICAL',
    severityLevel: 9.2,
    audioCue: 'critical',
    environmentReaction: 'Volcanic world and emerald ice remnant on collision course; horizon flare intensifies.',
    cameraShake: 1.92,
    blackHoleInstability: 0.93,
    affectedObject: 'Colliding Planetary Bodies',
  },
  {
    eventNumber: 64,
    exactTriggerSeconds: 573,
    displayTime: '05:27',
    eventName: 'ASTEROID IMPACT CHAIN',
    alertTitle: 'IMPACT CHAIN',
    alertMessage: 'ASTEROID IMPACT CHAIN // EXPLOSIVE IMPACTS ALONG ROADWAY',
    severity: 'CRITICAL',
    severityLevel: 9.2,
    audioCue: 'critical',
    environmentReaction: 'Chain of asteroid detonations shatters tarmac segments directly ahead of racer.',
    cameraShake: 1.95,
    blackHoleInstability: 0.94,
    affectedObject: 'Highway Roadbed Structure',
  },
  {
    eventNumber: 65,
    exactTriggerSeconds: 582,
    displayTime: '05:18',
    eventName: 'FUTURISTIC CITY DISINTEGRATION',
    alertTitle: 'CITY DISINTEGRATION',
    alertMessage: 'FUTURISTIC CITY DISINTEGRATING // ATOMIC BONDS FAILING UNDER TIDAL FORCES',
    severity: 'CRITICAL',
    severityLevel: 9.3,
    audioCue: 'critical',
    environmentReaction: 'Metropolis structures break down at atomic level into glowing streams of ionized subatomic plasma.',
    cameraShake: 1.98,
    blackHoleInstability: 0.94,
    affectedObject: 'City Structure Matter',
  },
  {
    eventNumber: 66,
    exactTriggerSeconds: 591,
    displayTime: '05:09',
    eventName: 'ROUTE GRAVITY REVERSAL',
    alertTitle: 'GRAVITY REVERSAL',
    alertMessage: 'ROUTE GRAVITY REVERSAL // INERTIAL DAMPENERS OVERLOADED',
    severity: 'CRITICAL',
    severityLevel: 9.3,
    audioCue: 'critical',
    environmentReaction: 'Transient gravitational repulsion wave flips track dust upwards before collapsing inward.',
    cameraShake: 2.00,
    blackHoleInstability: 0.95,
    affectedObject: 'Inertial Dampener Grid',
  },
  {
    eventNumber: 67,
    exactTriggerSeconds: 600,
    displayTime: '05:00',
    eventName: 'FIVE-MINUTE CRITICAL POINT',
    alertTitle: '5-MINUTE CRITICAL',
    alertMessage: 'FIVE-MINUTE CRITICAL POINT // TERMINAL EVACUATION WINDOW OPEN',
    severity: 'CRITICAL',
    severityLevel: 9.4,
    audioCue: 'critical',
    environmentReaction: '05:00 threshold crossed; skybox turns black and ultraviolet; emergency audio siren engages.',
    cameraShake: 2.05,
    blackHoleInstability: 0.95,
    affectedObject: 'Universal Sector State',
  },
  {
    eventNumber: 68,
    exactTriggerSeconds: 609,
    displayTime: '04:51',
    eventName: 'EMERGENCY LAUNCHER ACTIVATED',
    alertTitle: 'LAUNCHER ACTIVATED',
    alertMessage: 'EMERGENCY LAUNCHER ACTIVATED // ROUTE 01 MAGNETIC LOCK CHARGING',
    severity: 'CRITICAL',
    severityLevel: 9.4,
    audioCue: 'critical',
    environmentReaction: 'Physical Orbital Launcher tower powers on; three giant acceleration rings glow with emerald light.',
    cameraShake: 2.05,
    blackHoleInstability: 0.96,
    affectedObject: 'Orbital Launcher Tower',
  },
  {
    eventNumber: 69,
    exactTriggerSeconds: 618,
    displayTime: '04:42',
    eventName: 'ESCAPE PLATFORM FAILURE',
    alertTitle: 'PLATFORM FAILURE',
    alertMessage: 'ESCAPE PLATFORM FAILURE // SECONDARY PAD COLLAPSING',
    severity: 'CRITICAL',
    severityLevel: 9.5,
    audioCue: 'critical',
    environmentReaction: 'Emergency pad 02 drops into event horizon; pilot redirected to primary launcher route.',
    cameraShake: 2.10,
    blackHoleInstability: 0.96,
    affectedObject: 'Emergency Pad 02',
  },
  {
    eventNumber: 70,
    exactTriggerSeconds: 627,
    displayTime: '04:33',
    eventName: 'BLACK HOLE TIDAL SURGE',
    alertTitle: 'TIDAL SURGE',
    alertMessage: 'BLACK HOLE TIDAL SURGE // PHOTON RING DIAMETER EXPANDING',
    severity: 'CRITICAL',
    severityLevel: 9.5,
    audioCue: 'critical',
    environmentReaction: 'Blinding secondary photon ring wraps around black hole shadow; relativistic jets fire upward.',
    cameraShake: 2.12,
    blackHoleInstability: 0.96,
    affectedObject: 'Photon Ring Secondary Arc',
  },
  {
    eventNumber: 71,
    exactTriggerSeconds: 636,
    displayTime: '04:24',
    eventName: 'PLANETARY ORBIT BREAKDOWN',
    alertTitle: 'ORBIT BREAKDOWN',
    alertMessage: 'PLANETARY ORBIT BREAKDOWN // ALL SATELLITE WORLDS SPIRALING INWARD',
    severity: 'CRITICAL',
    severityLevel: 9.5,
    audioCue: 'critical',
    environmentReaction: 'Seven planetary bodies spiral rapidly toward accretion disk; skybox filled with burning planets.',
    cameraShake: 2.15,
    blackHoleInstability: 0.97,
    affectedObject: 'Planetary System Orbits',
  },
  {
    eventNumber: 72,
    exactTriggerSeconds: 645,
    displayTime: '04:15',
    eventName: 'COLLAPSING SPACE HIGHWAY',
    alertTitle: 'COLLAPSING HIGHWAY',
    alertMessage: 'COLLAPSING SPACE HIGHWAY // ROADWAY DISINTEGRATING IN RACER WAKE',
    severity: 'CRITICAL',
    severityLevel: 9.6,
    audioCue: 'critical',
    environmentReaction: 'Tarmac behind the racer disintegrates into black void; cannot reverse or brake.',
    cameraShake: 2.18,
    blackHoleInstability: 0.97,
    affectedObject: 'Racing Track Roadbed',
  },
  {
    eventNumber: 73,
    exactTriggerSeconds: 655,
    displayTime: '04:05',
    eventName: 'MASS DEBRIS ACCELERATION',
    alertTitle: 'DEBRIS ACCELERATION',
    alertMessage: 'MASS DEBRIS ACCELERATION // WALL OF MATTER APPROACHING FROM BEHIND',
    severity: 'CRITICAL',
    severityLevel: 9.6,
    audioCue: 'critical',
    environmentReaction: 'Destruction front of crushed structures pursues ship at match velocity.',
    cameraShake: 2.20,
    blackHoleInstability: 0.97,
    affectedObject: 'Destruction Front Wall',
  },
  {
    eventNumber: 74,
    exactTriggerSeconds: 664,
    displayTime: '03:56',
    eventName: 'ORBITAL CITY CORE FAILURE',
    alertTitle: 'CORE FAILURE',
    alertMessage: 'ORBITAL CITY CORE FAILURE // CENTRAL COMMAND COMPLEX GONE',
    severity: 'CRITICAL',
    severityLevel: 9.7,
    audioCue: 'critical',
    environmentReaction: 'Last central command spire implodes with blinding electrical nova flash.',
    cameraShake: 2.22,
    blackHoleInstability: 0.98,
    affectedObject: 'Central Command Complex',
  },
  {
    eventNumber: 75,
    exactTriggerSeconds: 673,
    displayTime: '03:47',
    eventName: 'FOURTH COLLAPSE WAVE',
    alertTitle: 'FOURTH COLLAPSE WAVE',
    alertMessage: 'FOURTH COLLAPSE WAVE // TERMINAL SECTOR COLLAPSE IN FULL PROGRESS',
    severity: 'CRITICAL',
    severityLevel: 9.7,
    audioCue: 'critical',
    environmentReaction: 'Catastrophic spacetime tear opens along entire track horizon; stars smeared into circular halos.',
    cameraShake: 2.25,
    blackHoleInstability: 0.98,
    affectedObject: 'Spacetime Continuum Fabric',
  },

  // =========================================================================
  // EVENTS 76–90: EMERGENCY / TERMINAL BREAKDOWN (03:38 → 01:31)
  // =========================================================================
  {
    eventNumber: 76,
    exactTriggerSeconds: 682,
    displayTime: '03:38',
    eventName: 'ALL ROUTES DESTABILIZING',
    alertTitle: 'ALL ROUTES DESTABILIZING',
    alertMessage: 'ALL ROUTES DESTABILIZING // MAINTAIN MAXIMUM FORWARD VELOCITY',
    severity: 'EMERGENCY',
    severityLevel: 9.7,
    audioCue: 'emergency',
    environmentReaction: 'Every track branch suffers structural failure; warning banners flash along remaining pylons.',
    cameraShake: 2.28,
    blackHoleInstability: 0.98,
    affectedObject: 'Unified Track Network',
  },
  {
    eventNumber: 77,
    exactTriggerSeconds: 691,
    displayTime: '03:29',
    eventName: 'EMERGENCY ESCAPE WINDOW',
    alertTitle: 'ESCAPE WINDOW',
    alertMessage: 'EMERGENCY ESCAPE WINDOW // 3 ESCAPE ROUTES VISIBLE AHEAD',
    severity: 'EMERGENCY',
    severityLevel: 9.7,
    audioCue: 'emergency',
    environmentReaction: 'Three physical escape routes illuminated with laser guidance: Route 01, Route 02, Route 03.',
    cameraShake: 2.30,
    blackHoleInstability: 0.98,
    affectedObject: 'Three Terminal Escape Routes',
  },
  {
    eventNumber: 78,
    exactTriggerSeconds: 700,
    displayTime: '03:20',
    eventName: 'GRAVITY STREAM FORMATION',
    alertTitle: 'GRAVITY STREAM',
    alertMessage: 'GRAVITY STREAM FORMATION // RELATIVISTIC INFALL CURRENT ACCELERATING',
    severity: 'EMERGENCY',
    severityLevel: 9.8,
    audioCue: 'emergency',
    environmentReaction: 'Vast river of matter flows past racing highway, dragging free debris at near light speed.',
    cameraShake: 2.32,
    blackHoleInstability: 0.99,
    affectedObject: 'Relativistic Infall Current',
  },
  {
    eventNumber: 79,
    exactTriggerSeconds: 709,
    displayTime: '03:11',
    eventName: 'PLANETARY SPAGHETTIFICATION INTENSIFIES',
    alertTitle: 'SPAGHETTIFICATION INTENSIFIES',
    alertMessage: 'PLANETARY SPAGHETTIFICATION INTENSIFIES // PLANET DRAWN INTO RIBBON',
    severity: 'EMERGENCY',
    severityLevel: 9.8,
    audioCue: 'emergency',
    environmentReaction: 'Sapphire giant planet stretches into a thin glowing matter ribbon circling the black hole.',
    cameraShake: 2.35,
    blackHoleInstability: 0.99,
    affectedObject: 'Sapphire Planet Ribbon',
  },
  {
    eventNumber: 80,
    exactTriggerSeconds: 718,
    displayTime: '03:02',
    eventName: 'ORBITAL CIVILIZATION COLLAPSE',
    alertTitle: 'CIVILIZATION COLLAPSE',
    alertMessage: 'ORBITAL CIVILIZATION COLLAPSE // ZERO POWER GRIDS REMAINING',
    severity: 'EMERGENCY',
    severityLevel: 9.8,
    audioCue: 'emergency',
    environmentReaction: 'Total power extinction across all orbital structures; only emergency beacons remain alight.',
    cameraShake: 2.38,
    blackHoleInstability: 0.99,
    affectedObject: 'Global Civilization Grid',
  },
  {
    eventNumber: 81,
    exactTriggerSeconds: 727,
    displayTime: '02:53',
    eventName: 'CRITICAL TIDAL DISTORTION',
    alertTitle: 'CRITICAL TIDAL',
    alertMessage: 'CRITICAL TIDAL DISTORTION // SPACE GEOMETRY COMPRESSING AHEAD',
    severity: 'EMERGENCY',
    severityLevel: 9.8,
    audioCue: 'emergency',
    environmentReaction: 'Space ahead visibly contracts; track looks shorter as light paths warp sharply.',
    cameraShake: 2.40,
    blackHoleInstability: 0.99,
    affectedObject: 'Metric Space Geometry',
  },
  {
    eventNumber: 82,
    exactTriggerSeconds: 736,
    displayTime: '02:44',
    eventName: 'ESCAPE ROUTE FRACTURE',
    alertTitle: 'ROUTE FRACTURE',
    alertMessage: 'ESCAPE ROUTE FRACTURE // LATERAL SEPARATION ON TRACK DECK',
    severity: 'EMERGENCY',
    severityLevel: 9.8,
    audioCue: 'emergency',
    environmentReaction: 'Track deck fractures; pilot must jump gaps using boost energy to maintain forward momentum.',
    cameraShake: 2.42,
    blackHoleInstability: 0.99,
    affectedObject: 'Track Deck Jump Points',
  },
  {
    eventNumber: 83,
    exactTriggerSeconds: 745,
    displayTime: '02:35',
    eventName: 'MASSIVE DEBRIS CONVERGENCE',
    alertTitle: 'DEBRIS CONVERGENCE',
    alertMessage: 'MASSIVE DEBRIS CONVERGENCE // CORE INGRESS VORTEX SURGING',
    severity: 'EMERGENCY',
    severityLevel: 9.9,
    audioCue: 'emergency',
    environmentReaction: 'Millions of debris shards spiral into a single dense funnel directly behind the racer.',
    cameraShake: 2.45,
    blackHoleInstability: 0.99,
    affectedObject: 'Core Ingress Funnel',
  },
  {
    eventNumber: 84,
    exactTriggerSeconds: 755,
    displayTime: '02:25',
    eventName: 'ORBITAL RING FORMATION',
    alertTitle: 'RING FORMATION',
    alertMessage: 'ORBITAL RING FORMATION // ACCRETION STREAM FORMING CLOSED RING',
    severity: 'EMERGENCY',
    severityLevel: 9.9,
    audioCue: 'emergency',
    environmentReaction: 'Compressed planetary matter forms hyper-dense ring at 1.5 Schwarzschild radii.',
    cameraShake: 2.48,
    blackHoleInstability: 0.99,
    affectedObject: 'Hyper-Dense Plasma Ring',
  },
  {
    eventNumber: 85,
    exactTriggerSeconds: 764,
    displayTime: '02:16',
    eventName: 'PLANETARY MATTER STRETCHING',
    alertTitle: 'MATTER STRETCHING',
    alertMessage: 'PLANETARY MATTER STRETCHING // TIDAL FORCES TEARING CRUST',
    severity: 'EMERGENCY',
    severityLevel: 9.9,
    audioCue: 'emergency',
    environmentReaction: 'Remaining planetary bodies tear into gaseous filaments wrapping around event horizon.',
    cameraShake: 2.50,
    blackHoleInstability: 0.99,
    affectedObject: 'Planetary Remnants',
  },
  {
    eventNumber: 86,
    exactTriggerSeconds: 773,
    displayTime: '02:07',
    eventName: 'BLACK HOLE GRAVITY CRITICAL',
    alertTitle: 'GRAVITY CRITICAL',
    alertMessage: 'BLACK HOLE GRAVITY CRITICAL // LIGHT ITSELF TRAPPED IN RUN ZONE',
    severity: 'EMERGENCY',
    severityLevel: 9.9,
    audioCue: 'emergency',
    environmentReaction: 'Total optical lensing wraps 360 degrees around cockpit; distant universe visible as small ring.',
    cameraShake: 2.52,
    blackHoleInstability: 1.00,
    affectedObject: 'Total Einstein Ring',
  },
  {
    eventNumber: 87,
    exactTriggerSeconds: 782,
    displayTime: '01:58',
    eventName: 'FINAL ROUTE NETWORK FAILURE',
    alertTitle: 'FINAL NETWORK FAILURE',
    alertMessage: 'FINAL ROUTE NETWORK FAILURE // ONLY 3 TERMINAL ARMS SURVIVING',
    severity: 'EMERGENCY',
    severityLevel: 9.9,
    audioCue: 'emergency',
    environmentReaction: 'All standard highways collapsed; only the three dedicated escape routes remain intact.',
    cameraShake: 2.55,
    blackHoleInstability: 1.00,
    affectedObject: 'Three Terminal Routes',
  },
  {
    eventNumber: 88,
    exactTriggerSeconds: 791,
    displayTime: '01:49',
    eventName: 'LAST EMERGENCY ROUTES OPEN',
    alertTitle: 'LAST ROUTES OPEN',
    alertMessage: 'LAST EMERGENCY ROUTES OPEN // ENTER TERMINAL ESCAPE VECTOR NOW',
    severity: 'EMERGENCY',
    severityLevel: 9.9,
    audioCue: 'emergency',
    environmentReaction: 'Terminal junction branches unlock; green beacon lasers guide ship toward Orbital Launcher.',
    cameraShake: 2.58,
    blackHoleInstability: 1.00,
    affectedObject: 'Orbital Launcher Route 01',
  },
  {
    eventNumber: 89,
    exactTriggerSeconds: 800,
    displayTime: '01:40',
    eventName: 'STRUCTURES ENTER GRAVITY STREAM',
    alertTitle: 'STRUCTURES IN STREAM',
    alertMessage: 'STRUCTURES ENTER GRAVITY STREAM // TOWERS SWEPT INTO HORIZON',
    severity: 'EMERGENCY',
    severityLevel: 9.9,
    audioCue: 'emergency',
    environmentReaction: 'Entire city foundations fly past canopy drawn into the dark central void.',
    cameraShake: 2.60,
    blackHoleInstability: 1.00,
    affectedObject: 'City Foundation Remnants',
  },
  {
    eventNumber: 90,
    exactTriggerSeconds: 809,
    displayTime: '01:31',
    eventName: 'FINAL COLLAPSE WAVE',
    alertTitle: 'FINAL COLLAPSE WAVE',
    alertMessage: 'FINAL COLLAPSE WAVE // POINT OF NO RETURN IMMINENT',
    severity: 'EMERGENCY',
    severityLevel: 9.9,
    audioCue: 'emergency',
    environmentReaction: 'Final seismic shockwave rocks the remaining terminal trestle; warning alarms scream.',
    cameraShake: 2.65,
    blackHoleInstability: 1.00,
    affectedObject: 'Terminal Trestle Infrastructure',
  },

  // =========================================================================
  // EVENTS 91–99: FINAL WARNING / HORIZON BREAK (01:22 → 00:09)
  // =========================================================================
  {
    eventNumber: 91,
    exactTriggerSeconds: 818,
    displayTime: '01:22',
    eventName: 'SINGULARITY APPROACH',
    alertTitle: 'SINGULARITY APPROACH',
    alertMessage: 'SINGULARITY APPROACH // HORIZON DISTANCE UNDER 500 METERS',
    severity: 'FINAL_WARNING',
    severityLevel: 9.9,
    audioCue: 'final_warning',
    environmentReaction: 'Black hole shadow fills forward and lower view; intense violet corona flaring.',
    cameraShake: 2.70,
    blackHoleInstability: 1.00,
    affectedObject: 'Event Horizon Surface',
  },
  {
    eventNumber: 92,
    exactTriggerSeconds: 827,
    displayTime: '01:13',
    eventName: 'MASSIVE GRAVITY DISTORTION',
    alertTitle: 'MASSIVE DISTORTION',
    alertMessage: 'MASSIVE GRAVITY DISTORTION // ESCAPE VELOCITY EXCEEDING NORMAL PROPULSION',
    severity: 'FINAL_WARNING',
    severityLevel: 9.9,
    audioCue: 'final_warning',
    environmentReaction: 'Boost energy regeneration locked at maximum; ship must boost continuously to resist pull.',
    cameraShake: 2.75,
    blackHoleInstability: 1.00,
    affectedObject: 'Ship Propulsion Systems',
  },
  {
    eventNumber: 93,
    exactTriggerSeconds: 836,
    displayTime: '01:04',
    eventName: 'FINAL ESCAPE CORRIDOR',
    alertTitle: 'FINAL ESCAPE CORRIDOR',
    alertMessage: 'FINAL ESCAPE CORRIDOR // REACH THE PHYSICAL ORBITAL LAUNCHER',
    severity: 'FINAL_WARNING',
    severityLevel: 9.9,
    audioCue: 'final_warning',
    environmentReaction: 'Orbital Launcher magnetic lock zone visible dead ahead; acceleration ring 1 active.',
    cameraShake: 2.80,
    blackHoleInstability: 1.00,
    affectedObject: 'Magnetic Lock Zone',
  },
  {
    eventNumber: 94,
    exactTriggerSeconds: 845,
    displayTime: '00:55',
    eventName: 'ROUTES BEGIN SPAGHETTIFICATION',
    alertTitle: 'ROUTES SPAGHETTIFYING',
    alertMessage: 'ROUTES BEGIN SPAGHETTIFICATION // TRACK DECK STRETCHING INTO VERTICAL ARCS',
    severity: 'FINAL_WARNING',
    severityLevel: 9.9,
    audioCue: 'final_warning',
    environmentReaction: 'Track tarmac stretching vertically into paper-thin ribbons under tidal forces.',
    cameraShake: 2.85,
    blackHoleInstability: 1.00,
    affectedObject: 'Terminal Track Rails',
  },
  {
    eventNumber: 95,
    exactTriggerSeconds: 855,
    displayTime: '00:45',
    eventName: 'FINAL ESCAPE WINDOW',
    alertTitle: 'FINAL ESCAPE WINDOW',
    alertMessage: 'FINAL ESCAPE WINDOW // SECONDS REMAINING BEFORE ABSOLUTE HORIZON PULL',
    severity: 'FINAL_WARNING',
    severityLevel: 10.0,
    audioCue: 'final_warning',
    environmentReaction: 'Acceleration ring 2 and ring 3 glowing with blinding emerald launch vector guidance.',
    cameraShake: 2.90,
    blackHoleInstability: 1.00,
    affectedObject: 'Acceleration Rings 2 & 3',
  },
  {
    eventNumber: 96,
    exactTriggerSeconds: 864,
    displayTime: '00:36',
    eventName: 'ALL MATTER CONVERGING',
    alertTitle: 'MATTER CONVERGING',
    alertMessage: 'ALL MATTER CONVERGING // ENTIRE SECTOR BEING CONSUMED BY SINGULARITY',
    severity: 'FINAL_WARNING',
    severityLevel: 10.0,
    audioCue: 'final_warning',
    environmentReaction: 'All remaining debris, structures, and planetary remnants form unified vortex into horizon.',
    cameraShake: 2.92,
    blackHoleInstability: 1.00,
    affectedObject: 'Total Accretion Vortex',
  },
  {
    eventNumber: 97,
    exactTriggerSeconds: 873,
    displayTime: '00:27',
    eventName: 'EVENT HORIZON EXPANSION',
    alertTitle: 'HORIZON EXPANSION',
    alertMessage: 'EVENT HORIZON EXPANSION // RUNWAY MARGIN COLLAPSING FAST',
    severity: 'FINAL_WARNING',
    severityLevel: 10.0,
    audioCue: 'final_warning',
    environmentReaction: 'Event horizon expands upward toward launcher gate; final 27 seconds of physical runway.',
    cameraShake: 2.95,
    blackHoleInstability: 1.00,
    affectedObject: 'Event Horizon Surface',
  },
  {
    eventNumber: 98,
    exactTriggerSeconds: 882,
    displayTime: '00:18',
    eventName: 'FINAL GRAVITATIONAL PULL',
    alertTitle: 'FINAL GRAVITATIONAL PULL',
    alertMessage: 'FINAL GRAVITATIONAL PULL // ENGAGE DOCKING / LAUNCH VECTORS NOW',
    severity: 'FINAL_WARNING',
    severityLevel: 10.0,
    audioCue: 'final_warning',
    environmentReaction: 'Tidal forces reach critical threshold; ship flight controls locked onto launcher vector.',
    cameraShake: 2.98,
    blackHoleInstability: 1.00,
    affectedObject: 'Launcher Docking Gate',
  },
  {
    eventNumber: 99,
    exactTriggerSeconds: 891,
    displayTime: '00:09',
    eventName: 'SINGULARITY IMMINENT',
    alertTitle: 'SINGULARITY IMMINENT',
    alertMessage: 'SINGULARITY IMMINENT // FINAL COUNTDOWN ACTIVE',
    severity: 'FINAL_WARNING',
    severityLevel: 10.0,
    audioCue: 'final_warning',
    environmentReaction: 'Horizon break sequence begins; destruction front reaches terminal gate; docking bay secures.',
    cameraShake: 3.00,
    blackHoleInstability: 1.00,
    affectedObject: 'Terminal Escape Vector',
  },

  // =========================================================================
  // EVENT 100: SINGULARITY CRITICAL / FINAL COLLAPSE (00:00)
  // =========================================================================
  {
    eventNumber: 100,
    exactTriggerSeconds: 900,
    displayTime: '00:00',
    eventName: 'SINGULARITY CRITICAL — FINAL COLLAPSE',
    alertTitle: 'SINGULARITY CRITICAL',
    alertMessage: 'SINGULARITY CRITICAL // FINAL COLLAPSE INITIATED',
    severity: 'SINGULARITY_CRITICAL',
    severityLevel: 10.0,
    audioCue: 'collapse',
    environmentReaction: 'The 15:00 clock strikes 00:00; absolute singularity consumes remnants as existing safe zone and ending logic resolves.',
    cameraShake: 3.20,
    blackHoleInstability: 1.00,
    affectedObject: 'Eternal Kerr Singularity',
  },
];

/**
 * Fast O(1) indexed lookup by event number (1 to 100)
 */
const MASTER_EVENT_MAP = new Map<number, FinalCollapseMasterEvent>();
for (const evt of FINAL_COLLAPSE_MASTER_100_TIMELINE) {
  MASTER_EVENT_MAP.set(evt.eventNumber, evt);
}

export function getMasterEventByNumber(eventNumber: number): FinalCollapseMasterEvent {
  const clamped = Math.max(1, Math.min(100, Math.round(eventNumber)));
  return MASTER_EVENT_MAP.get(clamped) || FINAL_COLLAPSE_MASTER_100_TIMELINE[0];
}

/**
 * Resolves the active master event strictly by elapsed seconds from 15:00 (0 to 900s)
 */
export function getMasterEventByElapsedSeconds(elapsedSeconds: number): {
  currentEvent: FinalCollapseMasterEvent;
  nextEvent: FinalCollapseMasterEvent | null;
  secondsUntilNext: number;
} {
  const safeElapsed = Math.max(0, Math.min(900, elapsedSeconds));

  let currentIndex = 1;
  for (let i = FINAL_COLLAPSE_MASTER_100_TIMELINE.length - 1; i >= 0; i--) {
    if (safeElapsed >= FINAL_COLLAPSE_MASTER_100_TIMELINE[i].exactTriggerSeconds) {
      currentIndex = FINAL_COLLAPSE_MASTER_100_TIMELINE[i].eventNumber;
      break;
    }
  }

  const currentEvent = getMasterEventByNumber(currentIndex);
  const nextEvent = currentIndex < 100 ? getMasterEventByNumber(currentIndex + 1) : null;
  const secondsUntilNext = nextEvent ? Math.max(0, nextEvent.exactTriggerSeconds - safeElapsed) : 0;

  return {
    currentEvent,
    nextEvent,
    secondsUntilNext,
  };
}
